### ISSUE TITLE
Attached pictures

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3696] opened 2016-12-01 15:55 UTC
Is regularly here so break the conclusion images attachments.
In the log there are no errors
![78](https://cloud.githubusercontent.com/assets/17574854/20800789/c60f11c2-b7f7-11e6-95cb-35aeec6d1cd8.jpg)

**Comment by frandominguezl** [comment] 2016-12-16 18:07
Can't duplicate the issue. Are you still experiencing this error?

**Comment by Yariksat** [comment] 2016-12-16 18:18
The error remained.
If you select to edit the message and afterwards to save then image begins to displayed. Afterwards after a while her breaks a again.

**Comment by frandominguezl** [comment] 2016-12-16 21:01
Did you try with different pics, as well as different pic size?

**Comment by Yariksat** [comment] 2016-12-17 14:33
Heavier pictures more often break the
Breaks down are constantly miniatures
And most likely it is the old image when their be reloaded the problem like as disappears

**Comment by Yariksat** [comment] 2016-12-25 17:12
> And most likely it is the old image when their be reloaded the problem like as disappears

If you reload the problematic investments then later everything is ok

**Comment by frandominguezl** [comment] 2016-12-28 10:34
Can you please post the images you're using? I can't reproduce the issue with some internet images.

**Comment by Yariksat** [comment] 2016-12-29 17:48
From here, the last message
https://yarik-sat.ru/index.php?topic=340.msg48961#msg48961
![769107455](https://cloud.githubusercontent.com/assets/17574854/21550106/1ad88b54-ce08-11e6-9b38-1f6f042a9c5f.jpg)

**Comment by colinschoen** [comment] 2016-12-29 17:56
Can't replicate with that image either. What is your hosting environment?

**Comment by frandominguezl** [comment] 2016-12-30 12:53
I can't reproduce it either...

@colinschoen He's using SSL, maybe is that related to the issue?

**Comment by Oldiesmann** [comment] 2017-01-10 03:25
I've got SSL enabled on my test board and it works fine for me even with a semi-large file (545kb).

**Comment by Yariksat** [comment] 2017-01-10 15:55
Download the attachment, delete and then re-download the attachment, and then it will be displayed normally.

**Comment by sbulen** [comment] 2017-01-27 21:46
Neat pic, makes a good avatar.  

We just made a few changes to clean up attachment processing.   The changes were merged just this morning.  So, could you please:
(1) Download a fresh set of files from Github.   The attachment changes were in Sources & Themes.  It'd be safest to download & refresh all directories & subdirectories.   
(2) Confirm attachments, avatars & custom avatars are in _3 separate directories_.  Confirm in the admin panel, under Avatar settings and under Attachment settings, that all 3 directories are specified properly & have _no error messages in red text_.  
(3) Confirm all size restrictions make sense under Avatar settings and under Attachment settings.   
(4)  Clean up errors in the attachment & avatar directories by running the Attachment Integrity Test.  Sometimes you need to run this 2-3x to get to a 'no errors found'.   
(5) Retest....

... & let us know how it goes!

**Comment by frandominguezl** [comment] 2017-02-07 19:07
@Yariksat Any more info about this? Did you test anything? Is the error still happening?

**Comment by sbulen** [comment] 2017-02-07 20:45
FYI, I don't think size is an issue.  Most of my attachment testing was with large images, > 2MB and I never had a similar issue.  

It is possible that uploading multiple attachments with confusing attachment size settings can cause an issue.   (E.g., directory auto management on...,  directory max =2.5M, attachment max = 4M, post max = 10M... What will happen with a 2.8M file???)   This is why I wanted to confirm that the attachment size settings were looked at.  A lot of the attachment defaults are small.

**Comment by Yariksat** [comment] 2017-02-10 17:04
Currently I will fail to check out.
You may specify a what changes have been made to edit manually ?

**Comment by sbulen** [comment] 2017-02-19 17:29
Yariksat - 

I'd really suggest a refresh of the forum software.  If you want to know what changes were made, you can search for merged prs, like this:
       is:pr is:merged attachment 

Will give you this list:
       https://github.com/SimpleMachines/SMF2.1/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20attachment

An observation - The broken image links above, I think are for the thumbnails, not the actual images.   I'd right click on one, inspect it, & make sure that the filename and path make sense.  

Shawn

**Comment by sbulen** [comment] 2017-03-03 05:35
Yariksat -

A couple more questions...
1) When you click on the filename (e.g., IMG_2231.jpg above) do the photos display properly?   
2) What do your thumbnail settings look like, under Admin | Attachments & Avatars | Attachment Settings?   

The default settings are listed here, I'd like to know if you are using the defaults:
![image](https://cloud.githubusercontent.com/assets/23568484/23539418/19c4fbd0-ff90-11e6-8195-9a78fd41bc8b.png)

**Comment by Yariksat** [comment] 2017-03-04 08:46
1. Yes . No show only thumbnails
2.  Here are my settings
![93](https://cloud.githubusercontent.com/assets/17574854/23577432/2acd9022-00d0-11e7-8eed-e45ff135586f.jpg)

**Comment by sbulen** [comment] 2017-03-07 03:15
Yariksat - 
Thanks for the info.  I regret to say that I couldn't reproduce this.  My only suggestion now is to find a way to reload the forum files.  
I did find a similar issue, which I'll log separately.  
Shawn

**Comment by colinschoen** [comment] 2017-03-24 04:43
Can't reproduce this at all. If others have this issue please reopen.

**Closed as completed by colinschoen** 2017-03-24 04:43 UTC
Labels: Attachments
