### ISSUE TITLE
incorrect text in edit membergroup

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2766] opened 2015-03-08 23:28 UTC
You can upload custom images to the default theme directory to be able to select them here.

this text is not correct, the image must be in the images/membericons folder for each theme that is being used, not just the default theme.

**Comment by margarett** [comment] 2015-03-20 22:21
I never really used this. How does this work, exactly? Can the same group have different stars in different themes?

**Comment by margarett** [comment] 2015-03-20 22:46
Strange behavior...
The only icons that show up for selection are the one in default theme's "membericons" folder (even if using other theme and other icons exist in that theme). But if said icons don't exist in other theme, it doesn't fallback to default's ones. IMO it should, don't you think?

**Comment by illori** [comment] 2015-03-20 23:58
cant hurt. 

i dont agree with your change here https://github.com/margarett/SMF2.1/commit/3b8d47028aa1a0b6d108a8f2d00dae9d8080f963#diff-7fa5ecbd8c738e177ea868d01f023d59L82

sure it can fall back to default, but we should still be prompting the user to put the images in their themes folder.

that is why the text on the left is wrong but the path was correct.

**Comment by margarett** [comment] 2015-03-21 00:02
I tested with more than one of the themes available for 2.1B1 and I always reproduced the behavior.
**No matter which images are in these theme's "membericons" folder, only the default theme's icons are available for selection.**
 If the same icon exists in the custom theme, that is used. If not, no image is loaded (the replacement "*" is shown)

So IMO, what I changed makes sense, because it is as SMF behaves. Unless I missed something, which is highly likely :tongue: 

edit: damn markup :angry:

**Comment by illori** [comment] 2015-03-21 00:05
well if that is how it works in 2.1. it is a MAJOR regression from 2.0.

if you select a badge/image and put a different one in your theme does the different one show up in the posts?

**Comment by margarett** [comment] 2015-03-21 00:11
If it has the same name, yes.
Until my PR, if it wasn't there (same name) nothing would be shown (just the "asterisk"). Now it falls back to the default theme (which was originally selected in admin panel)

**Comment by illori** [comment] 2015-03-21 10:15
that is fine, but you are telling people not to upload the image to their theme. this will make users think that they can no longer have different images for each theme.

**Comment by margarett** [comment] 2015-04-09 08:14
Can this issue be closed? The PR was merged so... ;)

**Comment by illori** [comment] 2015-04-09 09:14
i dont think so. i still dont agree with the change to default. you still can have the images in your custom themes and right now it makes it look like you can not from this point forward.

**Comment by margarett** [comment] 2015-04-09 10:02
But the fact is that you can only select icons in default theme's folder :P
Maybe it requires a help popop or something?

**Comment by illori** [comment] 2015-04-09 10:05
maybe that needs to be changed to select from your "default" theme instead?

a help popup might not hurt but i dont think it is required.

**Comment by illori** [comment] 2015-04-20 20:42
also might be useful to note about the size of the image that will show.

```
// If this is bigger than 128 in width or 32 in height, skip this one.
                if ($image_info == false || $image_info[0] > 128 || $image_info[1] > 32)
                    continue;
```

**Comment by margarett** [comment] 2015-04-20 20:45
Is there any particular reason for this "hard limit"? The width I can understand, but the height seems a bit too "aggressive" :tongue:

**Comment by illori** [comment] 2015-04-20 20:47
i dont know why, it is in place. i could see some admin asking for a way to set the limit themselves or remove it completely.

**Comment by illori** [comment] 2015-04-21 10:13
also

```
    // Scan the directory.
    $context['possible_icons'] = array();
    if ($files = scandir($settings['default_theme_dir'] . '/images/membericons')) 
```

i think the fix here is to set it to use theme_dir in place of default_theme_dir. last i checked each theme can have their own images so why not just use the theme option here and dump using the default theme for the images?

**Comment by frandominguezl** [comment] 2017-01-10 15:29
Any comments on this @live627 ?

**Closed as completed** 2017-02-16 02:08 UTC
Labels: Theme, Localization
