### ISSUE TITLE
MariaDB not compatible any longer.

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#7070] opened 2021-09-10 09:11 UTC
#### Description
due to #7065 i can no longer upgrade SMF 2.1, it fails to detect a valid version of the mysql db.
### Steps to reproduce
1. run upgrade.php when you are using MariaDB, it errors out that your database version does not meet requirements.
2. 

### Environment (complete as necessary)
- Version/Git revision: upgraded at midnight EDT last night
- Database Type:
- Database Version: MariaDB 10.4.10
- PHP Version: 7.3.12
- wampserver

https://i.imgur.com/54iM4mS.png PHP ini screenshot, i dont know why it has an older version listed here. using wamp server.

### Additional information/references

**Comment by albertlast** [comment] 2021-09-11 04:56
Mysqlnd is the driver and not the mysql version,
So maybe it's the chech written wrong, instead of checking
the version of the driver the check needs to versus the database.

**Comment by WhistlingDonkey** [comment] 2021-09-11 08:31
Confirmed, as far MariaDB 10.3.29 is concerned. The MySQL server version in MariaDB 10.3.29 is 5.5.5 . I don't know what it is for MariaDB 10.4.10. @illori, you can run this php script (filling in the db connection details) to retrieve the MySQL server version for MariaDB 10.4.10. This is both of the db version checks in install.php and upgrade.php.

`
<?php
   //Creating a connection
   $con = mysqli_connect("localhost", "root", "password", "mydb");

   //MySQL Server version
   $version = mysqli_get_server_info($con);
   print("Client Library Version Number (mysqli_get_server_info): ".$version);

   $info = mysqli_get_client_info();
   print("<br>Client Info (mysqli_get_client_info): ".$info);

   //Closing the connection
   mysqli_close($con);
?>
`

This is my output for MariaDB 10.3.29:
Client Library Version Number (mysqli_get_server_info): 5.5.5-10.3.29-MariaDB-0+deb10u1
Client Info (mysqli_get_client_info): mysqlnd 5.0.12-dev - 20150407

SMF runs fine with this version of MariaDB, so it's just the install and upgrade blocking it's use.

As MariaDB is apparently a popular DB, is there a reason, for want of a better word, we don't have "native" support for it?

**Comment by WhistlingDonkey** [comment] 2021-09-11 08:36
OK, what the heck happened with the code there? Try this, and put the php start and end tags at the start and end!

//Start
//Creating a connection
$con = mysqli_connect("localhost", "root", "password", "mydb");

//MySQL Server version
$version = mysqli_get_server_info($con);
print("Client Library Version Number (mysqli_get_server_info): ".$version);

$info = mysqli_get_client_info();
print("<br>Client Info (mysqli_get_client_info): ".$info);

//Closing the connection
mysqli_close($con);
//End

**Comment by albertlast** [comment] 2021-09-11 09:13
The mysql Client information are irrelevant for smf, this has no relation to use database.

**Comment by illori** [comment] 2021-09-11 09:44
Client Library Version Number (mysqli_get_server_info): 5.5.5-10.4.10-MariaDB Client Info (mysqli_get_client_info): mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

**Comment by illori** [comment] 2021-09-11 09:46
@albertlast if you look at the code, it is calling those functions. so either it has to be fixed or adjusted one way or the other.

**Comment by WhistlingDonkey** [comment] 2021-09-11 09:58
Then why is mysqli_get_client_info part of the version check in install.php and upgrade.php? It's version number is being checked (which I think could be the incorrect thing to do) and used if it's version number is less than what the MySQL server version is!

illori, yep that's what I thought it'd be. After the preg_replace function further down in the db version check everything after the dash is stripped off leaving just the version number 5.5.5 = fail!
. . . 
Seriously, shouldn't we be querying mysqli_get_server_version() instead of  mysqli_get_server_info() ?

**Comment by WhistlingDonkey** [comment] 2021-09-11 15:39
Some further research, this is caused by a hack in MariaDB to have a single digit major version for some replication protocol: https://stackoverflow.com/questions/56601304/what-does-the-first-part-of-the-mariadb-version-string-mean#56607492

@illori, you can try this as a workaround. In my.cnf (probably located in /etc/mysql) you can add the following to the `[mariadb]` section and then restart mariadb:

version=10.4.10-MariaDB

This should stop the 5.5.5- from being expressed when the version is requested. Try the script I posted again after changing and restarting. If you can't find my.cnf it could be in various locations. This long page lists all of the locations it could be: https://mariadb.com/kb/en/configuring-mariadb-with-option-files/

I'm not sure how we can effectively fix this, if we check server_version instead of server_info which would negate the issue then we can't use php's inbuilt version_compare function which we also use to compare postgresql's version, unless we rebuilt value returned by server_version into the proper version string.

**Comment by illori** [comment] 2021-09-11 15:55
that may fix it for us, but can we expect all hosts that use MariaDB to add this setting? i bet many would not and tell the users to find another forum to use.

**Comment by WhistlingDonkey** [comment] 2021-09-11 16:59
That's why I said "effectively fix". It does need a proper fix because we can't expect people to have to go and add to my.cnf . We can get the version as an integer by using server_version instead of server_info but then we can't do the check with version_compare, and we need version_compare to check Postgresql's version so the fix for SMF is either to get the version as an integer and rebuild it somehow into the proper version string format, or to strip the 5.5.5- from the start of the version string if it's present.  I gave the workaround to hopefully get you unstuck for now as I won't be looking into the fix 'till tomorrow.

**Comment by live627** [comment] 2021-09-11 17:31
My live server is on mariadb and `mysqli_get_server_version()` returns `50505`; it's on 10.2 and php is 7.1.

My localhost is on mariadb and `mysqli_get_server_version()` returns `100309`; it's on 10.3 and php is 7.3.

**Comment by sbulen** [comment] 2021-09-11 18:24
"Up thru 5.5, MariaDb was a drop-in replacement for mysql."   Not any more.

After that, with the 10.x versions, it's more of a function by function thing.  

https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/

If you consider the lists of incompatibilities minor - and *most* are - then you could attempt a crude map:
5.5 => 5.5
5.6 => 10.0
5.7 => 10.1
8.0 => 10.4

**Comment by sbulen** [comment] 2021-09-11 18:27
> My live server is on mariadb and `mysqli_get_server_version()` returns `50505`; it's on 10.2 and php is 7.1.
> 
> My localhost is on mariadb and `mysqli_get_server_version()` returns `100309`; it's on 10.3 and php is 7.3.

That 10.2 reporting out as 5.5 is confusing....

Same problem Illori sees.

**Comment by albertlast** [comment] 2021-09-11 18:30
Since we support mysql 5.6+ -> mariadb 10.3 or 10.4 is minimum?

**Comment by sbulen** [comment] 2021-09-11 18:32
Looks more like 10.0...

**Comment by live627** [comment] 2021-09-11 21:35
MariaDB seems to always add `5.5.5` to the version string. We can check that it matches and assume that it MariaDB 10.x.

**Comment by sbulen** [comment] 2021-09-12 05:02
Yeah, kinda...

I think the reason 5.5 is specified is that that is the last time they were in sync...

The problem is that 10.4 is wildly different than 10.0.  

10.4 ~= 8.0 and 10.0 ~= 5.6.  

We need something finer than that...  i think we need to parse that whole x.y.z-a.b.c string.

**Comment by WhistlingDonkey** [comment] 2021-09-12 08:06
I believe 5.5.5 was an arbitrary number in that it wasn't tied to any version compatibility, it's simply to do with needing a single digit major version number for replication. A MariaDB aware client library apparently strips this off correctly which is why it seems that some people out in the greater world get the 5.5.5 reported as part of the string and others don't.  There was a little tidbit on it here: https://github.com/joomla/joomla-cms/issues/9062#issuecomment-184742936

I think the easiest way will be, using the current method, is to look for `5.5.5-` at the start of the returned string and strip it off if it's there, and then continue on with the existing preg_replace and version_compare.

I also suggest changing the title of this issue to "Installer and Upgrader not compatible with MariaDB version prefix" as MariaDB is compatible and working fine, it's just the installer and upgrader not knowing about the version prefix.

**Comment by tinoest** [comment] 2021-09-12 08:27
Why not just run the query ‘SELECT VERSION();’ as that returns it correctly to my knowledge.

**Comment by illori** [comment] 2021-09-12 10:13
https://github.com/SimpleMachines/SMF2.1/blob/4084720f849f3741f8da428e5bc8400b2d057d06/Sources/Subs-Admin.php#L64-L84
https://github.com/SimpleMachines/SMF2.1/blob/4084720f849f3741f8da428e5bc8400b2d057d06/Sources/DbExtra-mysql.php#L371-L389

looks like starting here we have come code that does correctly pull the database version. can we reuse this same code in the installer/upgrader to check the version?

on my install it tells me the version of the database is 10.4.10-MariaDB

**Comment by albertlast** [comment] 2021-09-12 15:11
Looks good to me, we only need a test result for Mariadb 10.0

**Comment by jdarwood007** [comment] 2021-09-12 16:45
I'm not sure why we don't just do SELECT VERSION();  There may be a reason.  But if we need to determine the client version for any reason, that should become a separate check.

A workaround though could be to match out the MariaDB
```
		'version_check' => 'global $db_connection; $v = min(mysqli_get_server_info($db_connection), mysqli_get_client_info()); preg_match("~(\d+\.\d+\.\d+(?:-MariaDB))~i", $v, $m); return  !empty($m[0]) ? $m[0] : $v;',
```

Or as mentioned using select version;
```
		'version_check' => 'global $db_connection; return mysqli_fetch_row(mysqli_query($db_connection, "SELECT VERSION();"))[0];',
```

In both cases, this is because MariaDB is not matching the mysql version.

On another note, the utf8 stuff in there is not used at all far as I can find in the code.

**Comment by WhistlingDonkey** [comment] 2021-09-12 17:34
`'version_check' => 'global $db_connection; return mysqli_fetch_row(mysqli_query($db_connection, "SELECT VERSION();"))[0];',` this works well in a test script and saves doing another preg_replace to remove the 5.5.5- prefix, which may disappear in the future.

Checking which had the lower version with `min` for the client version and the server version didn't do anything anyway, the server version was always returned from the argument.

I think we can also tidy up the actual db version checks in install.php and upgrade.php while we are at it so the preg_replace and actual version compare are the same. We have two different ways to do the same thing. Line 883 install.php, Lines 1948 to 1951 upgrade.php

**Comment by jdarwood007** [comment] 2021-09-12 19:22
You can't remove the regex.  Some installs will add junk into the version.  Such as on mine, the version is ``10.3.31-MariaDB-0ubuntu0.20.04.1``

**Comment by WhistlingDonkey** [comment] 2021-09-13 04:24
I wasn't saying to remove the regex, I was saying it saves us from adding another one just for the 5.5.5- prefix on MariaDB.

**Closed as completed** 2021-09-17 00:40 UTC
Labels: Upgrader
