### ISSUE TITLE
issue with installing packages containing hooks

### ISSUE THREAD

**Issue by Underdog-01** [SimpleMachines/SMF#2382] opened 2014-09-27 16:07 UTC
Here is a test package:
http://www.web-develop.ca/index.php?action=dlattach;topic=92.0;attach=163

You will notice one error in the log for install only. 
I believe it is due to the way in which the load_file function has been configured.
Imo this was introduced by Suki from this reference:
https://github.com/SimpleMachines/SMF2.1/commit/fbd85f8920801a715ab5e1415cdbe1e99d4d91b4

The actual error message is being logged from within the call_helper function.
This occurs when a function name is piped through load_file and that function returns the function name (failing to load a file). Since the value of the return variable is not false, it proceeds further to eventually log an error.

What would be a preferred method to fix this?
Perhaps have the load_file function return an array ie.. array('file', $string) or array('func', $string) depending on it being a file or not? and/or.. some condition prior to the error logging?

Regards.

**Comment by MissAllSunday** [comment] 2014-09-27 18:42
load_file will return false if no file was located but a file was indicated on the string.

If the error is been logged by SMf it means your $string hit one of the checks, which leaves me to believe there is some sort of quirkiness in the way load_file is been used or the content of $string.

Question is, how exactly are you adding your hooks?  your package doesn't contain any files or references.

**Comment by MissAllSunday** [comment] 2014-09-27 19:54
OK, you're using plain old 2.0 calls.

Your $string been a function name doesn't make any difference, is_callable can happily accept a string.

The issue isn't on load_file() that function won't do anything if there isn't a | symbol, none of your hooks has it so it will just return the exact string your gave it to it.  Both load_file and call_helper only do things if you tell them to do things, otherwise they just return what was passed.

The issue here is how are you calling your functions and more specifically, when, many people do not know but the place and timing while installing is important, its always advisable to load any files you're gonna use before calling any function on them.

You're using 

``` xml
<readme parsebbc="true">SMF2/readme_PersonalizedBBC.txt</readme>
```

So, the hook you just added is actually been used while you're installing the mod, try to move that part **after** you've done all you have to do.

**Comment by MissAllSunday** [comment] 2014-09-27 20:16
Oh, scratch that...

You're using 

``` php
add_integration_function('integrate_bbc_codes','PersonalizedBBC_codes', true);
```

That "true" on 2.1 means "file" rather than "permanent" https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs.php#L4082

So, add_integration_function is actually adding a pipe which result in a flawed process on call_helper.

I suppose the new params on add_integration_function can be added to the end but I doubt many mod authors care to use that permanent param since its marked as "true" by default so there is no need to add it.

**Closed as completed** 2014-09-27 20:56 UTC

**Comment by Underdog-01** [comment] 2014-09-28 02:57
Alright.. 

this:
add_integration_function('integrate_bbc_codes',PersonalizedBBC_codes', true);

should now be this in SMF 2.1:
add_integration_function('integrate_bbc_codes','$sourcedir/PersonalizedBBC.php|PersonalizedBBC_codes');

It works like this but why only for the integrate_bbc_codes hook?

**Comment by MissAllSunday** [comment] 2014-09-28 14:16
I already made the change, I suppose other mod authors also adds the second argument even if its not really needed.

**Comment by Underdog-01** [comment] 2014-09-28 20:17
The change did not work for the way I was doing it prior as it was still throwing an error even without the true parameter. I had to adjust my installer to detect the SMF version and then a specific 'integrate_bbc_codes' hook depending on that version (with or without the file included for that specific hook).
You can still test your changes with the mod's beta link I posted above as that version's hook install was for SMF 2.0.X if you want to ensure SMF 2.1 is backward compatible. 

The new official copy that I just released on SMF.org has been edited with the file|function included in the hook for SMF 2.1 to circumvent the error. ref. https://github.com/Underdog-01/Personalized_BBC/blob/master/SMF2/PersonalizedBBC_mysql.php

  BBCode mods are not exactly backward compatible anyhow due to the image file type changes so BBCode mod authors will have to release new updates, meaning they can also adjust their install routine.
Unless of course the SMF 2.1 routine is adjusted even further to search for both file types (png .. failing that check for gif).

I am not sure if other various hooks are effected with this install error as I will have to test this further.  
Ideas mentioned here are dependant on whether it is the general goal of the dev team for backward compatibility with the SMF 2.0.X branch.

**Comment by MissAllSunday** [comment] 2014-09-29 01:23
I had updated a few BBC mods to 2.1 and I cannot reproduce this issue on any of them.

I debugged the issue right to your action=admin;area=PersonalizedBBC;  page, the string was clean at the moment it was passed by both load_file and call_helper during install so the problem is not on installing but on the very first time your page is been showed to the admin.

Something, somewhere in your code is creating this one time logic flaw by calling PersonalizedBBC_codes before PersonalizedBBC_codes.php gets loaded, don't know your codebase too well, but I assume a simple require_once to load the file on a very early level will suffice.

**Comment by Underdog-01** [comment] 2014-09-29 01:55
The file containing the function is loaded with a hook.
this one that was created in the installer:.
add_integration_function('integrate_pre_include', '$sourcedir/PersonalizedBBC.php');

The purpose of that hook should be to load the file. Shouldn't the hook to load files be executed prior to any other hooks? Files are loaded to make use of their functions contained within which is what other hooks more or less do (use functions contained within the preloaded files).
This error only shows once during the install process and does not occur after the mod is installed.

**Comment by MissAllSunday** [comment] 2014-09-29 13:28
yeah, that hook shouldn't really be used on 2.1 anymore since its always better to load your files when you're gonna needed than loading it on every single action, thats why add_integration_hook was changed in the first place.

On 2.0 there wasn't any other way to load your file except the admin one and some other obscure tricks so you were pretty much stuck with pre_include, on 2.1, however, you don't really need to use that hook  anymore except for counted and really exceptional reasons.

Anyway, can't reproduce this with any other mod, even with some plain old 2.0 bbc mods.

**Comment by Underdog-01** [comment] 2014-09-29 22:37
Not even with other BBCode mods that used hooks for 2.0.X ??
I will have to run some tests with other mods.
Atm I do not see any issue with the way I initially had it configured although I fixed it for the SMF 2.1 branch as I showed in my last github link with my v1.7 official release. That being said it isn't really important I suppose unless I can reproduce the issue with another mod or two (from other devs).
I will keep you posted in this report if I find the issue occurs for other example mods.

**Comment by Underdog-01** [comment] 2014-09-29 23:09
Here are other example mods I found that are showing the same error:
http://custom.simplemachines.org/mods/index.php?mod=3872
http://custom.simplemachines.org/mods/index.php?mod=3387
http://custom.simplemachines.org/mods/index.php?mod=3431
http://custom.simplemachines.org/mods/index.php?mod=3452
http://custom.simplemachines.org/mods/index.php?mod=3398
http://custom.simplemachines.org/mods/index.php?mod=2247

Imo SMF 2,1 is not executing the require file command for the 'integrate_pre_include' hooks prior to executing the integrate_bbc_codes type hooks (to be SMF 2.0.X backward compatible) and/or my initial hypothesis at the onset of this report.

.. The examples above are all mods that use the integrate_bbc_codes hook although this may occur with other hook types that I have yet to test. I will look for other mods that are not BBCode type and are showing a similar error if need be.

Perhaps reopening this report would be prudent? I believe input from other devs would be helpful whereas they may be unaware due to it being closed.

**Comment by MissAllSunday** [comment] 2014-09-30 13:35
Your initial hipoteshis blamed me for a change I already fixed, just need to also add it to remove_integration too. The new issue now has nothing to do with your original report, is a completely different issue since whats causing it its not what you suggested on your initial report, thus, it needs an new report.

Yes, debugging shows the file included with pre_include is not been loaded.

Debuggin also shows theres a pretty early call to parse_bbc() on Subs:: line 2892  which according to debug_backtrace() its called very very earlier in the process, inside setupThemeContext  but still, reloadSettings() is called even earlier than loadTheme()  so any files inside $modSettings['integrate_pre_include'] should be included.

All of that leads me to believe there is some sort of cache issue going on, BTW this happens on 2.0 too, the only reason we know about this is because 2.1 adds an error log while 2.0 just doesn't do anything.

This shouldn't be an issue if mod authors uses the new feature to load their own files when needed instead of abusing pre_include

**Comment by Underdog-01** [comment] 2014-09-30 20:48
Imo you have taken the initial report out of context. I was not blaming you but rather pointing out what I thought may have been a recent change in an area of code that could cause the issue as it may have needed some fine tuning. ie. I did not create a reversal pull request but rather just a report with a reference to code changes in the area I saw the error coming from. This is mostly because the error did not occur for me prior to that time frame.   

  Imo there is no abuse of the pre_include hook here. As its name suggests, the files it calls should be pre-included prior to pretty much any other process that may load a function including those that exist for the mod install routine. This is the purpose of that hook and it should work as such. As I stated prior, the error only occurs for me during the install process and not during regular forum use.

  Why would I open another report and not just request that this report be reopened? The issue still exists especially if backward compatibility is sought by the development team. My debugging shows the error occurs from the code recently introduced in the referenced area.

**Comment by MissAllSunday** [comment] 2014-09-30 22:19
Point, is, the issue has nothing to do with you original report, its a different issue that has to be treated separately, thus, it needs a new report.

I already addressed the backward compatibility by changing the params on both add and remove integration_function, that part is already solved and has nothing to do with the issue regarding integrate_bbc_codes

The reason why you didn't saw any issue before is pretty simple and I already told you, on 2.0 there is no indication that a hook failed, it just don't do anything.

The only reason this occur in 2.1 after the changes I made is because, well, the changes I made!!!  I added a log_error to detect when a function/method wasn't callable.

I really, really don't know how to say this more clear, yes, the "problem" exists because of the changes I introduced BUT thats precisely WHY I introduced those changes! the code is doing what its suppose to be, which is telling you if your function/method failed to be callable.

Now, there is an issue with integrate_bbc_codes, for some reason pre_include its been skipped, this is the MAIN issue and this is the one who needs to be addressed.

As for pre_include abuse, I already told you that in 2.0 you pretty much are stuck with it, in 2.1 you don't, in 2.1 you have specific features to deal with loading your files, this specific features were specifically designed to load your file only when needed.

pre_include just wasn't designed for that, its main purpose was to help integrating SMF with other scripts, not to be used by mods.

Again, pre_include shouldn't be used, specially since it will load your file EVERYWHERE, you don't need your file everywhere, doesn't make any sense, it makes more sense to load your ONLY when you really needed.

**Comment by Underdog-01** [comment] 2014-09-30 23:52
Thanks for the very clear explanation.
I agree with you that the require file need not be used on every page load and should only be required when functions contained within are to be used.  

So even though the other various hooks should now be using file|function, the examples show that the integrate_pre_include is not being triggered prior to the onset of the integrate_bbc_codes hook within the mod installation routine. I will either file another report as you suggest with those specifics else post a pull request with a possible fix.

Regards.

**Comment by Underdog-01** [comment] 2014-10-01 01:04
reloading the settings table during the install process executes the pre_include array and stops the errors.
ref. https://github.com/SimpleMachines/SMF2.1/pull/2396

**Comment by MissAllSunday** [comment] 2014-10-01 01:07
Yes, as I was suspecting, it had to do with $modSettings['pre_include'] not been properly "reloaded" before using it.

Thanks for the patch, I will test it and merge it when I have some time.

**Comment by Underdog-01** [comment] 2014-10-01 02:31
No problem. 

Regards.
