### ISSUE TITLE
Some form fields reset after saving if they contain umlauts (special characters)

### ISSUE THREAD

**Issue by Konzertheld** [SimpleMachines/SMF#407] opened 2013-06-08 00:22 UTC
1. Install SMF 2.1 @ bb72cffb893b9bd5697113aca3aed880ee0ae0f7 (I found it in 2.0.4 stable and reproduced on the Git master as of now) without UTF-8.
2. Create a new board that contains an umlaut, like "Äpfel".
3. Click modify.

The board settings open and the board's name is not loaded. You have to enter it again to save your changes because the save button is deactivated until you entered a board name. The value is saved and used correctly (the board name displays on the forum).

The same problem applies to several fields. I also discovered it in member group descriptions and I am not sure if those are the only two.

Apache 2.2.22
PHP Version 5.4.14-1~quantal+1
MySQL 5.5.31-0ubuntu0.13.04.1

**Comment by eurich** [comment] 2013-06-08 19:06
I'd recommend to use UTF-8 for multilingual forums. German umlauts [äöüß] are well displayed as long as you use the right language files (german).
non-UTF8 English language files use $txt['lang_character_set'] = 'ISO-8859-1';
non-UTF8 German language files use $txt['lang_character_set'] = 'ISO-8859-15';

äöü and ß don't exist in ISO-8859-1, but that's not a bug, it's simply the wrong charset you used.

**Comment by Konzertheld** [comment] 2013-06-10 01:25
Well, the forum is not multilanguage. It's German only. So I don't see how that is related. I can enter values with umlauts and I can display them (boards with umlauts in their name show up correctly on the front page etc). Just in the edit forms those values cause problems.

Posting with umlaut usage also works fine. I can write posts with umlauts, display and edit them.

**Comment by eurich** [comment] 2013-06-10 03:21
most forms (e.g. the posting text or subject) are "protected" via php functions htmlspecialchars() and htmlentities(), german characters will be replaced with their html entity equivalent. Some areas inside the admin interface do not use these php functions in order to allow HTML text..
Example `<span style="color:yellow;"> My forum description</span>`

You can still use umlauts there, but you'd need to:
1) convert the forum to UTF-8 (umlauts are know characters then) or 
2) switch the code page from 8859-1 to 8859-15 (same here) or
3) use html entities `&uuml; &auml ...`
http://unicode.e-workers.de/entities.php

**Comment by Konzertheld** [comment] 2013-06-10 03:44
Thanks for the explanation. So it is intended to allow HTML for board titles/descriptions and user groups (descriptions)? Especially for the latter I don't see a usecase (I don't even see where the group descriptions are used).

Anyway, I changed the codepage to 8859-15 and it didn't help. And how would a use of htmlentities or htmlspecialchars apply to the form where the value is entered? Those functions are usually used for output, to prevent people from injecting unwanted stuff.

**Comment by eurich** [comment] 2013-06-10 06:06
Don't worry about security, SMF's db layer is still taking care of these.. also: that's all inside the admin area, so you'd need an hijacked admin session in order to do these "bad things" ..

> Anyway, I changed the codepage to 8859-15 and it didn't help

Yep, your're right, my mistake. Haven't checked these parts of code for some time.. It's AFAIK still "by desgin" and intended.. . I've seen lots of boards with HTML (images added, colored text etc) in board titles, descripttions and category titles. 

I've use entities in the past, IIRC

**Comment by Konzertheld** [comment] 2013-06-10 07:59
Hm, I still don't get how those values completely disappear. They are obviously correct in the database so they should display (at least wrong or incomplete) in the form.

Anyway, could you point me to where the "edit board" form is created? I don't have a clue of the SMF file structure, but I'd like to surround the output with htmlentities() as I don't need HTML in those fields.

**Comment by eurich** [comment] 2013-06-10 08:14
Should be sources\ManageBoards.php

**Comment by Arantor** [comment] 2013-09-27 15:32
Well, interestingly enough SMF does actually push UTF-8 by default on installs now.

I'd personally be more interested if this could be repeated on a UTF-8 install (UTF-8 is recommended even in non multi-lingual installations)

**Comment by Arantor** [comment] 2013-10-08 13:05
I should add, I can't reproduce this with UTF-8 on current 2.1. Actually tempted to close this, to be honest, it does strike more of a configuration issue than anything else.

**Comment by Arantor** [comment] 2014-02-02 20:45
Still cannot reproduce, closing.

**Closed as completed by Arantor** 2014-02-02 20:45 UTC
