### ISSUE TITLE
Deprecating compatibility functions

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4096] opened 2017-06-04 17:23 UTC
Hopping through the codebase, I found the following things...

- [ ] un_htmlspecialchars - PHP 5.1 and above includes htmlspecialchars_decode. I'm not sure how this function differs from it (it says it removes things but it just replaces things from reading the code).
- [ ] html_to_bbc, bbc_to_html, legalise_bbc (and sort_array_length) - I know the notes say that they shouldn't be removed due to mod compatibility, however mods have to be updated for 2.1 anyway so authors could move to a different implementation.
- [ ] theme_postbox - Used in SMF 1.1. Need I say more :x 
- [ ] smf_setcookie has a note that it can be removed since SMF requiers PHP >= 5.3.8 now.

**Comment by live627** [comment] 2017-06-07 03:59
Huh, I always  thought  un_htmlspecialchars() and htmlspecialchars_decode() did the same thing.

**Comment by Sesquipedalian** [comment] 2017-06-08 08:06
> un_htmlspecialchars - PHP 5.1 and above includes htmlspecialchars_decode. I'm not sure how this function differs from it (it says it removes things but it just replaces things from reading the code).

Yeah, they look the same to me. We should probably keep it around for old mods, but we could replace the current content of the function with a simple `return htmlspecialchars_decode($string)`.

> html_to_bbc, bbc_to_html, legalise_bbc (and sort_array_length) - I know the notes say that they shouldn't be removed due to mod compatibility, however mods have to be updated for 2.1 anyway so authors could move to a different implementation.

In theory the mods should be updated, sure, but I doubt they all will. It doesn't hurt us to keep these functions around for now.

> theme_postbox - Used in SMF 1.1. Need I say more :x

No, you needn't. Death to it!

> smf_setcookie has a note that it can be removed since SMF requiers PHP >= 5.3.8 now.

Ditto for this one.

**Comment by XinYenFon** [comment] 2017-06-08 08:17
@Sesquipedalian backward compat broken for a long time so anything unnecessary should better be dead in sense of consistency.

But the thing is, anything removed from SMF (Source) should be noted in wiki so mod authors can update their mods far more easily.

**Comment by NanoSector** [comment] 2017-06-08 15:51
We need a wiki page with all the developer changes anyway, like hooks added/changed and stuff.

**Comment by colinschoen** [comment] 2017-06-08 17:33
i'll make a post in the doc team boards to see if they can get a page template sorted for us and we can start updating it.

**Comment by frandominguezl** [comment] 2017-06-08 18:00
We've got this; http://wiki.simplemachines.org/smf/Differences_between_SMF_2.1_and_SMF_2.0

What else do you need?

**Comment by colinschoen** [comment] 2017-06-08 18:01
Specifically a page for developers and mod authors that shows the changes in functions and available hooks.

**Comment by Arantor** [comment] 2017-08-24 11:56
The behaviour is more evident in a mixed encoding environment but it is not a 1:1 change because the behaviours differ when considering the behaviour of nbsp decoding. Using the internal function yields a real nbsp character (U+00A0) while this function yields U+0020 which in some of the places it is used, could be significant, e.g. with posts and the preservation of spaces that is carried out there.

**Comment by NanoSector** [comment] 2017-08-24 16:38
@Arantor I suppose you're talking about the un_htmlspecialchars function?

**Comment by Arantor** [comment] 2017-08-24 20:41
Yup, and changing it out is not consequence free.

**Comment by Sesquipedalian** [comment] 2017-08-25 01:16
> Using the internal function yields a real nbsp character (U+00A0) while this function yields U+0020

Good to know. Thanks, @Arantor.

**Comment by NanoSector** [comment] 2017-08-25 22:44
smf_setcookie actually has some hook stuff going on, so we might not want to remove this. It also calls setcookie() natively.

**Comment by NanoSector** [comment] 2017-08-25 22:44
Also, do we agree on removing the bbc and html functions now?

**Comment by Arantor** [comment] 2017-08-26 17:58
The problem is that 2.1 really does pitch itself as trying to be compatible with 2.0 mods, to the point of offering to help install them. For a modest incremental update as originally envisioned, this would have worked - templates didn't even need major overhauls for the most part.

But I think yes, it's probably at the point where they should go now. theme_postbox definitely needs to die already.

**Comment by Arantor** [comment] 2017-08-27 11:55
Oh, and html_to_bbc is in use in the manage boards area so you can't just remove it.

**Comment by MissAllSunday** [comment] 2017-09-05 00:01
Yes, html_to_bbc is still used to allow basic BBC usage inside board description, I believe categories too.

**Comment by jdarwood007** [comment] 2018-09-06 00:23
Looking at the code and all the usage of un_htmlspecialchars, I would say at this point in 2.1 life cycle it could cause a BC issue if we change it.  Too much testing would need to be done to ensure that we didn't break something with this change.


Thoughts?

**Comment by Sesquipedalian** [comment] 2018-09-26 07:53
I've just done some tests on un_htmlspecialchars() vs. htmlspecialchars_decode(). Arantor was mistaken when he said,

> Using the internal function yields a real nbsp character (U+00A0) while this function yields U+0020

In fact htmlspecialchars_decode() does nothing to `&nbsp;`. However, the point remains that un_htmlspecialchars() is not an exact equivalent for htmlspecialchars_decode(), since un_htmlspecialchars() replaces `&nbsp;` with a simple space character, so we cannot remove it without potentially breaking a whole bunch of stuff.

**Comment by jdarwood007** [comment] 2018-09-26 23:36
Ok, With the PR submitted I suggest we close this and move it to future.

**Comment by Sesquipedalian** [comment] 2018-09-27 05:34
> Ok, With the PR submitted I suggest we close this and move it to future.

It's just awaiting an approving review so I can merge it.

**Comment by albertlast** [comment] 2018-09-28 14:34
Like i said,
in my eyes the depracted function should be mark as depracted,
eaven smf them self use them.

**Comment by Sesquipedalian** [comment] 2018-09-28 17:50
If SMF itself is still using them, then they are by definition not deprecated yet.

**Closed as completed** 2018-10-03 18:26 UTC
Labels: Enhancement
