### ISSUE TITLE
Global moderator can not see the moderation button

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#4741] opened 2018-04-30 18:52 UTC
Hi,

Global moderator can not see the moderation button.  Only see the user actions button

Admin admin sees the moderation button. no problem

![mod](https://user-images.githubusercontent.com/5096676/39444538-d0824278-4cc0-11e8-84a9-9825e58a3a13.png)
![admin](https://user-images.githubusercontent.com/5096676/39444540-d1b0c8b8-4cc0-11e8-8994-ab5e357b90c8.png)

**Comment by albertlast** [comment] 2018-05-01 04:20
@Sesquipedalian @colinschoen i looked in the code and notice that global mod didn't exists.
What i mean with that,
i see code for handling admin and see code for moderator,
but i see no code/logic to define a global mod.

From my point of view there didn't exists any flag(on GUI side) to define a group as global mod and
there is no point where we save this information.

Short notice the button is not displayed,
because "global mods" got a false in
https://github.com/SimpleMachines/SMF2.1/blob/a95d6c17719f0f7b2ce259a96f752ce9550dcab1/Themes/default/Display.template.php#L308

is_mod is set here
https://github.com/SimpleMachines/SMF2.1/blob/a95d6c17719f0f7b2ce259a96f752ce9550dcab1/Sources/Load.php#L979

**Comment by albertlast** [comment] 2018-05-01 05:16
Okay look like i take the wrong route,
as fare i know the right should be came from can_moderate_forum is setted false because global mod didn't have moderate_forum
in the permission management you find the point: general permissions -> "Moderate forum members" set this true and the button is there.
But again question at the crew @colinschoen @Sesquipedalian shouldn't had a glob mod by default this true?

btw. the button only exists in mobile view (gvv miss this to mention in my eyes)

**Comment by Sesquipedalian** [comment] 2018-05-01 15:29
Yes, `if ($context['can_moderate_forum'] || $context['user']['is_mod'])` was all wrong. First of all, those aren't the correct permissions to check. Second, that kind of check doesn't belong in the template files, but rather in the source files. All the template file should do is check `if (!empty($context['mod_buttons']))`

**Comment by albertlast** [comment] 2018-05-01 15:31
But why got global mod not moderate_forum?

**Comment by Sesquipedalian** [comment] 2018-05-01 19:20
The name of that permission is a bit misleading. It refers to permission to configure certain things about how the forum functions, not to permission to moderate posts throughout the forum.

**Comment by gevv** [comment] 2018-05-02 09:48
Hi,

@Sesquipedalian  Change code, clear cache  Themes/default/Display.template.php   the problem continues

**Comment by illori** [comment] 2018-05-04 10:28
the issue is related to this line https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/Display.template.php#L241

if it is changed to `', (!empty($context['mod_buttons'])) ? '<a class="button mobile_mod">' . $txt['mobile_moderation'] . '</a>' : '', '` this issue seems resolved. @gevv can you test it?

then we need to apply the same fix to line 263.

**Comment by gevv** [comment] 2018-05-04 13:17
thanks everyone


@illori change code moderation button looks ok.
// Mobile action - moderation buttons (top)
// Mobile action - moderation buttons (bottom)

**Comment by Sesquipedalian** [comment] 2018-05-04 18:50
#4748

**Comment by illori** [comment] 2018-05-04 19:10
Thanks

**Comment by illori** [comment] 2018-05-05 10:33
since the PR has been merged i am going ahead and closing this issue.

**Closed as completed by illori** 2018-05-05 10:33 UTC
Labels: Moderation, Permissions, Membergroups
