### ISSUE TITLE
Problem with Installation

### ISSUE THREAD

**Issue by SoLoGHoST** [SimpleMachines/SMF#872] opened 2013-11-13 03:15 UTC
Ok, so, noticing some problems right off the bat here with the install.  1 Whatever is supposed to be up top on install.php doesn't show (I believe it relates to the div with class set to "news normaltext", but not entirely sure).  2, when going to step 2, and step 3 of install (after putting in proper information), I get white page after hitting Continue button, and after getting to Step 3, I'm unable to see step 3's page and not able to finish installation.  Again, this could be something wrong on my end of things, but this is my first experience so far with SMF 2.1 and just thought I'd share this.  Not able to go to install.php since it tells me that SMF is already installed, and trying to go to my actual index.php page on that site produces an empty white page.  So, the last thing I did was put in my database information and click on next and got an empty white page and am unable to finish installation because of white page and empty white page on actual index.php.  Going to install.php again gives me SMF is already installed and if I continue than I will need to put in the same information again for database.

Used Opera Browser during installation, if it matters.  And attempting to install on a sub-domain.
![capture](https://f.cloud.github.com/assets/569354/1528593/0f9994d8-4c13-11e3-8150-e366da6902ca.PNG)

**Comment by illori** [comment] 2013-11-13 10:42
![Alt text](http://imageshack.us/a/img837/4443/w5nc.png)

the installer looks fine to me.

**Comment by AaronVanGeffen** [comment] 2013-11-13 13:51
SoLoGHoST, can you check whether there are any PHP error messages in the HTML source?

**Comment by illori** [comment] 2013-11-14 21:25
i just ran a full install without any issues with the installer [layout wise]

**Comment by Arantor** [comment] 2013-12-19 22:20
Due to the lack of information and inability to reproduce, I'm going to close this.

**Closed as completed by Arantor** 2013-12-19 22:20 UTC
