### ISSUE TITLE
Something related to json decode issues

### ISSUE THREAD

**Issue by bperry921** [SimpleMachines/SMF#3520] opened 2016-07-09 04:07 UTC
I am getting an invalid arguement error msg for line 2095 for the snippet of code displayed here from my copy of the Subs_editor.php file...

![image](https://cloud.githubusercontent.com/assets/4441576/16705982/0409ebac-4569-11e6-938c-ee85c285e239.png)

And the url that triggers this most is here... http://www.rjventure.com/index.php/topic,222396.0/prev_next,next.html

**Comment by MissAllSunday** [comment] 2016-07-10 17:05
Whats the value of $row['answers'] before and after its been passed to smf_json_decode() ?

**Comment by bperry921** [comment] 2016-07-10 18:39
Ok, I know what is causing the error now but its not in this code here, its throwing the error because every upgrade I've done over the last several months changes the values in the answer field of qanda database table to false for some strange reason, after i fix the database manually the error goes away

**Comment by bperry921** [comment] 2016-07-29 18:56
Updating also changes the cost field of my subscriptions table settings to false as well, annoying...

**Comment by Oldiesmann** [comment] 2016-08-12 16:59
What values were in the cost field prior to running the upgrade? That will help us determine where the issue is.

**Comment by live627** [comment] 2016-08-12 22:35
inb4 invalid utf-8....

**Comment by MissAllSunday** [comment] 2016-09-01 15:59
@bperry921  Are you still able to reproduce this error?

**Comment by bperry921** [comment] 2016-09-01 19:38
As of my last update to the latest release which was about 3 weeks ago, yes. Even when I corrected the database to save the fields in the correct format for that release, the next upgrade did the same thing, it leaves the question section alone but the answers in the qanda table get changed to the text string false.

**Comment by MissAllSunday** [comment] 2016-09-01 19:51
Can you please test it with a full upgrade,  that is,  with an upgrade from 2.0 to the latest 2.1 branch

**Comment by bperry921** [comment] 2016-09-01 19:55
I will do an upgrade, but it won't be from 2.0 to latest 2.1, yall can do that, I'm too busy.

**Comment by bperry921** [comment] 2016-09-01 20:09
same result

**Comment by MissAllSunday** [comment] 2016-09-01 21:39
We need to make sure this issue happens on a full upgrade from a 2.0  
database.   Partial upgrades an issues with upgrading alpha to beta  
releases won't be supported.

**Comment by MissAllSunday** [comment] 2016-11-18 17:30
Partial upgrade from alpha/beta to beta won't be supported.

**Closed as completed by MissAllSunday** 2016-11-18 17:30 UTC
