### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mime_type' of undefined

### ISSUE THREAD

**Issue by kungfooman** [SimpleMachines/SMF#5757] opened 2019-08-11 13:41 UTC
#### Description

![image](https://user-images.githubusercontent.com/5236548/62834537-56b9d100-bc4e-11e9-9d8d-39cca7d27149.png)

### Steps to reproduce
1. Change settings to allow mp4 attachments
2. Upload some mp4 file

**Comment by frandominguezl** [comment] 2019-08-11 18:13
Where are you exactly getting this error? I tried to replicate it but I couldn't.

Can you provide more details? Files size, for example...

**Comment by smfbigguy** [comment] 2019-08-11 20:36
I have added mp4's to my install and it works fine with no errors. of course my install might be a month old or so, so something could have happened between then and now.

**Comment by frandominguezl** [comment] 2019-08-11 20:56
Mine is not that old. @kungfooman You're using latest build from GitHub or RC2?

**Comment by sbulen** [comment] 2019-08-11 21:34
I would also attempt mp4s from other sources.  

Mp4s are just containers, holding many types of contents.   IIRC, no "magic #",  so we're at the mercy of whoever encoded it to put the mime type in there.

**Comment by sbulen** [comment] 2019-08-12 00:23
I cannot duplicate this.  Had a different issue, though, which I will log separately.

**Comment by kungfooman** [comment] 2019-08-12 07:04
I tested HEAD (just cloned) and RC2, both fail with same error (beautified):

![image](https://user-images.githubusercontent.com/5236548/62849380-bad8a580-bcdf-11e9-8622-9f82941b5ad3.png)

The uploaded file size is 46MB, smaller files work! So this is probably a file size issue. But I don't know why, in my `php.ini` I allow `upload_max_filesize = 100M` and in SMF settings I allow unlimited file size (=0).

@frandominguez03 I get the error after dragging a .mp4 file on the "attachment drop zone", it looks like this after the error: 

![image](https://user-images.githubusercontent.com/5236548/62849724-05a6ed00-bce1-11e9-99c2-16d574f84643.png)

**Comment by frandominguezl** [comment] 2019-08-12 15:51
Thanks for the details. I could kind of reproduce it with a 30MB file:
![image](https://user-images.githubusercontent.com/10365222/62878673-d49eda80-bd29-11e9-95d1-15f544381ede.png)

**Comment by sbulen** [comment] 2019-08-15 04:13
Could you confirm what your post_max_size is in your php.ini file?  The default for those values, IIRC, is 30MB, and that's ~what we're seeing.  

I can reproduce this if I drop my post_max_size down to ~30MB.  

So...  I wonder if we should prevent folks from setting attachment settings larger than php.ini allows?

The reason I couldn't reproduce this before is my post_max_size was set to 500MB...

(EDIT:  Also look at upload_max_filesize...  I tend to set both to the same value...)

**Comment by kungfooman** [comment] 2019-08-15 07:21
Thanks for testing @sbulen 

Now I set `post_max_size = 500M` and `upload_max_filesize = 500M`

Uploading the 46mb file causes this error now:

![image](https://user-images.githubusercontent.com/5236548/63079117-d80aaf80-bf3d-11e9-8c8b-18bcdadf1420.png)

There is enough space left on disc... actually tested it with: `fallocate -l 100mb test.mp4`

**Comment by sbulen** [comment] 2019-08-15 12:37
That's a normal SMF message letting you know you exceeded your folder settings.  Look closely at all of your attachment settings.

Here, it may be that the defaults are too low?

**Comment by sbulen** [comment] 2019-08-15 12:45
Sorry closed in error...

**Comment by frandominguezl** [comment] 2019-08-20 09:23
> Could you confirm what your post_max_size is in your php.ini file? The default for those values, IIRC, is 30MB, and that's ~what we're seeing.
> 
> I can reproduce this if I drop my post_max_size down to ~30MB.
> 
> So... I wonder if we should prevent folks from setting attachment settings larger than php.ini allows?
> 
> The reason I couldn't reproduce this before is my post_max_size was set to 500MB...
> 
> (EDIT: Also look at upload_max_filesize... I tend to set both to the same value...)

Sorry for late answer;

post_max_size=8M
upload_max_filesize=2M

**Comment by sbulen** [comment] 2019-08-20 17:29
That confirms the above.  The problem here is that your php environments don't allow file xfers that large.   You can change all the settings you like in SMF, but if the platform itself stops you, you're stuck...  

I think the best solution here is to query the php setting, & not allow the user settings to exceed that.

**Closed as completed** 2019-09-01 15:42 UTC
Labels: Attachments
