### ISSUE TITLE
Installer: same MySQL version detection as Upgrader

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#7078] opened 2021-09-14 03:44 UTC
#### Description
The installer uses the same `mysqli_get_server_info()` MySQL version detection as the upgrader which causes issues in detecting the proper version number for MariaDB, so just adding this issue so we can fix the installer at the same time as the upgrader.

### Environment (complete as necessary)
- Version/Git revision: Github latest

### Additional information/references
Refer #7070 for previous discussion on mysqli_get_server_info() and MariaDB.

**Comment by illori** [comment] 2021-09-15 23:38
duplicate of #7070

**Closed as completed** 2021-09-17 00:40 UTC
Labels: Installer
