### ISSUE TITLE
Mysql Syntax error

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5295] opened 2018-12-28 15:08 UTC
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO smf_calendar_holidays (title, event_date) VALUES ('New Year''s', '1' at line 6`

That's the message I get when upgrade from previous dev-build.

**Comment by VBGAMER45** [comment] 2018-12-28 15:12
Looks issue with ' in new years

**Comment by ghost** [comment] 2018-12-28 15:33
Seems like this one : https://github.com/SimpleMachines/SMF2.1/commit/1f3e76f67fa0db18ffe91a1f671f396287fd209f

**Comment by albertlast** [comment] 2018-12-28 15:54
In the template of creating issue we ask many things,
it would helpfull when you insert them.

Because i'm not able to reproduce this issue.

**Comment by ghost** [comment] 2018-12-28 15:58
It could only be those two files, things upgraded fine previously.

**Comment by albertlast** [comment] 2018-12-28 16:03
let me ask directly:
What is you php and mysql/mariadb version?

**Comment by ghost** [comment] 2018-12-28 16:13
10.1.30-MariaDB-1~xenial

**Comment by albertlast** [comment] 2018-12-28 16:24
plase do a  ``select version();``

**Comment by ghost** [comment] 2018-12-28 16:25
(edited)

**Comment by albertlast** [comment] 2018-12-28 16:30
Please try this changes: https://github.com/SimpleMachines/SMF2.1/pull/5296

**Comment by ghost** [comment] 2018-12-28 16:37
Yup, le works.

**Comment by albertlast** [comment] 2018-12-28 16:39
as typical,
mysql doesn't show the place where the error happen,
it stop random somewhere else.

**Comment by ghost** [comment] 2018-12-28 16:41
Yes, I guess Issue closed.

**Comment by albertlast** [comment] 2018-12-28 16:42
No,
please not close,
the issue get closed by the pr when merged.

**Comment by ghost** [comment] 2018-12-28 19:55
okay

**Closed as completed** 2018-12-28 20:38 UTC
Labels: Upgrader, Database
