### ISSUE TITLE
Token verification failed. Please go back and try again. 

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5775] opened 2019-08-21 21:25 UTC
#### Description
Token verification failed. Please go back and try again. 

### Steps to reproduce
1. edit yahoo custom profile field, set to active no
2. save page
3. Token verification failed. Please go back and try again. 

seems many other admin actions are also failing with the same error... any ideas to troubleshoot this? would it help to provide my php.ini from my wamp install?

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version: 7.1.16

### Additional information/references

**Comment by illori** [comment] 2019-08-22 10:24
my email settings were not working... changed them to work and now this issue has gone away.

**Comment by sbulen** [comment] 2019-08-22 11:15
May have been the restart that fixed it - not necessarily the setting change.

I would close issues you can no longer reproduce.

**Comment by MissAllSunday** [comment] 2019-08-22 14:23
Yep, let's close this but there's still an issue with tokens being dynamically created and attempted to be verified on pages that didn't generate them, still haven't found a fix for that or even get to know the root cause of it

If you can reproduce the issue again please use the other issue related to tokens to keep things organized.

**Closed as completed by MissAllSunday** 2019-08-22 14:23 UTC
