### ISSUE TITLE
Empty space in quote field and too big under quote

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2180] opened 2014-08-12 18:18 UTC
It's great that what I reported was fixed, but now I want for you to describe the view on it, look:

When some post is quote, set the text with one  line spacing from quote code, in editor it’s looks in this way: 

![smf21a](https://cloud.githubusercontent.com/assets/8003629/3895006/38ede574-224a-11e4-820a-bdd8de604fe5.png)

And everything is all right, but unfortunately after adding the post, in topic it’s looks in this way: 

![smf21b](https://cloud.githubusercontent.com/assets/8003629/3895012/4fea795e-224a-11e4-9fc9-a83c80e3166b.png)

Text "SMF 2.1" above itself has a too big empty field, look how it not nicely looking, such a empty space, now look on quote above the text "Simple Machines Forum"  there is also empty space. And it shouldn’t be in this way. 

Now I moved the written text "SMF 2.1 TEST2" up to the code of the quote without the space in the editor and a little bit this line spacing in post is smaller. 

![smf21c](https://cloud.githubusercontent.com/assets/8003629/3895025/79139054-224a-11e4-89ad-a78552fc94f4.png)

![smf21d](https://cloud.githubusercontent.com/assets/8003629/3895046/96b2ab40-224a-11e4-8c1b-5d6bd2f99cdc.png)

But I don't know as you, but if I’m writing the post quoting somebody, in editor of writing the message I don’t starting writing the text right under the quote code:

[quote author=admin link=msg=14 date=1407864066]
Simple Machines Forum
[/quote]
Test...

Just:

[quote author=admin link=msg=14 date=1407864066]
Simple Machines Forum
[/quote]

Test...

So look at screens, the quoted quotation above itself has empty field, it shouldn’t be and the written text above itself has too big empty field, it should be reduced.

![smf21e](https://cloud.githubusercontent.com/assets/8003629/3895122/0f6d7240-224b-11e4-99e4-d05a6e0bb3a5.png)

![smf21f](https://cloud.githubusercontent.com/assets/8003629/3895124/12b55972-224b-11e4-8475-7386ea53baf9.png)

Look how that is in SMF 2.0

![smf2a](https://cloud.githubusercontent.com/assets/8003629/3895185/ae20f150-224b-11e4-9f2b-7666d11f62ae.png)

![smf2b](https://cloud.githubusercontent.com/assets/8003629/3895188/b08070c4-224b-11e4-8c0d-06e79dac89df.png)

I just want to share my opinion on this topic, if you acknowledge that everything is ok with it, it is your, I only described my view.

**Comment by XinYenFon** [comment] 2014-08-12 18:58
Already reported here #2169

**Comment by BitFros7y** [comment] 2014-08-13 11:49
Well for me its normal as most sofwares supporting quoting have that "bug"...
Simple and good way to fix it would be to check on "user creating new post" for any new lines right after quotes ] (Both starting and ending quote)

**Comment by XinYenFon** [comment] 2014-08-29 15:21
After some more investigation, the extra line (inserted by SCEditor) is required for toggle, otherwise it bugs quote/code tags and keeps things inside quote/code. So this is not a bug, its actually bug in SMF 2.0 afaik (didn't really tested), you can find more reference in the sceditor.js files.

About other one, that's a bug and reported (as told before) #2169 - This issue can be closed now.

**Comment by live627** [comment] 2014-09-08 01:21
Should be fixed with 92da1395d38b7b24e7a1e4311da373938fba0d38

**Closed as completed by live627** 2014-09-08 01:21 UTC
Labels: Parsers (BBC/Markdown), Editor
