### ISSUE TITLE
Is View Mail queue working?

### ISSUE THREAD

**Issue by mtomas7** [SimpleMachines/SMF#4986] opened 2018-09-01 19:48 UTC
Hi, I remember that some time ago in RC1 View Mail queue was working, but it seems that after I updated several times to GitHub daily, it stopped.

Could anyone verify that when you post new topic, then go to Admin > Maintenance > Mail > view queue

Do you see the queue?

Sometimes I need to process it immediately, that's why it is important to me.

Thank you!

**Comment by gevv** [comment] 2018-09-21 08:18
hi,
after the latest updates mail and alerts not working

**Comment by Sesquipedalian** [comment] 2018-10-10 22:23
I haven't yet had time to see if I can reproduce the reported issue, but I've set the milestone for this to RC2 so that we remember to either close it or fix it by then.

**Comment by smfbigguy** [comment] 2018-10-11 00:07
Alerts and mail queue work on my site. I updated Sept 29th. So if they are broke it was something after that date. I hope this helps a bit at least.

**Comment by smfbigguy** [comment] 2018-10-13 03:16
I had to play around with cron jobs in cpanel to get things to work right. I have it set to every minute. I know these aren't the most technical reports but I thought I would add this for a bit more info.

**Comment by SugarD-x** [comment] 2018-11-06 23:51
I've had issues with failed messages that weren't sent out to email addresses specifically through the newsletter option get stuck in the queue without stating such, but other than that my mail queue has been working fine since I figured out how to get mail working properly in SMF 2.1 Beta 3. I'm now on the latest repository files and I'm still not having any issues loading it. Maybe it is an environment issue? I didn't have to set anything up for it to work on my end.

**Comment by sbulen** [comment] 2019-06-10 09:41
I cannot reproduce this using the current github version.  I think it got fixed somewhere along the way.

**Comment by MissAllSunday** [comment] 2019-08-21 16:08
@mtomas7 @gevv @SugarD-x  Can you verify that this issue has indeed been solve?

**Comment by SugarD-x** [comment] 2019-08-22 05:58
Seems to be working fine on my end now, as far as I can tell.

**Comment by MissAllSunday** [comment] 2019-08-22 14:14
Cool, just one more verification just to be sure and we can close this.

**Comment by MissAllSunday** [comment] 2019-09-23 15:27
@mtomas7 @gevv I will close this. Feel free to open a new one if the issue hasn't been solved on the current build

**Closed as completed by MissAllSunday** 2019-09-23 15:27 UTC
Labels: Mail
