### ISSUE TITLE
Undefined array key "href" whe using ssi_recenttopics on a page while posting with an attachment

### ISSUE THREAD

**Issue by Bopske** [SimpleMachines/SMF#7729] opened 2023-04-09 13:22 UTC
#### Description
As reported here: https://www.simplemachines.org/community/index.php?topic=585605.msg4150152#msg4150152
I happens when ssi_recentTopics is called on the page

### Steps to reproduce
1.  In this case: when usign a portal with recenttopics blocks
2.  Make or chaneg a post with an attachment

### Environment (complete as necessary)
- Version/Git revision: SMF2.1.3
- Database Type: 
- Database Version:
- PHP Version: 8.0.28

### Additional information/references
See solution provided here:
https://www.simplemachines.org/community/index.php?msg=4150101

**Comment by tinoest** [comment] 2023-04-09 14:01
I think this is a duplicate of this. 

https://github.com/SimpleMachines/SMF/issues/7625

**Comment by Bopske** [comment] 2023-04-09 14:45
I guess so...

**Comment by DiegoAndresCortes** [comment] 2023-06-15 02:30
Could this be closed if it's a duplicate?

**Closed as not planned** 2023-06-15 04:12 UTC
Labels: Attachments, SSI
