### ISSUE TITLE
 Pagination error

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#7522] opened 2022-07-11 07:27 UTC
while cleaning up some spam, I noticed that some page numbers seemed wrong

see where it says `1.95` instead of  `1`

https://www.simplemachines.org/community/index.php?topic=582201.40

Seems to me that this only happens when manually fiddling with the numbers.

Marking as `Serious bug` with **high priority** because it should load the last page of posts, not be empty.

**Comment by sbulen** [comment] 2022-07-18 01:29
Is this a dupe of #7389?

**Closed as completed** 2022-10-18 21:58 UTC
Labels: Serious Bug
