### ISSUE TITLE
Upgrade: forum don't work after upgrade process ended.

### ISSUE THREAD

**Issue by realdigger** [SimpleMachines/SMF#3854] opened 2017-01-18 06:07 UTC
After upgrade process ended, Settings.php have this line which cause critical error
`$upgradeData = #remove#;`

**Comment by Mavn** [comment] 2017-01-18 06:23
I have same problem

**Comment by sbulen** [comment] 2017-01-18 07:21
This is a dupe of this issue:
Upgrader - : unserialize(): Error at offset 0 of 15 bytes in ... upgrade.php on line 125 #3841

I've submitted a fix, but we're discussing whether it needs a better approach over in the PR:
Set $upgradeData to null after successful upgrade #3849

**Comment by Oldiesmann** [comment] 2017-01-19 02:50
Duplicate of #3841

**Closed as completed by Oldiesmann** 2017-01-19 02:50 UTC
