### ISSUE TITLE
05-11-2012 installation - messageindex

### ISSUE THREAD

**Issue by Akyhne** [SimpleMachines/SMF#232] opened 2012-11-18 21:21 UTC
Clean installation:

The message index shows a blank page with the error:
Fatal error: Call-time pass-by-reference has been removed; If you would like to pass argument by reference, modify the declaration of call_integration_hook(). in /home/www/mysite.com/Sources/MessageIndex.php on line 680
#678    // Allow adding new buttons easily.
#679    // Note: $context['normal_buttons'] is added for backward compatibility with 2.0, but is deprecated and should not be used
#680    call_integration_hook('integrate_messageindex_buttons', &$context['normal_buttons']);

**Comment by norv** [comment] 2012-11-18 22:17
This must be on PHP 5.4+, where passing arguments by-ref at runtime has been removed.

Thank you for the report. We will have to update the old hooks too.

**Comment by live627** [comment] 2012-11-19 05:22
Globals should not be passed.

**Comment by emanuele45** [comment] 2012-11-19 09:15
Duplicate of #54.

**Closed as completed by emanuele45** 2012-11-19 09:15 UTC
