### ISSUE TITLE
custom profile fields, standard (with title)

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1887] opened 2014-06-23 14:11 UTC
when you use the option standard (with title) it includes the cust_ prefix to the name of the field, it should just include the name without the prefix

**Comment by MissAllSunday** [comment] 2014-06-23 16:11
Cannot reproduce this,   the "Name" or also called "Title" is what is used as a prefix, it has always been like that, it specifically says the title will be included.

If no title was provided, the code uses the ID for the custom field, but in theory, any custom value should have a proper name/Title.

**Comment by illori** [comment] 2014-06-23 16:15
strange,  enabled it again [back to standard (with title) and the cust_ prefix is not showing...

**Comment by illori** [comment] 2014-07-01 22:14
after running the upgrade script the cust_ prefix is showing on the titles of the profile fields in the mini profile.

so if i have a field named test, in the mini profile i have cust_test:

**Closed as completed** 2014-07-08 19:03 UTC
Labels: Profile Fields
