### ISSUE TITLE
Weird interaction between account settings and iPad/Safari and iPad/chrome  save password feature.

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1757] opened 2014-06-04 17:50 UTC
Please use html5 form attribute autocomplete="off" to work around several buggy browsers that are over eager to jam a saved username into a form with a password field in it.  

<hr>

This is not a problem in 2.0.7.
When I go to the account settings page, my ipad automatically replaces my email address with the username I used when I logged in.

Since I wanted to fix another field in that page, I decided I needed to fix the email address at the same time.  SMF complained that I had changed my email address and would therefore be logged out.  

But it did not log me out -- presumably because I had changed it to exactly what it had been before.
![image](https://cloud.githubusercontent.com/assets/3267025/3177479/a20f38e8-ec10-11e3-9d9c-dcf4e0605f33.jpg)
![image](https://cloud.githubusercontent.com/assets/3267025/3177477/a20cdc06-ec10-11e3-967d-e29a267b5eac.jpg)
![image](https://cloud.githubusercontent.com/assets/3267025/3177478/a20d2288-ec10-11e3-8968-b3a9563fb2b0.jpg)

![image](https://cloud.githubusercontent.com/assets/3267025/3177481/abfaca98-ec10-11e3-86d3-2199c767d2a7.jpg)

**Comment by illori** [comment] 2014-06-04 17:57
sounds like this may be a dup of #1191 which should be solved

**Comment by AngelinaBelle** [comment] 2014-06-04 18:16
Not a dup. The primary issue is that SMF and Safari for iPad are not compatible here.
So SMF is not iOS friendly.  Can any MAC users report in?

Safari thinks the email input field is meant for my username, and so automatically fills in the username it just remembered for me for this site.   It also automatically fills in my password at the bottom of the page.

Can the page tell Safari not to try this trick on this page, or would the fix involve renaming the input field.

The confusing bit about the changed but unchanged email address is just baggage; the email address was changed back to its database value by the time I submitted the form.

**Comment by illori** [comment] 2014-06-04 21:00
looking at the code for that element i might be willing to say this is an issue with your browser and not smf.

```
<input id="email_address" class="input_text" type="email" value="myemailaddress@emailaddress.com" size="30" name="email_address">
```

**Comment by AngelinaBelle** [comment] 2014-06-04 21:06
Issue with Safari for iPad. IOS 7.1.1 not compatible with that page. Don't know about chrome.

**Comment by illori** [comment] 2014-06-04 21:10
http://webcache.googleusercontent.com/search?q=cache%3Ahttp%3A%2F%2Fcache.nevkontakte.com%2Fproxy.html#!go/http%3A%2F%2Fbasics4mac.com%2Farticle.php%2Fautofill_bug_workaround makes it seem like this may be an issue with the auto fill on your device

**Comment by AngelinaBelle** [comment] 2014-06-05 01:45
This is not related to autofilling from my contacts; I have that setting turned off.
This problem occurs in Safari and chrome 35.1916.38 but not opera mini 7.05.45389
This can be a problem for iOS 7.1.1 users.

Two browsers recognize the email input field in account settings as being the same as the username input field in ?action=login

**Comment by illori** [comment] 2014-06-05 09:34
and it is not trying to auto fill from any other source? since no one else has reported this i think it is an issue with how your browser is configured and not an smf issue.

**Comment by AngelinaBelle** [comment] 2014-06-05 11:48
Not seeing this problem elsewhere.

I beg.  I beg.  I beg others to turn on "save passwords" and test this feature in a variety of platforms rather than telling me it is not an issue for iPad users

**Comment by XinYenFon** [comment] 2014-06-05 12:12
I'm currently using Windows Phone 8.1 - IE, that part is empty.

**Comment by AngelinaBelle** [comment] 2014-06-05 12:50
Email goes empty?  That is weird

**Comment by XinYenFon** [comment] 2014-06-05 12:52
Not email Current pass part :) Also i don't see any problem with mail part too.

**Comment by AngelinaBelle** [comment] 2014-06-05 13:06
Glad ie gets it right.
How hard would it be to &lt;form autocomplete="off"> ?
This would accommodate buggy Safari and chrome browsers on iPad and iPhone and who knows where else.

**Comment by Oldiesmann** [comment] 2014-06-05 15:11
Seems reasonable to me. Firefox wants to suggest usernames for that field as well (though it doesn't automatically fill it in since I have several accounts on my test board). It's probably better for security anyway.

**Comment by AngelinaBelle** [comment] 2014-06-09 11:34
This change did not fix the problem.  Can it be listed as a known issue -- Safari and Chrome for iOS and can be given as the source of the problem.

This is NOT a problem in 2.0.7-- in2.0.7, the browser tries to change the user display name

**Comment by illori** [comment] 2014-06-09 11:37
then that means on that forum you can change your display name, you should test apples to apples on a forum where you can not change the display name

**Comment by AngelinaBelle** [comment] 2014-06-09 12:42
I did not understand your communication above, Illori. I will attempt to clarify my statement above that, and hope for the best.
  I am remarking that the fix did not solve the issue
- oldiesmann's Fix #1764 did not fix the problem; perhaps it should be listed as a known issue

---

Just for reference, to compare to behavior of the current stable version:
- I double-checked with the same browsers on SimpleMachines.org, which is running. 2.0.7, and noted that, on that forum, with the same browser, iOS autocomplete attempts to change the users display name rather than the email.

**Comment by illori** [comment] 2014-06-09 13:17
AB check that on the forum you are testing on you can modify your dispay name, if you can not, then it is not a valid test compared to SM.org where you can modify your display name.

**Comment by illori** [comment] 2014-06-09 13:21
also have you confirmed that your test forum has updated to a revision that includes the changes oldies made?

**Comment by AngelinaBelle** [comment] 2014-06-09 13:51
- on test2.turtleshelllprod.com, I am able to modify my display name.
- before testing, I checked the admin log to see that upgrade had been run 3 days after the commit date given above.

**Comment by Oldiesmann** [comment] 2014-06-10 15:55
If it's still an issue even after that change, it means that the attribute isn't supported by iOS. Unfortunately there's not a lot we can do in that situation.

**Comment by illori** [comment] 2014-06-10 15:57
so should we leave this open @Oldiesmann or close it?

**Comment by Oldiesmann** [comment] 2014-06-10 16:00
I'll close it for now since it seems to be working fine in Firefox 30 on my laptop (no fields are auto-filled and no suggestions are given for any of them).

**Closed as completed by Oldiesmann** 2014-06-10 16:00 UTC

**Comment by AngelinaBelle** [comment] 2014-06-10 16:03
I would support adding this to a list of known issues before closing the topic.  That way, users of various versions of Chrome and Safari can understand that they will run into this issue unless they turn off the password-memory feature.

There is a workaround that involves creating invisible "fake" username and password field before any other text input on the page to fool these browsers, but it seems like an ugly solution.  
http://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by AngelinaBelle** [comment] 2014-06-11 12:17
The current Chrome Canary, which will be Chrome 36 for desktops, will be ignoring autocomplete=off
There may or may not be a setting or omnibox flag that can be used to disable "ignore-autocomplete-off"
https://groups.google.com/a/chromium.org/d/msg/chromium-dev/zhhj7hCip5c/fUflgXE7i1QJ

Reportedly, future versions of Safari will also be ignoring autocomplete=off
https://discussions.apple.com/message/25542444#25542444

So the problem could get bigger in the future.
The only proposed workaround is to try this before any type=password field in the form:
&lt;input type="text" style="display:none" />&lt;input type="password" style="display:none"/>

**Comment by AngelinaBelle** [comment] 2014-06-27 13:21
This is still a problem on the iPad with Safari and chrome #1954 to fix

**Comment by AngelinaBelle** [comment] 2014-07-23 13:00
This is still a problem
