### ISSUE TITLE
[3.0]: Cannot assign null to property SMF\Config::$auth_secret of type string

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#8276] opened 2024-07-01 17:25 UTC
### Basic Information

Attempting an install, getting an error at the very start:

> 
Fatal error: Uncaught TypeError: Cannot assign null to property SMF\Config::$auth_secret of type string in D:\wamp64\www\30livegit\SMF\Sources\Config.php:895 Stack trace: # 0 D:\wamp64\www\30livegit\SMF\Sources\Config.php(864): SMF\Config::set(Array) # 1 D:\wamp64\www\30livegit\SMF\install.php(60): SMF\Config::load() # 2 {main} thrown in D:\wamp64\www\30livegit\SMF\Sources\Config.php on line 895

### Steps to reproduce

1.  Attempt an install using current git https://github.com/SimpleMachines/SMF/commit/7ca376391486c465a287e51345e348190f771390

### Version/Git revision

https://github.com/SimpleMachines/SMF/commit/7ca376391486c465a287e51345e348190f771390

### Database Engine

MySQL

### Database Version

8.4

### PHP Version

8.3.8

### Logs

```shell
Fatal error: Uncaught TypeError: Cannot assign null to property SMF\Config::$auth_secret of type string in D:\wamp64\www\30livegit\SMF\Sources\Config.php:895 
Stack trace: 
#0 D:\wamp64\www\30livegit\SMF\Sources\Config.php(864): SMF\Config::set(Array) 
#1 D:\wamp64\www\30livegit\SMF\install.php(60): SMF\Config::load() 
#2 {main} thrown in D:\wamp64\www\30livegit\SMF\Sources\Config.php on line 895
```

### Additional Information

Was attempting to reproduce #8243

**Comment by Sesquipedalian** [comment] 2024-07-01 17:30
Try again with [93d1247](https://github.com/SimpleMachines/SMF/commit/93d12471b2c87b0a6075995ebaeae96b6e44aff9)

**Comment by sbulen** [comment] 2024-07-01 17:36
Will do... Gimme a sec... Testing this "forum on a live git repo" approach...

One observation - I started looking into it & auth_secret doesn't have a default value in Settings.php - not even an empty string...

**Comment by Sesquipedalian** [comment] 2024-07-01 17:40
> One observation - I started looking into it & auth_secret doesn't have a default value in Settings.php - not even an empty string...

That's by design. It's been that way since $auth_secret was first introduced.

**Comment by sbulen** [comment] 2024-07-01 17:46
OK, install completed, but...  it oddly displayed auth_secret at the top of the screen...

![image](https://github.com/SimpleMachines/SMF/assets/23568484/9dee34b0-3d53-4440-84b5-3fe63d81fe70)

**Comment by sbulen** [comment] 2024-07-01 17:47
...and continues to do so...

![image](https://github.com/SimpleMachines/SMF/assets/23568484/1ed497f7-f7c7-4d18-b3f1-7dcbfb1d7f21)

It's malformed in Settings.php:

![image](https://github.com/SimpleMachines/SMF/assets/23568484/8a9b048d-5a0d-4acb-84aa-bf73a4882d2d)

**Comment by sbulen** [comment] 2024-07-01 17:51
And not just auth_secret:

![image](https://github.com/SimpleMachines/SMF/assets/23568484/4f3a5934-efa1-4992-83d1-2333284227ce)

![image](https://github.com/SimpleMachines/SMF/assets/23568484/542f3a7f-3250-431c-97ff-9e932e8916a9)

**Comment by Sesquipedalian** [comment] 2024-07-01 18:00
That's unexpected. Hm...

**Comment by Sesquipedalian** [comment] 2024-07-01 18:20
Found the problem. Fix will be submitted shortly.

**Comment by Sesquipedalian** [comment] 2024-07-01 18:28
#8277 has been merged. Please confirm at your earliest convenience that it fixes the problem for you, too.

**Closed as completed** 2024-07-02 03:46 UTC
