### ISSUE TITLE
Upgrade Bug - setting attachment mime types

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6181] opened 2020-07-20 09:02 UTC
#### Description
Not all mime types get calculated due to a bug in the upgrade script.

This doesn't really matter much but should be fixed.

### Steps to reproduce
1. Upgrade from 1.1.21 to 2.1 latest

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:mysql
- Database Version:mysql
- PHP Version:7.2

### Additional information/references
This is caused by your update script skipping rows because you are setting mime types on attachments and then searching for a limit query on where mimetypes != '' on each step into the upgrade for mime types.  It's essentially the same bug I found earlier regarding attachments not being renamed and moved properly.

**Comment by Butterflysaway** [comment] 2020-07-20 09:02
Will try to fix for you soon

**Comment by Butterflysaway** [comment] 2020-07-20 09:04
problem area : upgrade_2-0_mysql.sql

```php
$request = upgrade_query("
			SELECT id_attach, filename, fileext
			FROM {$db_prefix}attachments
			WHERE fileext != ''
				AND mime_type = ''
			LIMIT $_GET[a], 100");
//A few lines later you are setting mime_type which then makes the next limit query get lost because you aren't selecting the same rows.
 		foreach ($ext_updates as $key => $update)
		{
			upgrade_query("
				UPDATE {$db_prefix}attachments
				SET mime_type = '$update[mime]'
				WHERE id_attach IN (" . implode(',', $update['files']) . ")");

			// Remove it.
			unset($ext_updates[$key]);
		}

**Comment by sbulen** [comment] 2021-03-15 07:24
I cannot reproduce this.

Although the query has a limit 100, the prior issues were fixed already...  I.e., the limit 100 will always return the next 100 issues (mime = '')  as the query executes.  

It will never skip a record as long as the mime_type is not ''.

I suspect there were other issues going on here.

**Comment by MissAllSunday** [comment] 2021-05-13 19:33
@Butterflysaway Are you still able to reproduce this?

**Comment by sbulen** [comment] 2021-06-10 02:06
I am going to close this out.  I cannot reproduce, & I have tried a couple of times.

I've even gone so far as to wipe out mime_type on a large forum & rerun the upgrader.  Note there are *some* differences, due mainly to the different ways the mime_type has been calculated over the years.  But there is no large # of fields getting skipped.

**Comment by sbulen** [comment] 2021-06-23 20:31
Actually I will reopen this.  

Looking at the PR #6177 and the related discussion, this is also likely a symptom of a LIMIT without an ORDER BY.  We should test adding the ORDER BY here as well.

**Closed as completed** 2021-07-06 21:29 UTC
Labels: Upgrader
