### ISSUE TITLE
INFORMATION_SCHEMA.GLOBAL_VARIABLES feature is disabled

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4441] opened 2017-12-28 22:31 UTC
Brand new install from github.  wamp server.  php 5.6.  Mysql 5.7.  

This comes up for the first two entries in the admin console.  

This is indirectly related to the discussion regarding this issue on the forum:
https://www.simplemachines.org/community/index.php?topic=557286.0

And also indirectly related to this open PR #4391 

See attached:
![image](https://user-images.githubusercontent.com/23568484/34424760-bd92d94e-ebda-11e7-98bb-d107c80e12da.png)

**Comment by sbulen** [comment] 2017-12-28 22:50
I thought that PR #4391 was still outstanding, but it looks like that commit was pulled along into #4392 as well.  So #4391 is a duplicate, its change has already gone in.

**Comment by albertlast** [comment] 2017-12-29 08:14
The issue is partly known,
as i mention in the pr of #4391 and reason why this pr is still open.
Since no one is response about my question about the mysql version
the issue is "wanted".

**Comment by sbulen** [comment] 2017-12-29 15:13
One of the conmits in PR #4392 attempted to deal with an issue that impacted a small # of mysql 5.0.x users, but it did so in a way that impacted everyone on mysql 5.7.6+.   

It made things worse - it impacts more people, all those on the more recent versions.   

I think we need to revert that commit in #4392, at least until you get your answer and can submit a proper fix.  

Make sense?

**Comment by albertlast** [comment] 2017-12-29 15:29
Dont wast your time about this please,
i know all the solutions,
the smf team need do decisions,
when they can't decide we can't help.

**Comment by colinschoen** [comment] 2017-12-29 15:31
Apologies. Will be looking at this again after holiday. Thanks for the patience.

**Comment by Sesquipedalian** [comment] 2018-01-10 20:33
I've given a little push in the conversation on the forum. We should have the final answer soon so that @albertlast can finally implement his fix for this.

[edit] link removed. please dont link to private topics. - Illori

**Closed as completed** 2018-01-11 23:22 UTC
Labels: MySQL
