### ISSUE TITLE
Image proxy issue - cURL gets a 403 Forbidden  (2.0 & 2.1)

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4581] opened 2018-03-04 00:38 UTC
No fix yet, but I have started to zero in on one of the issues with the proxy on my site.  I'll share what I know so far.  

Although many images are easily retrievable via other means, under the covers, a 403 Forbidden is returned to cURL.  The host server may not return that it is an image/jpeg in the header either.  All this basically makes the proxy punt on it, leaving blank space on the page.

Example image: 
`http://www.primovasound.com/gfx/base3.jpg`

Note the above image works fine on my WAMP test server in 2.0/2.1, but not on my linux hosted server on 2.0/2.1.  Your mileage may vary...  We may all be seeing different parts of this problem...

This is not a unique problem:
https://www.google.com/search?q=curl+403&oq=curl+403&aqs=chrome..69i57j69i60l3j0l2.1471j0j7&sourceid=chrome&ie=UTF-8

Most of the solutions out there involve getting clever with the CURLOPT settings.  I haven't found one that works with the above image yet.  

The CURLOPT_BINARYTRANSFER setting currently specified in proxy.php has been deprecated & does nothing.  

Note that with the header not saying the Content-type is 'image' poses a different problem.  Should we rely on the Content-type?   Or should we use the file's magic number?   Maybe once we're past the 403 the Content-type will show up...

**Comment by albertlast** [comment] 2018-03-04 05:36
I think the issue got already fix in this pr 
https://github.com/SimpleMachines/SMF2.1/pull/4550 please do a test.

**Comment by sbulen** [comment] 2018-03-04 06:18
I just tried #4550 and it did not resolve this issue.

**Comment by albertlast** [comment] 2018-03-04 07:26
the issue that you got a blank image i guess?

The code say when curl get not a 200 status: https://github.com/SimpleMachines/SMF2.1/pull/4550/files#diff-95dde0693614aded154dc51012aba3b8R105
then show a empty page.
From this point of view we got two options,
- change nothing because works as designed
- when error appear forword the user like we do on to big images (with the issue that we try to display http in a https env)

**Comment by sbulen** [comment] 2018-03-04 07:46
Yes - blank image.  The problem is that the  403 is erroneous - the image is there.  Just follow the link above.  I believe our cURL options are wrong somehow and don't work with some servers.  

I do believe that if we get past the cURL issue the content type issue goes away also (it does in my other environment).

**Comment by albertlast** [comment] 2018-03-04 08:11
i'm not sure if you read my update at comment,
about the options.

Since my test env is also windows i'm not able to reproduce this (the image get loaded),
but you could try to find the diff between you win and linux env.
I would hope that the diff is in the request header and this you could access by this: https://stackoverflow.com/questions/3164405/show-curl-post-request-headers-is-there-a-way-to-do-this

**Comment by sbulen** [comment] 2018-03-04 20:05
Note we already set CUROPT_HEADER here:
https://github.com/SimpleMachines/SMF2.1/blob/9c605bce14fb19718217675953ac014361a8ff8a/Sources/Class-CurlFetchWeb.php#L47

I've been able to confirm the same CURL options are passed in both win & linux.  (No surprise, same code...)   

I haven't yet figured out where to find the header data that is passed.  It doesn't appear to be saved in the SMF $curl object. 

I have confirmed that what is being returned in the $response['body'] is basically a 403 forbidden page that contains the following:   

```
                            <h1>Accessing http://www.primovasound.com/gfx/gkpx_14_2017.jpg securelyâ€¦</h1>

                            <span>This is an automatic process.  Your browser will redirect to your requested content in <span id="seconds">5</span> seconds.</span>
                        </div>

                        <form id="challenge-form" action="/verify.php" method="post">
                            <input type="hidden" name="hash" value="85aa65a83db10aa9a38f714919091b5996e60c69"/>
                            <input type="hidden" name="origin_url" value="http://www.primovasound.com/gfx/gkpx_14_2017.jpg"/>
                        </form>
```

This appears to be a redirect used when certain types of requests are detected...   My linux site gets this, my wamp site doesn't...  

I'm going to keep looking at this.  If I find where that header info is buried, I'll share it...

**Comment by albertlast** [comment] 2018-03-04 20:07
the stackoverflow url which i postet in the comment before show you how to access this information.

**Comment by sbulen** [comment] 2018-03-04 20:13
Actually, it doesn't.    The only example is how to get the error code, which is already captured & provided by our curl object (as are the *returned* headers).  It doesn't actually show you where the *sent* header is.   

One of the responses shows you how to dictate your own header...  That is interesting.  

As I stated, I'll keep looking into it.

**Comment by sbulen** [comment] 2018-03-04 22:56
Assuming I'm reading this right...   The header coming from the working system looks like this:
```
GET /gfx/base3.jpg HTTP/1.1
Host: www.primovasound.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko Firefox/11.0
Accept: */*
Accept-Encoding: gzip,deflate
```

And the header from the non-working systems is BLANK...   

I suspect the problem is that first line, which is non-standard (not key:attr)????   So it's getting stripped.  

Similar issue reported here:
https://stackoverflow.com/questions/13466239/curl-sending-blank-headertesting-java-web-server

Next challenge:  _Now I gotta figure out where that header comes from..._

**Comment by sbulen** [comment] 2018-03-04 23:38
The header appears consistent...  Now I'm really confused.  They both look like:
```
GET /gfx/base3.jpg HTTP/1.1
Host: www.primovasound.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko Firefox/11.0
Accept: */*
Accept-Encoding: gzip,deflate
```

I was able to find it in 'request_header' from curl_getinfo after setting CURLINFO_HEADER_OUT to true as described on this page:
http://php.net/manual/en/function.curl-getinfo.php

**Comment by Sesquipedalian** [comment] 2018-03-05 01:13
I just tested http://www.primovasound.com/gfx/base3.jpg and http://www.primovasound.com/gfx/gkpx_14_2017.jpg using a Linux server, and proxy.php was able to retrieve and display both images correctly. I don't know what's up with your configuration, @sbulen, but the problem doesn't appear to be in proxy.php's code. 

Speculation: Perhaps you have been testing against that URL a lot recently, and their server has started deploying poorly conceived countermeasures against you?

**Comment by sbulen** [comment] 2018-03-05 01:48
Anything's possible.  The engineer who runs that website was the one who pointed out the issue - that all his images disappeared throughout our forum.  I'll reach out to him directly, to see if I can learn anything there.  I'm guessing he runs the website, too...  

Note that the 403 is under the covers & happens at cache time - it appears as a 404 to the end user as the cached file really does not exist.  Part of the reason I'm digging in is that I've seen so many 'where are my pix' posts on the support forum.

**Comment by sbulen** [comment] 2018-03-08 05:35
I haven't heard back, but I am fairly certain that his ISP has blocked certain traffic from my ISP.  This being the internet, these things happen...   

**_I have confirmed that using fetch_web_data() solves my issues._**  I had to followup with a finfo_buffer(FILEINFO_MIME_TYPE) call to get the content_type, and a strlen() call to get the size.

**Comment by Sesquipedalian** [comment] 2018-03-08 05:40
Okay. That being the case, shall we close this issue?

**Comment by sbulen** [comment] 2018-03-08 06:04
It would make sense to retest & close after making that change.   Apparently, I got a good test case here!

**Comment by Sesquipedalian** [comment] 2018-03-08 06:12
> ... close after making that change. ...

Sorry, but which change do you mean?

**Comment by sbulen** [comment] 2018-03-08 06:16
Using fetch_web_data() instead of a direct call to curl.  As you propose on PR #4550.

**Comment by Sesquipedalian** [comment] 2018-03-08 06:20
Ah, I see. Thanks for the clarification. :)

**Closed as completed** 2018-03-11 19:14 UTC
Labels: Proxy

**Comment by sbulen** [comment] 2018-03-11 21:10
This one is not working for me.  Same behavior as before.

I have a version of proxy.php that used the OLD fetch_web_data that works - something feels lost in translation....   I'm not sure what the issue is at this point...

**Comment by Sesquipedalian** [comment] 2018-03-11 21:35
If the remote server is sometimes blocking your IP address, that is probably the cause. The only substantial change in 6cea2aa is the order in which the curl and fsockopen methods are attempted.

**Comment by sbulen** [comment] 2018-03-11 22:18
In my 2.0 forum, I just swapped out the curl call with fetch_web_data and it works.  I'm not sure why there is a difference.  I'll take a peek & see if I can understand why.  If I find something I'll open a new issue.
