### ISSUE TITLE
Avatar related issues

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#2530] opened 2014-11-25 19:56 UTC
- [x] if Gravatar forced, and user selects no avatar it shows default avatar in mini-avatar header and showing gravatar in rest. There shouldn't be a no-avatar option if gravatar forced or respect the select and show no avatar at all
- [x] if you don't force Gravatar and user selects no avatar then its showing default avatar on all places
- [x] if gravatar forced and user has no gravatar and its showing default avatar in mini profile and text (alt message on image) in rest of the forum.

**Comment by illori** [comment] 2014-11-25 22:55
this all is related to #2275 which the devs thought was not a bug.

**Comment by MissAllSunday** [comment] 2014-11-26 13:48
And yet I asked for DETAILS and no one provided anything...

> if you don't force Gravatar and user selects no avatar then its showing default avatar on all places

This is the correct behavior isn't it?  if not then please make up your mind on what its suppose to do...

> if Gravatar forced, and user selects no avatar it shows default avatar in mini-avatar header and showing gravatar in rest. There shouldn't be a no-avatar option if gravatar forced or respect the select and show no avatar at all

If gravatar is forced then it must show gravatar, no matter what choice the user has used.

Gravatar has its own unique "default avatar" for those mails that don't have an associated gravatar image and even SMF lets you specify which sets of "default gravatar" you can use.

**Comment by XinYenFon** [comment] 2014-11-26 13:58
Then it shouldn't be "No avatar" but "Default Avatar".

True, but still mini-avatar should also be showing the Gravatar not Default Avatar on Gravatar Forced situations.

**Comment by illori** [comment] 2014-11-26 19:53
in the admin panel you can force gravatar to be the default avatar for the forum.

when you select this option it should remove the option in the profile for a user to switch to no avatar. if that was done most of this issue would be fixed automatically. i pointed this issue with the no avatar option in the other issue.

**Comment by Oldiesmann** [comment] 2014-11-26 21:26
The biggest issue here is the "Force Gravatar" setting. It's a bit confusing...

When enabled:
User has not specifically chosen to use Gravatar - default is shown in forum header, user's Gravatar (if applicable) is shown everywhere else.
User has chosen to use Gravatar: Works as expected (user's Gravatar is used everywhere)
User specifically chooses "No avatar" (only after setting is enabled): A default avatar is used everywhere

Here's my suggestion on how to fix some of this mess:
1. Either a setting for whether or not to use the default avatar (for when Gravatar isn't forced), or at least some text that explains how it works. We have absolutely nothing that explains this. It's based solely on the existence of a "default.png" image in the avatars directory - if it exists and the user hasn't chosen another avatar (and Gravatar isn't forced), that file is used for their avatar.
2. When forcing Gravatar and the user has a Gravatar, use that in the header instead of the default one, regardless of whether the user has specifically chosen to use it. Also, we need to make the proper option selected in the profile, because it's confusing to have it using your Gravatar but have "No avatar" as the selected option.
3. Add helptext explaining the Gravatar settings. We can't assume everyone will know what Gravatar is.

**Comment by Xarcell** [comment] 2014-12-01 01:15
This is confusing. Can you have simplified settings like this:

1.| Use [Gravatar](https://gravatar.com/) - Assuming You Have Gravatar, Otherwise Theme Default Avatar Will Be Used.
2.| Use Theme Default Avatar.
3.| No Avatar - But Theme Default Avatar Will be Shown "If" Admin Has Selected To Use Default Avatars.

Force Gravatar? Why? Maybe I don't want my Gravatar to be shown.

**Comment by Kindred-999** [comment] 2014-12-06 14:53
but maybe the admin does.
Force Gravatar is an admin setting -- if you associate your forum account to a profile that has a Gravatar, the admin wants every user with such an association to use their defined gravatar and so, clearly to be marked as the same user.   Absolutely correct options IMO

The logic is a little convoluted... but I think Oldiesmann has the right idea

**Comment by XinYenFon** [comment] 2014-12-06 15:10
It's not about logic but execution, please read the issues and try to reproduce them you'll see the problems.

-----Original Message-----

**Comment by Oldiesmann** [comment] 2014-12-06 18:04
Doing a bit of digging here...

As far as the mini profile goes - for whatever reason, loadMemberContext isn't loading the avatar data properly in all situations. I'm not sure why though. In template_profile_popup(), if you change $context['member']['avatar']['image'] to $context['user']['avatar']['image'](the difference being that the first is the avatar for the user whose profile you're viewing, while the other is the avatar for the person doing the viewing, though in that case you're viewing your own profile), it works fine. Unfortunately I don't have time to dig into it further right now, but I'll look into it more in the coming days when I do have more time.

**Comment by Oldiesmann** [comment] 2014-12-08 17:34
Did some checking and figured out what's going on. Will commit fixes shortly.

The changes will also make the "force Gravatar" option do exactly that - always use the user's Gravatar (if they have one), even if they've chosen "No Avatar". We will still need to make some more tweaks to handle this (preferably remove the "No avatar" option from the profile and add appropriate helptext in spots), but this will fix the issues with Gravatar.

**Closed as completed** 2014-12-09 02:35 UTC
Labels: Avatars
