### ISSUE TITLE
Token verification failed in avatar and attachment setting not saved

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#528] opened 2013-07-26 12:30 UTC
hi,

Token verification failed in avatar and attachment setting not saved

**Comment by Oldiesmann** [comment] 2013-07-26 14:56
I can't reproduce this. I tried changing/saving both avatar and attachment settings on my test board and both options worked properly.

**Comment by XinYenFon** [comment] 2013-07-26 17:18
Please make sure you 're using latest repo.

**Comment by gevv** [comment] 2013-07-26 18:23
@ antes download and update the latest files, but I did mention that the problem continues avatar setting times did this problem first before pressing the "" Avatar, at the address given to the server "Install" option, I was active in

ettimki difference pruning done previously uploaded avatars view sizing error token disrupt whatever I wanted to turn it into an old appeared to increase the limit, then I wanted to add that setting has the same mistake in the section

http://imageshack.us/clip/my-videos/689/k3cznpjxrpbxwhrufrqryh.mp4/

**Comment by XinYenFon** [comment] 2013-07-26 18:55
Please edit your comment here and use only English 
Thank you :)

**Comment by Arantor** [comment] 2013-09-27 02:40
Can't reproduce this.

**Comment by Arantor** [comment] 2013-10-08 13:16
Still can't reproduce, closing.

**Closed as completed by Arantor** 2013-10-08 13:16 UTC
