### ISSUE TITLE
Unable to verify referring URL. Please go back and try again.

### ISSUE THREAD

**Issue by avalyn2** [SimpleMachines/SMF#5651] opened 2019-05-05 11:14 UTC
getting several errors like this in the log:

` Type of error: User 
Unable to verify referring URL. Please go back and try again.
http://myforum.com/index.php?action=login2`

**Comment by Sesquipedalian** [comment] 2019-05-08 00:25
Appears to have been caused by misconfigured cookie settings and to have been fixed by changing them: https://www.simplemachines.org/community/index.php?topic=567608.0

**Closed as completed by Sesquipedalian** 2019-05-08 00:25 UTC
Labels: Login/Sessions
