### ISSUE TITLE
Error about search

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#5908] opened 2019-12-30 01:54 UTC
#### Description
Message : Undefined variable: approve_query
/Sources/Search.php (Line 1828)

Not sure if that is new or not.

### Steps to reproduce
1. https://github.com/SimpleMachines/SMF2.1/commit/967b680eeb977a703cb58973790781169328a802 + https://github.com/SimpleMachines/SMF2.1/pull/5891.patch

### Environment (complete as necessary)
- Database Type: mysqli
- Database Version:5.7.28
- PHP Version: 7.4

**Comment by Oldiesmann** [comment] 2019-12-30 05:27
#5877

**Comment by sbulen** [comment] 2019-12-30 17:10
Yes, this is a dupe of #5877.  I'll close this out.

**Closed as completed by sbulen** 2019-12-30 17:10 UTC
