### ISSUE TITLE
integrate_buffer issue

### ISSUE THREAD

**Issue by asmith20002** [SimpleMachines/SMF#5997] opened 2020-02-04 21:17 UTC
Hello,

I had integrated a personal custom URL rewrite via integrate_buffer.  Sample:

```
function myRewrite($content)
{
	global $scripturl, $boardurl, $modSettings, $context, $smcFunc, $db_character_set;


       // Fetch topics from $content and store them into $found_topics
      
       // Find topic subjects
		$request = $smcFunc['db_query']('', '
			SELECT t.id_topic, t.id_board, m.subject
			FROM {db_prefix}topics AS t
				INNER JOIN {db_prefix}messages AS m ON m.id_msg = t.id_first_msg
			WHERE t.id_topic IN ({array_int:topics})',
			array(
				'topics' => $found_topics,
			)
		);
}
```

That function used to work fine in SMF 2.1 Beta 2 (when I actually wrote the code)

Downloaded the latest SMF from GIT (and RC2 from the official site) and this function has stopped working. The reason is database connection has been closed already in integrate_buffer function. To verify that it is the real issue I just put ````loadDatabase();````  at the beginning of the function and it started working again.

Not sure if this is a bug or it's like that by design.  Calling ````loadDatabase();```` again is a nasty hack.  If that is done by design, where do you think is the best place to run a query like that for the final buffer?

**Comment by jdarwood007** [comment] 2020-02-05 00:13
We don't explicitly call a close.  This is most likely either due to a php change or not using persistent connections.  A work around would be to call the queries earlier hook, store in a global and come back around to it in the rewrite.  The integrate_exit may be a place you can call at before the buffer kicks

**Comment by asmith20002** [comment] 2020-02-05 11:37
Tried with persistent connection, doesn't make a difference. The environment is the same though. OS + webserver + PHP + MySQL hasn't changed. The only change applied was running the upgrade.php and moving from Beta 2 to RC2.

Integrate_exit doesn't get called in every page. That's not good to handle custom URLs.

If you want to have a quick check yourself, you can use this fast code to see. Paste it anywhere you see fit.  Try with commenting/uncommenting `````loadDatabase();`````

For successful you should see the subject of a topic.
For failure, depending on your settings, a white page or an error.

````
$modSettings['integrate_buffer'] = 'custom_rewrite';
//$modSettings['integrate_exit'] = 'custom_rewrite';
function custom_rewrite($content)
{
	global $scripturl, $boardurl, $modSettings, $context, $smcFunc, $db_character_set;

		loadDatabase();

		// Need this here because if the database connection is terminated, we need to start over.
		$smcFunc['db_query']('set_character_set', '
			SET NAMES ' . $db_character_set,
			array(
			)
		);

		$request = $smcFunc['db_query']('', '
			SELECT m.subject
			FROM {db_prefix}messages AS m
			LIMIT 1',
			array()
		);

		$result = $smcFunc['db_fetch_assoc']($request);

		return $result['subject'];
}
````

**Comment by asmith20002** [comment] 2020-02-05 11:53
it worth noting that in Beta 2, it didn't require to put `````loadDatabase()````` there but it DID require to put ````` SET NAMES ````` which indicates that the connection was also terminated there but it did autoconnect when it reached the queries?  in RC2 it requires to `````loadDatabase()`````

**Comment by jdarwood007** [comment] 2020-02-05 23:59
As I mentioned, we don't call any close to the database (you won't even find a mysqli_close).  So as this is in the ob_start, php must have cleaned up the database connections at this point when you get the buffer data.
obExit should be called for everything, except possibly fatal errors that we can't handle gracefully.  It handles the templating so it should exist.

**Comment by albertlast** [comment] 2020-02-07 04:37
In early version of smf 2.1 loadDatabase() got called on more than one place,
this resulted in different behavior based on who was first.
With one pr from me? i guess the loadDatabase() got centralize.

Just give one example: https://github.com/SimpleMachines/SMF2.1/pull/4529/files

**Comment by Oldiesmann** [comment] 2020-02-08 02:16
That would explain why the database wasn't loaded after including SSI.php in a script I wrote to import shoutbox data from EhPortal to TinyPortal recently...

**Comment by albertlast** [comment] 2020-02-08 19:59
Well this doesn't explain why the database is not loaded,
i used this test code
```
<?php
require('./SSI.php');
$request = $smcFunc['db_query']('', 'select * from {db_prefix}members limit 2',array());
foreach ($smcFunc['db_fetch_all']($request) as $row)
    echo $row['id_member'] . '<br>';
```
works fine.

**Comment by Oldiesmann** [comment] 2020-02-08 21:58
The forum I tried it on is a regular RC2 release (hasn't been updated from GitHub as I don't want to break things too much) and it didn't work. I'll try the above code on my Git install (which is running the latest code from GitHub) and see if it works there.

**Comment by MissAllSunday** [comment] 2020-04-09 00:33
@asmith20002 Are you still having this issue? if so, can you reproduce it using the latest build?

**Comment by tinoest** [comment] 2020-04-17 11:49
If it helps ( it might not ) we had something similar in TinyPortal when using PHP5.6 and SMF2.1 all other versions of PHP were ok. We got around it with this code

```
// SMF2.1 and php < 7.0 need this
    if (TP_SMF21 && empty($db_connection)) {
        $db_options = array();
        // Add in the port if needed
        if (!empty($db_port)) {
            $db_options['port'] = $db_port;
        }
        if (!empty($db_mb4)) {
            $db_options['db_mb4'] = $db_mb4;
        }
        $options = array_merge($db_options, array('persist' => $db_persist, 'dont_select_db' => SMF == 'SSI'));
        $db_connection = smf_db_initiate($db_server, $db_name, $db_user, $db_passwd, $db_prefix, $options);
    }
```

**Comment by Oldiesmann** [comment] 2020-04-19 21:31
> I'm not sure why the markdown isn't working properly.

The markdown for multiline code is different than that for single-line code. See https://guides.github.com/features/mastering-markdown/#examples (click "code" under the "Examples" section)

**Comment by MissAllSunday** [comment] 2020-07-20 23:10
Has anyone else been able to reproduce this?

**Comment by jdarwood007** [comment] 2020-07-21 02:11
If somebody is able to produce it, it needs tracing to understand where the resource handles are being lost.  ObExit in Subs.php is a good place to do some var dumping and check.  This is where the final cleanups and the exit is called which then runs the ob_* registered callbacks.

**Comment by MissAllSunday** [comment] 2020-08-22 14:33
Gonna close this one, Feel free to create another one if someone is able to reproduce this issue.

**Closed as completed by MissAllSunday** 2020-08-22 14:33 UTC
Labels: Hooks
