### ISSUE TITLE
Boards/Categories sorted after upgrade

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#887] opened 2013-11-15 13:06 UTC
I upgraded my alpha build 3 times (2.0.x to 2.1 Alpha) - (2.1 Alpha to 2.1 Alpha) - (2.1 Alpha to 2.1 Alpha) and my boards/categories sorted differently from as it needs to be.

But if i edit a board (move up/down) everything fixes itself.

Apache version  2.4.7
PHP version     5.4.23
MySQL version   5.5.35-cll

**Comment by Arantor** [comment] 2013-11-15 16:35
Yeah this is related to issues mentioned in #858 and ideally we just need to rewrite the code in a 'once and for all' fashion.

**Comment by Arantor** [comment] 2013-12-05 22:35
I briefly outlined how we might deal with this on a permanent basis.

The problem is because the board index is dependent on the table being in the correct order all the time. This is because the table structure is likely to cause all kinds of fun around things like filesorts because of the large text columns, so if you have it in the correct order already, no sorting is required.

PostgreSQL and SQLite already don't bother with this, they just have an ORDER BY clause in there anyway so whatever we do doesn't really affect them.

Problem 1: InnoDB doesn't work that way. Specifically, InnoDB always orders the table by primary key. It has been suggested on the forum to order the table physically by board_order and make that the primary key, and use id_board as a UNIQUE to effectively maintain the same setup, but that's not always a given either.

Problem 2: It seems MySQL as of 5.6 doesn't always respect this behaviour even for MyISAM, meaning that effectively we cannot really rely on it any more for ordering.

Which means we're back to filesorts. The first filesort kicks in with the moderators being joined, but if we divest them off to a separate query as per #858 in the first place, we get a performance saving anyway when there's no per-board moderators applicable - which has savings beyond the board index (since the same query is also used for child boards in the message index)

If you strip those joins from the main query, you still get a filesort from the text fields in the boards table. But from a selecting and ordering perspective, it looks very much as though from my limited testing that we can avoid the filesort by dropping the text fields and using varchars instead.

MySQL 5.0.3 added the ability to have varchars beyond 255 characters, and if we went up to... say... 2000 characters that should cover pretty much all the normal cases of board descriptions etc. which should also solve our filesort. Yes, this won't be as fast as a table scan, but it should be an order of magnitude faster than just going back to a bare filesort. (I would note that this is a limitation pretty much everyone faces, though everyone else just seem to accept the filesort cost and be done with it)

**Comment by XinYenFon** [comment] 2014-02-07 16:09
My bad not to post my server info, but since i saw this issue related to mysql 5.6 only - I'm using mysql 5.5.

**Comment by Oldiesmann** [comment] 2014-02-07 16:17
It could also be an issue on 5.5 if you're using InnoDB. Either way it's something we'll need to fix for 2.1.

**Comment by Ant59** [comment] 2014-04-29 07:35
So was this issue fixed by this commit?
https://github.com/margarett/SMF2.1/commit/e591cf7caf3c8c79a431683843eb321302c8d3ff

**Comment by Arantor** [comment] 2014-04-29 12:25
The answer to that would be not completely, no.

**Comment by Oldiesmann** [comment] 2014-05-13 21:30
This should be fixed with #1637 now. Any further comments or can this be closed now?

**Comment by Arantor** [comment] 2014-05-13 22:37
I already left further comments that didn't get replied to, but that have a very direct bearing on things. I'd also assume that someone is going to do some serious testing on this on all supported platforms to check it is working as expected (and do so after moving boards around and so on)

**Comment by Dragooon** [comment] 2014-05-14 10:00
Which comments (sorry if I missed them, but I'm not sure what you're talking about here)? Testing is definitely required, from the little testing I did it seems to work without performance losses (and I imagine it'll cause some performance gains in alternate platforms since ORDER BY is not required)

**Comment by Arantor** [comment] 2014-05-14 19:07
The part about moderators. If you don't display them - and it's pretty crowded in there - you could drop the query entirely. Or at least if you push the fact that a given board has moderators to the boards table, you can determine whether you need to have the query or not.

**Comment by smfvn** [comment] 2014-05-15 04:01
<s>Sorry for my interupt! With the lastest package, I can't see any topics in the Message Index although I can see them in Board Index and can view by index.php?topic=...</s>
Edit: I can't see Welcome topic (topic=1) in the Message Index, others are fine!

**Comment by Oldiesmann** [comment] 2014-05-15 15:44
@smfvn - please open a new issue and provide a link to your board.

**Comment by Oldiesmann** [comment] 2014-05-15 17:08
Back on topic here, as far as the moderator queries go...

I really think the best solution here is to just cache all that info when the board is created/updated or after the info is pulled the first time. We just store the data as empty arrays if the board doesn't have any moderators/moderator groups (since the cache stuff returns "null" if the data isn't cached).

I'm fine with adding a setting to hide the moderators list as well, but I can't recall seeing any requests for this.

However, I really do not understand the "indicate whether a board has moderators in the boards table" suggestion at all. I have never heard of this logic being applied to anything database-related (keep in mind I've taken several database-related classes in school). What's so bad about these queries that we need to apply logic to only run them if absolutely necessary? Why hasn't similar logic been suggested elsewhere (indicate whether a message has attachments; indicate whether a group has members; indicate whether a user has made any posts...)?

**Comment by Arantor** [comment] 2014-05-16 00:19
> What's so bad about these queries that we need to apply logic to only run them if absolutely necessary?

I don't know, I'm just opposed to making two queries every page load when I can determine I already don't need them. And for the majority of cases you won't need them. Fortunately for me this isn't a problem as in my code it has already been removed.

> Why hasn't similar logic been suggested elsewhere (indicate whether a message has attachments

It has, in fact, been suggested years ago on Mantis. It would also fix the long-standing bug around posts with attachments getting their icon forcibly changed but not changed back if the attachments are deleted. You could turn that into a neat feature by using it to indicate the number of attachments on a given topic's first post as a detail on the board index.

It could also give you a performance saving around having to actually query if you know there aren't any messages with attachments, which on most forums is the norm on a given page's worth of messages. (You're already doing a query to fetch the posters for a given slice of the topic, fetching an attendant count of attachments is no more intensive in the wider view of things)

>  indicate whether a group has members; 

Because it's not queried enough to make it worthwhile. In the case of the board hierarchy moderators, you're doing something that's accessed _frequently_. Having a note of whether you actually can shortcut some of the work or not is a smart move. But for groups, the number of times you need to find how many people are in a group is relegated solely to the admin panel and you might as well not bother in those situations.

>  but I can't recall seeing any requests for this.

Other than mine, which has better justification for it than most of the requests I've seen put into SMF in 2.1.

What users are actually asking for? The common trends that users are asking for is to focus content on what's important, to make the layout clean. Having the list of moderators everywhere on a board index is actually not that useful. Would make so much more sense to display it on the board itself, rather than as part of a board index. Also you might want to consider dropping it from the linktree while you're at it, since it can make a stupidly long linktree.

Example you end up with: "My Community ►  General Category ►  General Discussion (Moderator: Arantor)" and that's without even having any sub-boards to contend with which also make the linktree longer. Note this also has consequences for responsive layouts.

Has anyone bothered to look at other forum software? They don't do it. Maybe there's a reason they don't do it and haven't done it in some time. The answer isn't 'because SMF's awesome', either. (And before anyone brings out the strawman of 'we don't copy other systems or their features', it is still important to understand the choices made by rivals. More importantly: the fact this information is not shown by default and there is a distinct lack of requests for it to do so.)

> I really think the best solution here is to just cache all that info when the board is created/updated or after the info is pulled the first time.

Apart from the fact that caches are by definition temporary and will be cleared daily if nothing else? I was just suggesting the cache have a sense of permanence about it.

>  I have never heard of this logic being applied to anything database-related (keep in mind I've taken several database-related classes in school).

If you've taken classes you should understand the difference between normalised (e.g. as far as 3NF) and denormalised data and if your teacher did the job properly, it should have been made clear that denormalisation is a quirk of design but not inherently bad where performance is a concern.

In an ideal world, we'd have totally normalised tables to avoid data redundancy. Except we have many instances of intentionally denormalised data for performance; half the fields in smf_topics don't actually _need_ to be there but they're kept there because it's faster to query that there than it is to actually fetch it from attendant sources, and it would be possible to construct queries that worked in that fashion.

This is, inherently, a suggestion for denormalised data - meta data in this case - whose primary purpose enables a performance saving on every instance of the board index or any display of sub-board indexes. Given the potential savings, a minor bit of denormalisation is a tiny price to pay in the long run.

But I suspect that wasn't covered in your classes, where only the theoretical ideal 'how it should be done' method gets taught, and not necessarily what applies in real life. Which is why looking at real world use, benchmarks and so on, is so important.

_shrug_ I offered it to you. I provided the bases on which I suggested it. Whether you choose to use it is not my problem any more. But you have made it clear that my suggestions aren't particularly welcome. Too busy sticking to the established order of things. Good luck with that.

**Comment by Dragooon** [comment] 2014-05-16 09:04
> I don't know, I'm just opposed to making two queries every page load when I can determine I already don't need them. And for the majority of cases you won't need them. Fortunately for me this isn't a problem as in my code it has already been removed.

Fair enough, but these are very fast two individual queries. MySQL won't even bother with them if the tables are empty.

> Apart from the fact that caches are by definition temporary and will be cleared daily if nothing else? I was just suggesting the cache have a sense of permanence about it.

A daily cache would give a much larger performance gain on most of the forums than skipping the query only if the moderators are not present, caching the moderators can save the two queries in most scenarios for a long time (especially when there are a lot of moderators, these queries can be as slow as the new BoardIndex one), plus a daily cache still prevents these queries from being run at every page load

> This is, inherently, a suggestion for denormalised data - meta data in this case - whose primary purpose enables a performance saving on every instance of the board index or any display of sub-board indexes. Given the potential savings, a minor bit of denormalisation is a tiny price to pay in the long run.

And that's the reason I'd rather not do this, SMF is really denormalised as is. I'd rather not denormalise further and add code redundancy it to save a query that takes 1/1000th of a second (phpMyAdmin numbers) when the table is empty

> shrug I offered it to you. I provided the bases on which I suggested it. Whether you choose to use it is not my problem any more. But you have made it clear that my suggestions aren't particularly welcome. Too busy sticking to the established order of things. Good luck with that.

You have this wrong idea that your suggestions are not welcomed, but I spent hours on rewriting board's sorting queries, boardindex and the Sphinx API solely based on your suggestions. Not all your suggestions can be met with the same enthusiasm you have but don't think that they're not welcome.

**Comment by Oldiesmann** [comment] 2014-05-16 18:46
Your suggestions are indeed welcome. We may not agree with them or understand why they're being made, but that doesn't mean we don't welcome your ideas. We're greatly appreciative of what you've contributed to 2.1 so far (both as a team member and as a friend/user of SMF).

You are correct that my classes have focused mostly on normalization. I am not too concerned with that aspect as far as SMF is concerned - in the real world the "ideal" way of doing things is often different than the way things "should be" done. What I am against is adding columns to tables for the simple purpose of not running queries that wouldn't take very long to run in the first place. I am fine with possibly doing it in other areas where it would actually make a difference (the attachments thing is a good idea since those queries are rather messy in the first place, and it would make it much easier to handle the icon thing you mentioned).

As far as displaying moderators goes - I'm open to suggestions about how to better display that. My "I haven't seen any requests for this" comment was more because I didn't understand why we should stop displaying them (other than the "so we don't have to run those queries" argument). If it makes things more streamlined, "modern", etc., then I'm all for looking at alternative ways to display that information (such as via a "staff" page somewhere which could borrow some data from the staff report in the admin center perhaps).

**Comment by Dragooon** [comment] 2014-05-25 09:57
Also, this issue should still be closed since the question in hand doesn't have anything to do with the original problem of incorrect board order.

**Comment by Dragooon** [comment] 2014-05-27 17:34
Closing issue as it's fixed by #1637

**Closed as completed by Dragooon** 2014-05-27 17:34 UTC
Labels: Serious Bug
