### ISSUE TITLE
Cap Number of Alert Notifications 

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1990] opened 2014-06-29 15:49 UTC
Currently if you have a large number of notifications, SMF will attempt to display all of them if you click the alert dropdown. There should be a limit on the number of notifications that's displayed and a link on the bottom that says "Show More" for usability purposes. (a la facebook) Not to mention the current approach can break layouts.

![screen shot 2014-06-29 at 11 45 22 am](https://cloud.githubusercontent.com/assets/3847907/3423683/dec226f4-ffa4-11e3-8326-ce1d6df9c8f1.png)

**Comment by Oldiesmann** [comment] 2014-06-29 17:47
We already have an "all alerts" link, so I'd be fine with showing something like only the last 10 and letting them go to their profile to see the rest.

**Comment by mcblaber** [comment] 2014-07-01 03:22
That would be fine. :+1: Although I'm tempted to say the "All Alerts" or "View All Alerts" should be moved to below the 10th alert. Just seems more logical.

**Comment by XinYenFon** [comment] 2014-07-09 23:28
oh i missed this @mcblaber we eliminated some text because of translated versions can be bit more larger, and this leads the dislocations of text and for mobile view.

**Comment by MissAllSunday** [comment] 2014-07-11 14:41
Does this needs an admin/user setting or is it something we can hardcode at 10 ?

**Comment by illori** [comment] 2014-07-11 14:42
just hard code it, then no one can complain that things get screwy if they increase the number too high.

**Comment by MissAllSunday** [comment] 2014-07-11 18:03
Ok, made the change, however, this could lead to some confusion since the total amount of unread alerts is still added to the alerts button.

For example, I have 17 unread alerts but the code is only showing 10.  I would be better if there is some kind of text showing something like

"Showing latest 10" and a more promient "show all alerts link", the current one is somehow small and gets missed pretty easily when the list is showing.

**Comment by live627** [comment] 2014-07-12 00:35
Why not just use a scrollable div?

On Fri, Jul 11, 2014 at 11:03 AM, Jessica González <notifications@github.com

**Comment by MissAllSunday** [comment] 2014-07-12 15:06
Not really a fan of adding a scroll in the middle of a page.

**Comment by live627** [comment] 2014-07-12 23:27
w/e

**Comment by live627** [comment] 2014-07-13 01:04
A scroll bar would fix

> this could lead to some confusion since the total amount of unread alerts is still added to the alerts button.

**Comment by MissAllSunday** [comment] 2014-07-13 14:31
And  it will create more issues:
- Most Android devices cannot scroll the content at all.
- On mobile devices there is no scroll indicator which will create an even bigger confusion.
- Scrollable divs are a pain to maintain crossbrowser wise.
- You're leaving themers with no other options.

Those are the reasons I'm not really a fan of adding a scroll overthere.

**Comment by XinYenFon** [comment] 2014-07-13 14:52
That cap should be 5 not 10.

**Comment by Oldiesmann** [comment] 2014-07-13 16:59
I think limiting it to 10 with no additional explanation will be fine. That's how IPB does it (one of the forums I frequent is IPB powered) - shows 10 notifications with "show all notifications" and "options" links at the top.

**Comment by XinYenFon** [comment] 2014-07-13 17:09
I suggested 5 because of small screen mobile phones.

**Comment by MissAllSunday** [comment] 2014-07-13 17:34
Does IPB shows the total amount of unread alerts?  thats the main issue, we are showing that number and it can be confusing to users to see a number and then only see a different amount of alerts been displayed.

My proposal change is quite simple, show a "showing latest 10" where the "All alerts" link currently is and move the "All alerts" link to the button of the displayed alerts.

As for 5 vs 10, we can check the browser and display 5 if its a mobile device or something.

**Comment by Oldiesmann** [comment] 2014-07-15 15:50
Yes, IPB does display the total number of unread alerts. One time recently I had 14 of them and it only showed the 10 most recent. I had to click on "View All Notifications" to see the other four.

**Comment by Dragooon** [comment] 2014-07-17 14:50
Limit it to 10 with an additional notice at the bottom to saying "Show rest of the unread alerts"

**Comment by illori** [comment] 2014-07-17 15:30
sounds good to me.

**Comment by Oldiesmann** [comment] 2014-07-17 17:01
Why do we need a "show the rest of the unread alerts" notice? We've already got a link you can click to view all alerts.

**Comment by Dragooon** [comment] 2014-07-17 17:02
Because otherwise it's not instantly obvious that there are more unread
notifications

**Comment by Oldiesmann** [comment] 2014-07-17 17:07
That's why we have something indicating how many alerts they have...

**Comment by Dragooon** [comment] 2014-07-17 17:08
And what are the chances having more unread notifications than what is
shown automatically makes sense?

**Comment by Oldiesmann** [comment] 2014-07-17 17:13
We don't need two links that go to the exact same spot. If users can't count, having an extra link isn't going to help.

**Comment by Dragooon** [comment] 2014-07-17 17:14
It would explain an odd behaviour, we can also move the view alerts link to
bottom and say that.

**Comment by Oldiesmann** [comment] 2014-07-18 14:39
A few of us started playing around with this yesterday and decided that a scrollable div would probably work best. The only issue is of course the fact that Android won't show scrollbars, so we need to figure out how to get around that. The "tinyscrollbar" plugin for jQuery is one option (I viewed their demos on my phone and the scrollbar does show there), though I'm not sure how easy it would be to implement as their demos have a main div, a bunch of empty divs for various scrollbar elements and then the div holding the content. This means we'd have to apply it to the main alerts div (obviously something we don't want to do), add yet another div to hold the div that holds all the alerts, or find a way to tweak the CSS for that one and hope it works the way we want it to.

**Comment by live627** [comment] 2014-07-19 01:45
https://github.com/mzubala/jquery-custom-scrollbar

**Comment by MissAllSunday** [comment] 2014-07-19 13:48
It would be good for us not to start depending on jquery for everything, specially for simple UI things that can be done in a much more simpler way.

Jquery is a tool, not a dependency.

**Comment by Oldiesmann** [comment] 2014-07-19 14:34
What solution would you propose? No matter what solution has been brought up so far, there's always something that someone doesn't like about it.

A scrollable div showing 5 notifications at once works quite well, especially on mobile devices. The only issue is making it obvious that the area can be scrolled on Android (and possibly other mobile platforms) where scrollbars aren't shown by default until you actually tap/click in the area. A jQuery scrollbar plugin would solve that issue and also give us consistency across all platforms.

**Comment by MissAllSunday** [comment] 2014-07-19 15:06
Like I said, scrollable divs patches some issues but brings up a few other ones. Thus, you end up with the same of even more number of issues, you're just changing places.

A jquery plugin will indeed solve the issue but you will end up depending on jquery to solve everything for you, which is simple not good.

Forums running on crappy servers or with too many jquery plugins will show the entire list of alerts until the DOM is ready.  Even the basic demo of the linked plugin above shows a 1 second delay before the plugin gets applied, on that delay the page looks fugly and makes you think theres something wrong with that page.

It might look good and work good on local instalations or vanilla forums but production sites is an entirely different beast, way too many things can broke the scrollable plugin and thus, will break the UI. Way too many things will delay the plugin execution too.

I'm in favor of using js to enhace the user experience but I'm also againts using js as solution for every UI problem we might have.

Even if you insists on using a scrollable plugin, we still need a cap, we can't show fifty or a hundred unseen alerts. Even showing twenty sounds pretty crazy.

What I propose is simple, keep a 10 cap, move the "show all alerts" at the botton. Thats all.

**Comment by Arantor** [comment] 2014-07-19 18:39
> Forums running on crappy servers or with too many jquery plugins will show the entire list of alerts until the DOM is ready.

Why? Did you guys rewrite that code so it wasn't done off the back of an AJAX poll in the first place? (meaning the JS should already be available _before_ the DOM even gets those elements)

**Comment by live627** [comment] 2014-07-19 22:11
> It would be good for us not to start depending on jquery for everything, specially for simple UI things that can be done in a much more simpler way.
> 
> Jquery is a tool, not a dependency.

What... the fuck. Did I really read this? Tell me I'm not hallucinating.

**Comment by Arantor** [comment] 2014-07-20 12:50
You're not hallucinating.

**Comment by MissAllSunday** [comment] 2014-07-20 13:20
I made my proposes and stated the flaws on the other ones, @Oldiesmann your call, call it and lets move on.

**Comment by illori** [comment] 2014-07-22 18:19
seems fixed on desktop browser, on chrome on android the drop down is not showing full size, it is not even big enough to show the all alerts area

**Comment by illori** [comment] 2014-07-22 18:28
desktop chrome has the same issue.

**Comment by Oldiesmann** [comment] 2014-07-22 18:38
Also, the goal (at least for me) was to make it so that just the list of alerts was scrollable, not the entire box.

**Comment by live627** [comment] 2014-07-22 20:30
Seems that Chrome cannot read max-height values.

http://stackoverflow.com/questions/9448234/chrome-mis-reading-max-height-and-max-width

**Comment by illori** [comment] 2014-07-22 20:32
the user replied there that they had zoom set and that caused the issue.

**Comment by live627** [comment] 2014-07-22 20:35
Yeah I checked. It was at 100% the default for me.

**Comment by illori** [comment] 2014-07-22 20:37
it was for me too. i dont think our issue is the same as that link you found.

**Comment by live627** [comment] 2014-07-22 22:36
I merged in a fix for this, now works on both IE and Chrome. I guess it pays to test outside of Firefox.

**Comment by illori** [comment] 2014-07-23 10:07
confirmed it seems fixed. i would just make the drop down a little smaller, it shows a hint of the next alert where IMO it should end cleanly at the bottom of the last alert we want to show.

**Comment by Oldiesmann** [comment] 2014-07-23 16:28
We had actually worked out how tall to make it for 5 alerts, but I don't remember exactly what that height was. 255px maybe?

**Comment by illori** [comment] 2014-07-23 16:34
360 px should do the trick including the all alerts header area

**Comment by Dragooon** [comment] 2014-08-15 18:05
Eh...why is this open? @Oldiesmann @MissAllSunday?

**Comment by NanoSector** [comment] 2014-09-07 14:28
This is fixed AFAICS, http://i.imgur.com/5cVrOAr.png

**Comment by Dragooon** [comment] 2014-09-07 14:29
Closing for now, if it isn't fixed let me know.

**Closed as completed** 2014-09-07 14:29 UTC
Labels: Notifications
