### ISSUE TITLE
Quote Selected Text bug(s)

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#7103] opened 2021-09-30 14:48 UTC
#### Description
Using the "Quote Selected Text" feature has a few inconsistencies and/or bugs
This affects both Quick Reply and normal reply.

### Steps to reproduce
Issue 1
1. triple click a word in a line of text in a post
2. first click puts the attention on the location, second click selects the single word, third click selects the entire line
3. with the line selected, click the Quote Selected Text button
4. Text is added into the reply (or quick reply) box -- but text includes the selected line PLUS a separate quote of the single word...
5. This is repeatable across multiple sites.

Issue 2
1. if you select text, but the area where the "QST" button would appear is not visible on the screen, sometimes, the QST button never appears
2.  This is intermittent. I have only seen it a few times but am not sure what the trigger for appear vs not appear is.

Issu3
1. If you select the text to be quoted from the left-top and select down - QST button appears.
2. If you select the text to be quoted from the bottom-right and select upwards - QST button does not appear

### Environment (complete as necessary)
- 2.1 RC4 released version
- mySQL
- 7.4

### Additional information/references

**Comment by Sesquipedalian** [comment] 2021-09-30 15:10
The first part of this appears to be a duplicate of #6960. The other two parts appear to be new.

**Comment by Kindred-999** [comment] 2021-09-30 16:07
AH, I missed that previous....   So, PR https://github.com/SimpleMachines/SMF2.1/pull/7009 should fix that first issue and was applied to the github code at the end of August. Excellent. 

Issues 2 is odd and not consistently reproducible.

Issue 3 is odd.... but not a high priority, IMO.

**Comment by BrickOzp** [comment] 2021-10-01 05:38
For issue 3.
Do you only select text from the message?
If you select anything outside the message, for example signature och quote buttons the QST won't be triggered

**Comment by WhistlingDonkey** [comment] 2021-10-01 14:16
I can make issue 3 happen in both directions. It seems to be dependent on how fast you do the the select, so selecting lightning fast in either direction it's a hit or miss whether the QST button is shown, and selecting slower in either direction you get the QST button, so I can confirm, that at least for me that the QST button does show when selecting backwards, but it appears that you have to be quite deliberate on how long you take between holding in and releasing the mouse button.

I think issue 2 may be related to the above, as the QST button always shows, even when it's offscreen when you click-select instead of drag-select.

**Comment by live627** [comment] 2021-10-13 23:36
This seems to be a side effect of ensuring that only a single message gets selected.

https://github.com/SimpleMachines/SMF2.1/blob/1989d5def91732ed96bf13d0cb73c84fe57e8b22/Themes/default/scripts/quotedText.js#L47-L54

**Comment by Sesquipedalian** [comment] 2021-10-14 20:29
When trying to reproduce these issues, I did not find that the speed of my mouse movement made any difference in and of itself. Instead, I found this:

Works:
<img width="535" alt="Screen Shot 2021-10-14 at 2 22 01 PM" src="https://user-images.githubusercontent.com/191731/137389863-9600bc04-546b-453f-b4d9-1529de7328de.png">

Doesn't work:
<img width="532" alt="Screen Shot 2021-10-14 at 2 22 17 PM" src="https://user-images.githubusercontent.com/191731/137389934-31c4705f-4a8b-4b48-a14f-10fc37eb8c01.png">

The latter doesn't work because the end of the selection has gone outside of the .inner div and includes the whitespace in the .post div.

When dragging the mouse quickly, it would be easy to overshoot the end of the text and wind up outside of the .inner div. Likewise, if dragging upwards from the bottom right, it would also be easy to start outside of the .inner div.

For those of you who were able to reproduce these issues, do my findings accurately describe what you are seeing in your tests, or is something else going on?

**Comment by WhistlingDonkey** [comment] 2021-10-15 09:11
I believe you are correct Sesquipedalian, the speed of the mouse is not a part of it, where the mouse starts and finishes is and is why I had hit and miss results using the speed of the mouse as the theory. After your post I tested further and this is what I found. Note, my original and latest tests were not a solid block like your test but 12 separate lines, ie Line 1, Line 2, Line 3 etc and originally deliberately didn't select past the top or bottom of the post.

There is a gap of 15px between the .poster and .postarea div's. You can start your selection in this area but you can't finish the selection in this area. So if you start the selection in this 15px gap (which belongs to post_area div) and finish the selection in the post then QST shows; if you start the selection in the post (or in the 15px gap) and finish the selection in the 15px gap QST doesn't show.

So, using my 12 separate lines as the example (line numbers arbitrary for the test):
`Selecting down`
Start selection more than 2 pixels to the left of Line 2 (normal mouse pointer), end the selection to the right of Line 8 QST shows.
Start selection to the right of Line 2, end the selection several pixels to the left of Line 8 QST doesn't show.

`Selecting up`
Start selection to the right of Line 10, end the selection just to the left of Line 3 (select text mouse pointer) QST shows.
Start selection to the right of Line 10, end the selection several pixels to the left of Line 3 (normal mouse pointer) QST doesn't show.

**Comment by Sesquipedalian** [comment] 2022-02-26 20:56
Part one of this was a duplicate and has already been fixed.

I cannot reproduce part two.

Part three isn't really a bug, and it isn't something we can do anything about anyway. If the user selection spills outside the post body, the JavaScript for the Quote Selected Text button can't do anything with that.

**Closed as completed by Sesquipedalian** 2022-02-26 20:56 UTC
Labels: Posting
