### ISSUE TITLE
can not issue warning

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#529] opened 2013-07-26 12:36 UTC
![Alt Text](http://imageshack.us/a/img802/6151/ek7c.png)

apparently when i issue a warning without sending a message i get an error that i need to send the user a message but it is not required when issuing a warning

antes tried to duplicate but was unable

**Comment by illori** [comment] 2013-07-26 12:56
after this issue, sending a warning with the message and now i can send warnings normally without sending a message

seems the preview box got stuck showing somehow.

but the message shown for not filling in the subject or body needs a bit of work. it should not say null

**Comment by jdarwood007** [comment] 2013-07-30 03:19
Works for me as intended.  I can't reproduce this at all.  As soon as I uncheck the option to send a warning the preview option goes away and clicking issue still submits it.  Although the bottom part with previous warnings needs a template adjustment it appears.

**Comment by illori** [comment] 2013-07-30 09:27
it does not happen all the time, but it does happen on my localhost install.

seems to happen when i press enter after typing in the reason for warning. if i click the issue warning button it does not have the problem

**Comment by XinYenFon** [comment] 2013-07-30 09:57
this is happening when you left empty or fill the reason place and hit enter (on keyboard). No issue i saw from the button.

**Comment by illori** [comment] 2013-07-30 10:00
looking at the page source the preview_button still shows... it is just display: none, i bet when you press enter it is hitting the preview button instead of the issue warning button

**Comment by jdarwood007** [comment] 2013-07-31 03:42
Which browser are you testing?  Using Chrome I can't reproduce this.
1. View user profile and select Issue Warning (i.e. Whipping Boy)
2. Change warning level (i.e. 20)
3. Enter a reason (i.e. Test)
4. Hit enter key

This could be resolved possibly by instead of using display: none, we set disabled="disabled" (or just disabled for html5).

**Comment by illori** [comment] 2013-07-31 09:23
firefox 22

**Comment by Oldiesmann** [comment] 2013-08-27 19:27
Same thing happens on my test board in Firefox 23. Hiding it and disabling it should fix the issue, though it's more of a bug with Firefox trying to "click" on things that aren't displayed.

**Comment by Arantor** [comment] 2014-01-16 23:27
Cannot reproduce with Chrome 32 or Firefox 26. Going to close this now, and we'll reopen it if it can be reproduced.

**Comment by illori** [comment] 2014-01-17 00:07
i can still duplicate in ff 26, give a user as warning enter the text and hit enter. please reopen.

**Comment by Arantor** [comment] 2014-01-17 00:18
Oh I see what the problem is now. Wasn't clear from the original report that you absolutely had to tab+enter (as opposed to just enter or pressing buttons)

**Comment by illori** [comment] 2014-01-17 00:19
i did not tab+enter, i just put the warning percentage clicked in the reason box put in the message and hit enter

**Closed as completed** 2014-01-17 00:33 UTC
