### ISSUE TITLE
Export dir get created in wrong way/path

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#6841] opened 2021-07-14 11:59 UTC
#### Description
Dunno which step the export dir get generated,
but my file path look like this now:
![grafik](https://user-images.githubusercontent.com/1782906/125618206-4e5f8b34-9825-4b76-abe7-c07b7c2fc697.png)
![grafik](https://user-images.githubusercontent.com/1782906/125618256-bf618bb1-17dd-40d3-abe1-ac9da315478c.png)

### Environment (complete as necessary)
- Version/Git revision: head
- Database Type: postgresql
- Database Version: 12
- PHP Version: 7.3.12

**Comment by Sesquipedalian** [comment] 2021-07-14 15:33
I'll take a look.

**Comment by Sesquipedalian** [comment] 2021-07-14 15:54
What do you currently see in the "Directory for profile data export files" setting in Administration Center ►  Server Settings ►  Data Export?

**Comment by albertlast** [comment] 2021-07-14 16:17
![grafik](https://user-images.githubusercontent.com/1782906/125656530-068c3b96-3ea3-4fa6-8061-9c3db3a5b001.png)

**Comment by Sesquipedalian** [comment] 2021-07-14 17:18
Well, I don't know how you got that string into your settings, but that's the problem. The `create_export_dir()` function simply created the path that it was told to create.

If you know a reproducible way to cause `{$boarddir}` to appear in that setting, that'd be a bug to investigate for sure.

**Comment by sbulen** [comment] 2021-07-14 17:18
This is fallout from:
https://github.com/SimpleMachines/SMF2.1/pull/6255/files

Which went in as part of the 9.6 changes.

There was a tweak needed here:
https://github.com/SimpleMachines/SMF2.1/pull/6802/files

I suggest going back to the initial simple inserts.....

**Comment by sbulen** [comment] 2021-07-14 17:19
I think it needs to be re-opened due to the note above.

We should go back to the simple inserts when a placeholder like {boardurl} is involved, OR, make it honor the placeholders on groups of inserts since it doesn't appear to be doing so.

**Comment by Sesquipedalian** [comment] 2021-07-14 17:20
Just did. We appear to be posting simultaneously. ;)

**Comment by Sesquipedalian** [comment] 2021-07-14 17:23
Can I reassign this to one or both of you, @sbulen and @albertlast? You two have the most experience with the code affected in #6255 and #6802.

**Comment by sbulen** [comment] 2021-07-14 17:26
I'll take it & restore to the initial code.

**Comment by sbulen** [comment] 2021-07-14 17:37
The above must be happening only on pg for some reason.  The variable is created properly in mysql with the latest code.  I had tested it earlier, but not in pg...
![image](https://user-images.githubusercontent.com/23568484/125667111-7e412bb2-87bf-4674-9556-17d41d74b994.png)

![image](https://user-images.githubusercontent.com/23568484/125667485-20fee247-dfad-4392-a066-412e3900ebee.png)

**Comment by sbulen** [comment] 2021-07-15 02:56
Actually, the issue does occur in mysql.  PR tested & on the way.

**Closed as completed** 2021-07-23 00:06 UTC
Labels: Exports
