### ISSUE TITLE
alerts topic link problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#5533] opened 2019-03-22 12:30 UTC
#### Description
hi,

alerts link "msgxxxx" at the end of the link

creating a direct topic link

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by live627** [comment] 2019-04-02 14:14
Possible duplicate of #5408

**Closed as completed** 2019-04-03 14:37 UTC
Labels: Notifications
