### ISSUE TITLE
Encoded characters in Custom Profile Fields

### ISSUE THREAD

**Issue by Kindred-999** [SimpleMachines/SMF#2575] opened 2014-12-06 14:34 UTC
http://test2.turtleshellprod.com/index.php?action=profile;area=account;u=19

`Oh YAY! It's a blurb!`
   gets saved (and then displayed) as 
`Oh YAY! It&#39;s a blurb!`

Admin edit - same result

Edited MY OWN profile

---

`this is a test blurb. 
"I'm not sure what to make of it", she said
!?@&$)(;:/-1234567890`

---

this SAVES and displays (in the textbox) correctly)
In the profile summary page, though

---

`this is a test blurb.
&quot;I&#39;m not sure what to make of it&quot;, she said
!?@&amp;$)(;:/-1234567890`

---

Custom Profile Field
Show in account settings
display above signature
require during registration
Large Text
Max 255 characters
4 rows 30 columns
users can see, owner can edit
searchable

**Comment by illori** [comment] 2014-12-06 16:12
duplicate of #1755

**Closed as completed** 2014-12-06 18:36 UTC

**Comment by Kindred-999** [comment] 2014-12-07 01:20
I will note -- although it may have been the same or similar to #1755 -- that one was noted as having been fixed - so something reintroduced the issue

I do see a commit related the this so - excellent.  I'll install a new version once it has the 2FA back in the main trunk.

**Comment by Dragooon** [comment] 2014-12-07 04:33
@Kindred-999 2FA has been merged in the main SMF branch, feel free to try it
