### ISSUE TITLE
Cookie will be not destroy when the board move to subfolder

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4366] opened 2017-10-20 20:09 UTC
When you got local cookie and change the board from exp. /smf to /smf/test
the cookie get lost smf is not able to delete/destroy the cookie
This issue is reintroduce by  https://github.com/SimpleMachines/SMF2.1/pull/4363

**Comment by sbulen** [comment] 2017-10-20 22:03
This is a dupe of #4297

**Comment by albertlast** [comment] 2017-10-20 22:11
Nope this issue the not mention,
The base of this issue is the missing path info in data.


________________________________
Von: Jon Stovell <notifications@github.com>
Gesendet: 21.10.2017 12:04 vorm.
An: SimpleMachines/SMF2.1
Cc: albertlast; Author
Betreff: Re: [SimpleMachines/SMF2.1] Cookie will be not destroy when the board move to subfolder (#4366)


Closed #4366<https://github.com/SimpleMachines/SMF2.1/issues/4366>.

**Comment by albertlast** [comment] 2017-10-21 19:01
i checked the pr from sbulen and he didn't fix the issue.

**Comment by sbulen** [comment] 2017-10-24 05:44
Note a correction: this issue is not a dupe of #4297.

**Comment by jdarwood007** [comment] 2017-10-24 16:00
By board you mean forum I assume?

**Comment by albertlast** [comment] 2017-10-24 16:03
Sure,
Like i already mention,
the issue for this is the missing information of the path from the cookie (which was already fixed in my pr)

**Comment by sbulen** [comment] 2017-10-29 22:16
My problem with this issue is that I think it ends up defeating the purpose of the localCookie setting.

Local cookies are intended to allow support for different forums in different subfolders.  I.e., each forum is in a unique subfolder and there is a corresponding cookie.  If you make cookie behavior independent of the subfolder, you have essentially disabled localCookies, i.e., they are now global.  

The online help indicates that keeping the subfolders distinct is important for some ISPs that are organized in that way.  You do not want the forum software or cookie operating outside of its scope.  

If you *DO* want it to use the cookie for the whole structure, independent of the subfolders, then you should de-select Local Cookies.

**Comment by albertlast** [comment] 2017-10-30 04:56
The behavior of the localcookies didn't change,
so your comment make no sense.

**Closed as completed** 2018-01-14 08:55 UTC
Labels: Cookies
