### ISSUE TITLE
0004364: URLs with brackets not supported

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1514] opened 2014-04-11 07:58 UTC
[url=http://www.tttth.com/[alt-coin-talk/]Talk[/url] > Works ok
[url=http://"http://www.tttth.com/ablt-co]-tak"]Talk[/url] > Works as closure tag and breaks the link.

I think we can fix this issue with changing systematic [url=] to [url=""]

**Comment by MissAllSunday** [comment] 2014-04-11 13:23
Duplicate of https://github.com/SimpleMachines/SMF2.1/issues/1187

**Closed as completed by MissAllSunday** 2014-04-11 13:23 UTC
