### ISSUE TITLE
Setting the time on the entire forum

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#5309] opened 2019-01-01 20:25 UTC
In Admin > Configuration > Features and Options > Server timezone is automatically set the correct time server for my country, but despite this, the clock in the forum incorrectly indicates the time. The clock shows the hour backwards. In SMF 2.0, after setting the time server, the correct time is automatically set on the entire forum. Why is it different in 2.1? Why do I have to make the second setting in Look and Layout > Time zone > (Forum Default) so that the time in the entire forum is correct? After all, the main time setting is in the admin panel as in version 2.0, so why are two settings needed?

SMF 2.1 RC1

**Comment by Sesquipedalian** [comment] 2019-01-01 21:23
What do you mean by "The clock shows the hour backwards"?

**Comment by Sesquipedalian** [comment] 2019-01-01 21:29
> Why do I have to make the second setting in Look and Layout > Time zone > (Forum Default) so that the time in the entire forum is correct?

That controls the time zone for _a specific user_. If you have a user in London and another in Sao Paulo, this setting allows them each to see timestamps in their own local time.

In contrast, the admin panel setting is for telling SMF what time zone _your server_ is in. 

These are two different settings because they refer to two different things. If you happen to be in the same time zone as your server, that's merely coincidence.

**Comment by LexArma** [comment] 2019-01-02 07:53
If I get this right, nothing has actually changed from 2.0. Even in 2.0 we had a forum wide setting in the admin control panel, and a user specific setting in profile settings.

**Comment by Arantor** [comment] 2019-01-02 21:21
It has changed, though. 2.1 can actually do it properly by ditching the hours offset and instead using time zones to calculate difference from server time.

**Comment by jsqx** [comment] 2019-01-02 21:39
**Little correction:** In Admin > Configuration > Features and Options > Server timezone is automatically set the correct time server for my country and the time in the entire forum is displayed correctly. But if I sign in, the time is not displayed correctly, an earlier hour is shown. Example: 5 pm (the correct time on the entire forum). After sign in: 4 pm (incorrect time). So why in SMF 2.1 the main function of setting time (Server timezone) on the entire forum is no longer the main function? Why me (admin) and every other user must set the time manually for own account in Look and Layout > Time zone > (Forum Default)? Not all users have the concept to manually set the correct time for their account. There is one time setting for the entire forum and all users in SMF 2.0, and this is correct.

**Comment by smfbigguy** [comment] 2019-01-02 23:19
All users will most likely not live in the same time zone. This is probably why each users has his own setting.

**Comment by Sesquipedalian** [comment] 2019-01-03 00:59
Exactly, @smfbigguy.

Since "The clock shows the hour backwards" doesn't seem to refer to anything in particular, I am closing this as not a bug.

**Closed as completed by Sesquipedalian** 2019-01-03 00:59 UTC
Labels: Won't fix / Not a bug

**Comment by LexArma** [comment] 2019-01-03 06:43
> There is one time setting for the entire forum and all users in SMF 2.0, and this is correct.

Just to reiterate, no - there are 2 for 2.0 as well. In the same places. And they work similarly to what is in 2.1. The only thing that has changed as far as I can tell, is how the time differences are handled in code.

**Comment by jsqx** [comment] 2019-01-03 09:42
> All users will most likely not live in the same time zone. This is probably why each users has his own setting.

I understand what you all mean. All users on my forum live in the same time zone. So look at it from this side, that not everyone runs an international forum. So add the time zone function during registration so that every user can choose the right time. The IP.Board software has such a function in registration. This is good solution.

**Comment by LexArma** [comment] 2019-01-03 09:50
You can do that yourself. Admin -> Configuration -> Profile Fields.
Select Timezone to be shown on registration.

**Comment by jsqx** [comment] 2019-01-03 10:42
Thank you for the information. But a small correction in this function would be useful. To be automatically set the default time for the forum in this selection list, which is set for the entire forum in the server's time zone. Look at the fact that IP.Board and MyBB has an automatically set time zone on such a list for the entire forum. And every new registrant can choose his own time zone. Where can I suggest such a suggestion?

IP.Board:

https://i.imgur.com/BvR7Eke.png

MyBB:

https://i.imgur.com/mMpsWE9.png

**Comment by LexArma** [comment] 2019-01-03 11:24
That is how it should work. The default if not selectable, and the preselected option if selectable is "(Forum default)" and unless you change it, that should stick.

**Comment by jsqx** [comment] 2019-01-03 19:10
So every new registered user after logging in has the correct time on the forum. No need to set the time zone selection during registration. And it's fine. But there is one small mistake, after installing the new forum 2.1 as admin I have an incorrect time after logging in to my account. It should not be like that. Let anybody fix this mistake.

**Comment by Arantor** [comment] 2019-01-03 19:53
Well, fix it in your profile... it’s no different to how you can’t set your avatar or signature during installation (and no, that should not be an option)

**Comment by LexArma** [comment] 2019-01-03 20:20
Just tested this with a beta 3 install I had lying around to be sure, and if the server timezone (and possible offset) are correctly set, it doesn't matter for any new user (except the original admin perhaps, because he is registered before the settings can be changed) if you accept the default value SMF gives you during registration, or manually select the same timezone - your clock will be on the right time.  So what exactly is the issue?

**Comment by jsqx** [comment] 2019-01-05 10:13
> (except the original admin perhaps, because he is registered before the settings can be changed).

Cool, I can set the time manually in the profile, but it is strange that you do not care about such a solution.

**Comment by jsqx** [comment] 2019-01-05 10:16
> (except the original admin perhaps, because he is registered before the settings can be changed). if you accept the default value SMF gives you during registration.

In 2.0, I also accepted the default value during registration, except that after setting up an administrator account, the time is correct. Cool, I can set the time manually in the profile, but it is strange that you do not care about such a solution.

**Comment by LexArma** [comment] 2019-01-05 10:24
If I had to guess, you have set your server timezone  incorrectly.

**Comment by Arantor** [comment] 2019-01-05 11:10
I’ve never seen an SMF of any version install with the correct time for me because the servers were never in my time zone...

Heck, even my local is wrong half the year due to DST.

**Comment by jsqx** [comment] 2019-01-05 16:57
> If I had to guess, you have set your server timezone incorrectly.

In Installer 2.1, it is not possible to set the server's time zone.

**Comment by Sesquipedalian** [comment] 2019-01-05 19:40
> In Installer 2.1, it is not possible to set the server's time zone.

Setting the server's internal clock is not possible from a PHP script. You need administrator privileges to adjust system settings like that, and you certainly would not want a PHP script to have that kind of access even if it were possible.

The installer does, however, automatically retrieve and use the time zone that the server is configured for. You can see the code that does this here:
https://github.com/SimpleMachines/SMF2.1/blob/4a751c639634055c63dc8440b4963331577024b1/other/install.php#L1344-L1363
As you can see, if the retrieved time zone is incorrect, that's because your server doesn't have the correct value for `date.timezone` set in its PHP configuration.
