### ISSUE TITLE
[3.0]: Type of SMF\Actions\Post2::$obj must be SMF\Actions\Post

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#8044] opened 2024-01-25 09:57 UTC
### Basic Information

![sshot-15](https://github.com/SimpleMachines/SMF/assets/229402/06779bfb-2937-42d1-b89c-f715263103c6)

### Steps to reproduce

1. Try to post a new topic

### Version/Git revision

3.0 Alpha 1

### Database Engine

MySQL

### Database Version

MariaDB-10.6.11

### PHP Version

8.0.30

### Additional Information

Post2.php, replace `protected static self $obj;` with `protected static Post $obj;`, or with `protected static parent $obj;`

**Comment by jdarwood007** [comment] 2024-01-26 00:46
I can't reproduce this error.  Is anyone else able to?

**Comment by Oldiesmann** [comment] 2024-01-27 19:01
I can't reproduce this on my test board either.

**Comment by dragomano** [comment] 2024-01-29 09:27
For me, this issue occurs only on PHP 8.0.30. There is no problem with PHP 8.1+

**Comment by DiegoAndresCortes** [comment] 2024-01-29 17:31
I can reproduce on PHP 8.0.30

**Comment by DiegoAndresCortes** [comment] 2024-01-29 18:07
I get pretty much the same issue in action=login
`Type of SMF\Actions\Login::$obj must be SMF\Actions\Login2 (as in class SMF\Actions\Login2) in \Sources\Actions\Login.php on line 28`

**Comment by dragomano** [comment] 2024-01-29 18:11
Confirm, I didn't notice it, because I didn't log out of the forum after installation :)

Post2: `protected static Post|Post2 $obj;`
Login: `protected static Login2|Login $obj;`
Logout: `protected static Login2|Logout $obj;`

**Comment by jdarwood007** [comment] 2024-01-29 22:41
Odd, I switched over to 8.0.30 and it works still.  Must be something more.

**Comment by jdarwood007** [comment] 2024-01-29 22:44
Are you guys on Windows?  Using a WAMP-type setup?  Using Apache with mod_php or something?
Trying to see what variable I am missing to produce this.

**Comment by dragomano** [comment] 2024-01-30 05:03
Windows 11, [PHP 8.0.30](https://windows.php.net/downloads/releases/php-8.0.30-Win32-vs16-x64.zip)

**Comment by DiegoAndresCortes** [comment] 2024-01-30 15:50
Same here

**Comment by jdarwood007** [comment] 2024-01-31 00:35
@ Sesquipedalian I would like your opinion here.  Looks like PHP 8.0 on Windows does not handle extending the class concerning `self` under `$obj`.  PHP 8.0 is already EOL and Windows usage is fairly low I suspect.
We seem to have two options

1. Fix the code as suggested above, removing reference to self in the base class and using the unions of the base and extended classes.
2. Do not support PHP 8.0 on Windows.

I'm debating this, because do we want to do a fix for this that affects a very small (maybe non-existent) under of installations?

**Comment by dragomano** [comment] 2024-01-31 04:24
One more reason to increase the minimum PHP version :)

**Comment by Sesquipedalian** [comment] 2024-01-31 06:37
The best solution is to set the type for all `$obj` properties to the class name (or the name of the extended class, if applicable). I will submit a PR shortly.

**Closed as completed** 2024-01-31 07:46 UTC
Labels: PHP version support
