### ISSUE TITLE
[i18n] Translate strings on translatewiki.net (MediaWiki Translate extension)

### ISSUE THREAD

**Issue by nemobis** [SimpleMachines/SMF#2641] opened 2015-01-02 09:43 UTC
In comparing [phpBB](http://trends.builtwith.com/cms/phpBB) to [SMF](http://trends.builtwith.com/cms/SMF), I noticed that part of SMF's success is in its being more used internationally (look at the southern emisphere countries). Indeed, SMF has more locales than phpBB, with around 50 language packs; but we could do better, e.g. MediaWiki has over 350.

I propose that the translation be [moved to translatewiki.net](https://translatewiki.net/wiki/Translating:New_project) to try to have as many locales as MediaWiki.
- I've checked the [rules](http://www.simplemachines.org/about/smf/translateagreement.php) and they're not problematic.
- The l10n files are just huge PHP arrays. MediaWiki used this format till few months ago, so it could be supported. That said, you probably want to switch to JSON format (or [another](https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Extension:Translate/File_format_support)) at some point, as [MediaWiki did](https://www.mediawiki.org/wiki/Localisation_file_format).
- The files themselves should be hosted in a repository here on GitHub if they aren't yet (that's easy, isn't it?). The rest would stay the same.

You already have [Translate](https://www.mediawiki.org/wiki/Help:Extension:Translate) on your own wiki, though [not used much](http://wiki.simplemachines.org/smf/index.php?title=Special%3ALog&type=pagetranslation), so you can try it there and if you wanted you could also self-host the translation. However, TWN has just [discontinued Shapado](https://translatewiki.net/wiki/Translating:Shapado), so there may be some translators looking for "forum" work. :)

**Comment by illori** [comment] 2015-01-02 10:17
at this time i dont see the team changing from what they are doing. also this is not a bug in SMF it is a suggestion. this really should be discussed on the forum where you are sure to get input from the loc team.

**Comment by XinYenFon** [comment] 2015-01-02 11:12
I also have to mention, SMF has its own Language Editor (apart from software). Software translations are done via it with some perks.

**Comment by nemobis** [comment] 2015-01-04 10:48
Sure, it's a suggestion/enhancement request. I want to understand 
technical requirements first.

Mert Alınbay, 02/01/2015 12:12:

> I also have to mention, SMF has its own Language Editor (apart from
> software). Software translations are done via it with some perks.

Interesting. Where should I read more about this language editor? I'd 
like to add it to our draft [feature 
comparison](https://docs.google.com/spreadsheet/ccc?key=0AvdoxmL5NpHydFFKMXJVZ1B0ZnpsUWd3LTVQRngtcmc).

**Comment by illori** [comment] 2015-01-04 11:30
the language editor is not available to the general public [source code etc], it is used by those given access to translate SMF and that is all that gets access to it.

**Comment by nemobis** [comment] 2015-01-04 11:38
Illori, 04/01/2015 12:30:

> the language editor is not available to the general public [source code
> etc], it is used by those given access to translate SMF and that is all
> that gets access to it.

Ok. So is there a way for me to know/read what features it offers? :)

**Comment by illori** [comment] 2015-01-04 11:40
no. really if you want to discuss this, it should be on the forum. this is an issue related to the localization team not the dev team. this is the wrong place for this if you want input from those involved in the decision making related to this.

**Comment by Kindred-999** [comment] 2015-01-06 17:07
Devs --  This can be closed as rejected. We will not be using external tools like this which do not suit our style or needs.

**Closed as completed** 2015-01-06 17:18 UTC
Labels: New feature, Localization
