### ISSUE TITLE
Database error on exporting personal messages

### ISSUE THREAD

**Issue by dragomano** [SimpleMachines/SMF#6441] opened 2021-01-08 15:48 UTC
#### Description
Database error: 'pm2.from_name' isn't in GROUP BY
File: News.php
Line: 2593
URL of the page causing the error: cron.php

### Steps to reproduce
1. Start to export personal messages
![2021-01-08 20_40_42-Download profile data — Firefox Developer Edition](https://user-images.githubusercontent.com/229402/104034128-4d8db480-51f2-11eb-9789-f97b585b5fbd.png)

### Environment (complete as necessary)
- Version/Git revision: 4ba5dd2
- Database Type: MariaDB
- Database Version: 10.5.6
- PHP Version: 7.4

**Comment by albertlast** [comment] 2021-01-08 15:50
it's not a database error in general, it's a marriadb issue.

**Comment by sbulen** [comment] 2021-01-08 16:06
Dupe of #6309

**Closed as completed** 2021-01-08 16:15 UTC
