### ISSUE TITLE
Skype icon not shown on poster information

### ISSUE THREAD

**Issue by frandominguezl** [SimpleMachines/SMF#3909] opened 2017-02-01 19:20 UTC
After entering an username in the skype field (Profile > Forum Profile), the icon is not shown on the poster information

**Comment by frandominguezl** [comment] 2017-02-02 18:13
Alright, so, dumb of me I just changed the placement in "Bottom poster info". Now, the curious thing is that after saving that, on bottom poster info there's also displayed Gender even though is not set to be placed there...

![](https://i.gyazo.com/2c0d5382acc88df9d1f6a7c661d820fe.png)


![](https://i.gyazo.com/a695f489ffe9909922c5112e4621637a.png)

**Comment by Oldiesmann** [comment] 2017-02-02 18:23
Gender is shown "with icons" as it should be. "Bottom Poster Info" shows things below all of the other poster info (icons, location, IP, etc.).

**Comment by frandominguezl** [comment] 2017-02-02 18:28
Before changing skype to "Bottom Poster Info", Gender was not displayed there. After changing it, it's now displayed.

**Comment by Oldiesmann** [comment] 2017-02-02 18:36
It's possible that the display_fields setting in the database got messed up during an upgrade due to some of the issues we've had in the past with conversion from serialize to JSON. In the screenshot you posted though, both the gender and Skype icons are in the proper place based on your settings.

**Comment by frandominguezl** [comment] 2017-02-02 18:47
Then I don't understand the behaviour of this, since both Skype & Gender were set as "with icons" and none of them appeared before. That's why I first opened this issue.

**Comment by Oldiesmann** [comment] 2017-02-02 18:59
Definitely sounds like the "displayFields" setting got corrupted at some point. That setting contains a JSON-encoded array of information about all of the custom profile fields. In earlier versions of SMF 2.1, we used serialize() instead of JSON for storing arrays in the database, and there have been some issues with that conversion process during upgrades in the past. When you changed the Skype field, that setting got updated, so everything is displaying properly now.

**Comment by sbulen** [comment] 2017-02-03 18:24
The JSON for displayfields appears to be built properly upon a fresh upgrade.

Like D3vcho, it feels like I chased it around a bit.  Almost like displaying the icons "kicked in" after I started putzing with it.  I don't suspect the JSON though.

**Comment by Oldiesmann** [comment] 2017-02-06 05:56
It's related to #3654 I believe

**Comment by frandominguezl** [comment] 2017-02-07 19:03
I updated the files of my hosted test forum (not localhost) and seems the error is not happening. Can anybody test this, please?

**Comment by sbulen** [comment] 2017-02-08 05:41
This is really a good catch...   

I suspect a disconnect between the migrated field names and what the app is using...
The app is looking for cust_skype, but the upgrader is using cust_skyp.   
I think other migrated fields are disconnected also...   

Is this it, or is this different???  This explains why I was having skype issues earlier...

![newone](https://cloud.githubusercontent.com/assets/23568484/22727029/758de268-ed8b-11e6-87b5-6dbaf5495cc1.JPG)
![skype5](https://cloud.githubusercontent.com/assets/23568484/22724877/1b16cfe6-ed7e-11e6-93b2-2ccba44385cc.JPG)
![skype2](https://cloud.githubusercontent.com/assets/23568484/22724876/1b12b5b4-ed7e-11e6-8559-0e8ab1f523b4.JPG)

**Comment by sbulen** [comment] 2017-02-08 06:08
The custom_fields in the app are:
   cust_aolins, cust_icq, **cust_skype, cust_yahoo,** cust_loca, cust_gender

The upgrader loads them as:
   cust_aolins, cust_icq, **cust_skyp, cust_yim,** cust_loca, cust_gender

YIM & Skype are wrong...   I'll push a PR forward to tweak it on the upgrader side...

**Comment by sbulen** [comment] 2017-02-08 06:54
Same user, post upgrade with fix applied - note the same user has skype & yahoo fields now fixed.

Also, last field not checked was ICQ.  Found one - all OK (ICQ icon is the green flower...).  PR submitted.

![skype-fix2](https://cloud.githubusercontent.com/assets/23568484/22726444/4fe722c0-ed88-11e6-8b0a-1494125b5ffa.JPG)
![skype-fix1](https://cloud.githubusercontent.com/assets/23568484/22726445/4fe73c42-ed88-11e6-90c5-8f4a6fa13b5b.JPG)

![skype-fix3](https://cloud.githubusercontent.com/assets/23568484/22726446/4fe797fa-ed88-11e6-8cd5-23e5ccea0205.JPG)

**Comment by sbulen** [comment] 2017-02-08 07:02
For me, the reason it felt inconsistent was that I was using a mix of migrated & new data to test.  Of course, the new stuff was fine...

**Comment by jdarwood007** [comment] 2017-02-08 23:22
If you are submitting a PR to fix an  open issue, you should add Fixes #2782 or such to the commit message, GitHub will take care of closing the related issue automatically.

**Comment by sbulen** [comment] 2017-02-09 00:10
I'm not 100% sure it closes D3vcho's original issue.   I think that should be left to D3vcho.

**Comment by sbulen** [comment] 2017-02-19 19:00
@d3vcho , has this been fixed?

**Comment by frandominguezl** [comment] 2017-02-28 14:35
@sbulen Sorry for the delay. The issue has not been solved. The icon is still displayed on the profile, but not on poster info

**Comment by sbulen** [comment] 2017-03-01 05:25
d3vcho - 

I tried to reproduce & I'm not seeing it.  It even seems to move where I tell it to go...  Pics of profile info & post info for my test case are provided below.  It was fine, & then I moved the skype icon to below the poster info just to see if it was updated appropriately, & it appears to be so.  

Maybe it was indirectly related to the migration issue?   If so, you may need to reload your DB and rerun the upgrader?   

Or maybe I'm missing something...   

![image](https://cloud.githubusercontent.com/assets/23568484/23446918/0c248ecc-fdfc-11e6-88c6-8c927d2f7ff8.png)
![image](https://cloud.githubusercontent.com/assets/23568484/23446951/45484522-fdfc-11e6-9a5a-15d7120c19c4.png)

**Comment by frandominguezl** [comment] 2017-03-01 06:02
I did not use the upgrader this time; I used a fresh GitHub copy of 2.1

**Comment by sbulen** [comment] 2017-03-01 11:58
I can't reproduce.   Can you provide some screenshots of what you're seeing?

**Comment by frandominguezl** [comment] 2017-03-01 18:28
@sbulen 

![](https://i.gyazo.com/e802d4f936adb84d657a4b736258bf97.png)

![](https://i.gyazo.com/c9202c9a9cbf97025e20471b41d3b2fe.png)

**Comment by sbulen** [comment] 2017-03-01 19:05
Well...  That'd be borked if it only worked on migrated data, wouldn't it?   

Confirmed...

It all works properly only after saving updates to the custom settings that first time...   You don't have to do this on a migrated database.  Something about the profile settings isn't getting stored properly on a vanilla install.  Earlier, I confirmed the JSON was proper.   (Vanilla was identical byte-for-byte to an upgraded forum...)  

Thinking out loud here... I wonder if there is content that gets stuffed elsewhere, like smf_settings?  Of if the install script has a hiccup?

**Comment by sbulen** [comment] 2017-03-01 19:42
D3vcho - 

Just opened up all the install & upgrade files & did a global search on custom_fields, to ensure consistency between install & upgrade & I found a difference.  

This exists on the upgrade script, but not the install script:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/upgrade_2-1_mysql.sql#L1108

(Often, when researching these issues, the Sesame Street jingle comes to mind - "One of these things is not like the other!" ;^) )

I wonder if this is the issue?   You want to give it a try?  I would add this logic to the install script & do a new install to test.  

This fits...  Because I bet updating custom_fields updates the smf_settings as well as the custom_fields.  (Although I question why we replicated this same data in two places...  Problem is now it must be maintained in two places...)

NOTE:  If you submit a PR, remember you have to mirror any mysql changes to the postgresql file as well.

**Comment by sbulen** [comment] 2017-03-01 19:56
I deeply apologize in advance if Sesame Street jingles come to mind whenever debugging future issues.

**Comment by sbulen** [comment] 2017-03-02 05:11
~~Looking at it, I just realized that the challenge will be that the install*.sql files do not behave like the upgrade*.sql files.     The upgrade*.sql files allow you to put in snippets of .php in there.   It appears the install*.sql only honor .sql.  You can't just copy the php logic over.~~

It may make sense to simply insert the new displayFields value...   

However, you can use phpMyAdmin & export the settings table DATA ONLY.  That will give you a properly formatted INSERT sequence to include in the install*.sql files.  From this, you can select and copy the INSERT for displayFields, the one we need.  Use that in the install*.sql file. That is the first thing I'd try!  

Hope this helps.  If you need any help, let me know.

**Comment by frandominguezl** [comment] 2017-03-02 18:11
If you can test it, feel free. I'm quite busy lately. Thanks :P

**Comment by sbulen** [comment] 2017-03-02 19:25
OK, will do.

Corrected a note above...

**Comment by sbulen** [comment] 2017-03-03 00:35
First post in a vanilla forum below!  (Before touching custom_fields...)  PR forthcoming.  

I'll let D3vcho decide when/whether to close this issue.

![image](https://cloud.githubusercontent.com/assets/23568484/23533366/3730ed98-ff66-11e6-9140-bf5010ddb71f.png)

**Comment by frandominguezl** [comment] 2017-03-03 06:03
Thanks @sbulen I'll test it later this afternoon

**Comment by colinschoen** [comment] 2017-03-20 05:13
#3954 fixes this. Closed.

**Closed as completed by colinschoen** 2017-03-20 05:13 UTC
