### ISSUE TITLE
Time zone problem

### ISSUE THREAD

**Issue by gevv** [SimpleMachines/SMF#6765] opened 2021-06-02 15:51 UTC
#### Description
Hello,

Server Time zone set to ""utc+03:00 turkey standart time""

but the time zone of registered all users is ""utc-coordinated universal time""

### Steps to reproduce
1. 
2. 

### Environment (complete as necessary)
- Version/Git revision:
- Database Type:
- Database Version:
- PHP Version:

### Additional information/references

**Comment by sbulen** [comment] 2021-06-02 16:46
I believe this is a dupe of https://github.com/SimpleMachines/SMF2.1/issues/6747

**Comment by sbulen** [comment] 2021-06-02 17:03
If this is a dupe, please close.  If not, please let us know what the distinction is between this & #6747

**Closed as completed** 2021-06-02 18:10 UTC
