### ISSUE TITLE
Enabling persistent connections generates errors

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4582] opened 2018-03-04 06:03 UTC
This error is now generated:
```
Type of error: Cron
2: Cannot modify header information - headers already sent by (output started at /xxxx/yyyy/public_html/VAN21/Sources/Subs-Db-mysql.php:80)
 https://blah.com/VAN21/cron.php
 /xxxx/yyyy/public_html/VAN21/cron.php (Line 270)

```
To reproduce, simply enable the option & navigate anywhere.

Latest & greatest.

Edit:  This is on my linux server, php7.1, mysql5.5

**Comment by albertlast** [comment] 2018-03-04 07:54
I went to settings.php
set $db_persist = 1;
set a breakpoint at line 67 notice that the persistent is true,
also notice that line 80 was $success is 1 (true)
This part get called twice once by load.php and once by cron.php and
everytime sucess was 1 and no error appears.

In short i'm not able to reproduce your error.

**Comment by sbulen** [comment] 2018-03-04 15:36
I set it using the db field in the application.  Under Server settings | database.

**Comment by sbulen** [comment] 2018-03-04 19:15
I also just tried it by updating settings.php as you describe.  Same issue either way.  

Note that this is in my linux system.   

I have attempted to install a fresh 2.1 in my WAMP system, to see if the issues are unique to linux, but that has failed for a variety of different reasons.  I'm about to log a different issue for that.

**Comment by albertlast** [comment] 2018-03-04 19:17
The essential diff between win and linux is,
when you use "localhost" on linux you use socket connection on windows you use always tcp/ip.
On linux you can force this by using 127.0.0.1

**Comment by albertlast** [comment] 2018-03-04 19:29
By playing with my version a error raised which could be yours too,
go to Subs-Db-mysql.php in line 72:
`$flags = MYSQLI_CLIENT_FOUND_ROWS;` to `$flags = 2; //MYSQLI_CLIENT_FOUND_ROWS = 2`

**Comment by sbulen** [comment] 2018-03-04 19:48
That change did not get rid of the error.

**Comment by sbulen** [comment] 2018-03-05 00:52
As an FYI - I do not have this issue on my WAMP server (php5.6, mysql5.7), only my linux server (php7.1, mysql5.5).

**Comment by Gwenwyfar** [comment] 2018-03-05 01:04
Not happening for me on php 7.1.14 and mysql 5.6.39, linux server. Does the last merged PR change anything, @sbulen?

**Comment by sbulen** [comment] 2018-03-05 02:00
No - I just double-checked.   I see this issue in php7.0 & 7.1.4 when persistent db sessions is enabled.  

But it does NOT happen when I have persistent db connections enabled under php5.6.

**Comment by Gwenwyfar** [comment] 2018-03-05 15:37
Could it be related to the php version mysql is using to run? Phpmyadmin still always tells me php version is 5.6, even if everything else is changed to 7.1 (through multiPHP manager)

**Comment by albertlast** [comment] 2018-03-05 16:54
testet on php 5.6 and 7.2 with maria 10.1 no error appears.

**Comment by sbulen** [comment] 2018-03-05 17:02
@Gwenwyfar - My php version selector has properly reported version #s throughout testing - I think the version #s are proper.   

FYI - I always start a round of tests with a fresh install.   (Including copying Setting.php from /other to boarddir.)

**Comment by Gwenwyfar** [comment] 2018-03-05 17:14
What I meant is that if this is a version specific bug, then it may not happen for me because my mysql is running on php 5.6 (even while the rest of the forum runs in 7.1). Or it could be unrelated, just making sure we have the right info. It seems like the mysql php version and the php version for everything else are separate in my server, which is why I brought this up.

As an added note, I also have no errors in other php versions (5.4, 5.6, 7.0, 7.1, 7.2).

**Comment by sbulen** [comment] 2018-03-06 03:31
Got to the bottom of this one...   Buried in the error log was the following:

`[04-Mar-2018 20:07:59 America/Chicago] PHP Warning:  mysqli_real_connect(): Persistent connections are disabled. Downgrading to normal ....`

I theorize that the error getting written to stderr was considered output, hence the "Cannot modify header" error?   

I'll leave this open for a few hours so folks can see the resolution before I close.

**Comment by albertlast** [comment] 2018-03-06 04:33
Can u check if 
mysqli.allow_persistent
Is false?
When yes we could check this before you try to activate persistent connection.

**Comment by sbulen** [comment] 2018-03-06 04:44
Correct, it's false.  You are right, it should probably be checked.

I think it is odd I had no error in 5.6...

**Comment by sbulen** [comment] 2018-03-06 04:53
Well...  I just changed my environment to 5.6 & now mysqli.allow_persistent is true.    

So, in my environment, the default changes to false with php 7.0/7.1.  That explains that...

**Comment by albertlast** [comment] 2018-03-06 05:20
Than keep the issue open,
i will make a pr how will make this issue more visible to the admin.

**Closed as completed** 2018-03-06 22:12 UTC

**Comment by sbulen** [comment] 2018-03-11 20:10
This needs to be reopened.  It did not work - I was still able to select persistent connections in my environment where they are disabled.  

This may be low priority?  Not sure how many folks would encounter this?

Latest from git, as of now.  linux, php7.1, mysql 5.5.

**Comment by albertlast** [comment] 2018-03-11 20:12
did you disable javascript on your smf?

**Comment by sbulen** [comment] 2018-03-11 20:12
No -

**Comment by sbulen** [comment] 2018-03-11 21:05
Confirmed - your new PR works.
