### ISSUE TITLE
progress to next page...

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2696] opened 2015-01-28 21:13 UTC
Convert HTML-entities to UTF-8 characters when you run this task it says "To avoid overloading your server, the process has been temporarily paused. It should automatically continue in a few seconds. If it doesn't, please click continue below. "

it never seems to move to the next page, not sure if something with my setup/browser or what.

**Comment by XinYenFon** [comment] 2015-01-29 15:57
I started to think, maybe its designed to behave like that? Optimze DB option also does not redirect, you need to click "back to ..." link to go back.

**Comment by illori** [comment] 2015-01-29 16:41
It has wording that says to click next if it does not automatically. I
don't know if this would also stop it from progressing automatically on
large forums.

**Comment by margarett** [comment] 2015-02-03 23:39
I agree that, at the very least, you would have no idea that the process was terminated :tongue:

**Comment by margarett** [comment] 2015-02-03 23:49
Looking at this a bit closely, I think that this function needs rework...

`// Character set conversions are only supported as of MySQL 4.1.2.
        if (version_compare('4.1.2', preg_replace('~\-.+?$~', '', $smcFunc['db_server_info']()), '>'))
            fatal_lang_error('utf8_db_version_too_low');`
Do we still support such low MySQL version?

`// No need to convert to UTF-8 if it already is.
        if ($db_character_set === 'utf8' && !empty($modSettings['global_character_set']) && $modSettings['global_character_set'] === 'UTF-8')
            fatal_lang_error('utf8_already_utf8');`
Not really happening. I can provoke the conversion as many times as I want

I'll try to populate a 2.0 forum in latin then convert it to 2.1 and try this. Just to debug

**Comment by margarett** [comment] 2015-02-04 00:23
Further investigation: when coming from a non-UTF database, it seems to work as expected. But I didn't populate my original 2.0 database with enough information to make it split the operation.
Anyway, not all tables were converted to UTF8... The following tables are still latin
smf_log_boards
smf_log_notify
smf_log_search_topics
smf_pm_labeled_messages
smf_log_activity
smf_log_mark_read
smf_log_search_results
smf_log_karma
smf_log_search_messages
smf_group_moderators
smf_log_scheduled_tasks
smf_topics
smf_log_topics
smf_moderators
smf_approval_queue
smf_moderator_groups
smf_log_polls
smf_log_spider_stats
smf_pm_recipients

**Comment by illori** [comment] 2015-02-04 00:31
may that be why i still have the task still available after i have run it?

**Comment by margarett** [comment] 2015-02-04 00:34
You should have an error saying that you are already in UTF8, not what you are getting ;)

**Comment by illori** [comment] 2015-02-04 00:38
ok that makes sense, i guess i should have mentioned it in the initial issue.

**Comment by illori** [comment] 2015-02-04 00:46
actually are you talking about the convert to utf-8 or the convert entities function?

**Comment by margarett** [comment] 2015-02-04 00:51
To utf8.
I just finished populating a 300k posts 2.0.9 forum in latin1 that I will now convert to 2.1 and retest this :)

edit: so it works as in my previous comment. I find it strange that it doesn't pause (it did 300k posts at once). Again, not all tables are converted

Oh and I was all confused :tongue: You are right, you are referring to the entities conversion and I was talking about convert database+data to utf8. Different things...

**Comment by sbulen** [comment] 2017-03-09 11:34
Is this a current 2.1 issue?   Or should it be closed?

**Comment by illori** [comment] 2017-03-10 10:08
this is still an issue. you can try to run the convert as stated above it does not move on without clicking the button.

**Comment by sbulen** [comment] 2017-03-10 13:58
The convert to utf8 function shouldn't be needed in 2.1, though, because the conversion is performed during the upgrade process.

So I'm confused...   Why is this needed in 2.1?

**Comment by XinYenFon** [comment] 2017-03-10 14:52
Well can't give the answer but @Oldiesmann should. I think he removed that function from the core but?

**Comment by illori** [comment] 2017-03-10 15:42
Does the upgrade convert everyone over?

**Comment by sbulen** [comment] 2017-03-10 16:22
Yes.  It is not an option, all users go to UTF8 as part of the upgrade.  I believe this was a change within the last couple of years.

**Comment by illori** [comment] 2017-03-11 14:38
does the upgrade change html entites to utf-8? if not then we still need this.

**Comment by XinYenFon** [comment] 2017-03-11 14:58
if its not it should be added to process as well.

**Comment by sbulen** [comment] 2017-03-11 16:36
No, the HTML entities conversion is not part of the upgrade.   

Further, when attempting to run the conversion in a newly upgraded DB, I'm getting "incorrect string value" messages, so there is something wrong with the logic at the moment.  

![image](https://cloud.githubusercontent.com/assets/23568484/23824962/c48cc380-0635-11e7-8647-2d32101a5003.png)

So...   It seems we need to add the HTML entities conversion to the upgrader and remove the HTML entities conversion from the maintenance menu.  (And figure out what the 'string' issues are....)

Is this correct?

**Comment by illori** [comment] 2017-03-11 20:08
we would need input from someone on the dev team if this is needed/wanted.

**Comment by jdarwood007** [comment] 2018-07-17 00:03
I'm trying to reproduce this but can't.  All I could do was cause it to not auto navigate due to a token error.  I referenced that in another related fixes in this section.

Is this still an issue that somebody can provide information to reproduce?

**Comment by illori** [comment] 2018-07-17 09:52
i click on the link to run the convert HTML -entities to UTF-8 characters, it takes me to the next page and nothing happens from there, it should redirect to a page to say it is finished or do more of the converting but it never does. if i click on continue i go back to the page i was on before with a message on it saying "The maintenance task 'Convert HTML-entities to UTF-8 characters' was executed successfully. " yet i can still run the convert again. if it was successful then why can i run it again?

**Comment by jdarwood007** [comment] 2018-07-17 13:39
So you are suggesting we need to add detection if we need to convert entities again?

We can easily fix that to return to the maintenance page after it finishes.

**Comment by illori** [comment] 2018-07-17 13:43
It looks unfinished right now it should redirect some where when it
finishes.

**Comment by jdarwood007** [comment] 2018-07-17 14:37
Submitted changes that fix that.

**Comment by jdarwood007** [comment] 2018-08-24 17:05
PR closed, closing this.

**Closed as completed by jdarwood007** 2018-08-24 17:05 UTC
