### ISSUE TITLE
inet_ntop(): Invalid in_addr value

### ISSUE THREAD

**Issue by MissAllSunday** [SimpleMachines/SMF#3548] opened 2016-08-23 23:34 UTC
www/beta/Sources/Subs.php
Line: 4985

This only happens when testing on localhost, the admin IP will be (string) 127.0.0  which that function cannot handle properly.

It can also happen with a few mods, I know I have one that explicitly uses 127.0.0.

**Comment by jdarwood007** [comment] 2016-08-23 23:43
So its 127.0.0 and not 127.0.0.1?  127.0.0 isn't a valid ipv4 address, its missing a octet.

**Comment by MissAllSunday** [comment] 2016-08-24 13:30
Its \www\beta\Sources\Subs.php:4979:string '127.0.0.1'  the normal and plain regular ip address for localhost.

**Comment by albertlast** [comment] 2016-08-25 16:59
sure inet_ntop can't handle 127.0.0.1 it's expect binary format,
for exp. 7f000001 should be the input for the output of 127.0.0.1 

The error is that 127.0.0.1 is in the database.

**Comment by jdarwood007** [comment] 2016-08-25 20:55
Ok, different issue then.  127.0.0. isn't a valid address and was trying to figure out why that was showing up at all.

**Comment by albertlast** [comment] 2016-08-25 21:00
The problem is,
that many information are missing.
Which table
which function
etc.

When we talk about the member table, I placed a pr which is already merge some days ago: https://github.com/SimpleMachines/SMF2.1/pull/3544

**Comment by MissAllSunday** [comment] 2016-08-31 21:00
After applying that PR the issue still happens.

Its not related to the members table, to be more specific, it is generated  
by visiting the message autogenerated by SMF on every new install:

/21/index.php?topic=1.0

The "poster", Simple Machines, uses string "127.0.0.1" as its IP:  
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/install_2-1_mysql.sql#L1721

**Comment by albertlast** [comment] 2016-09-01 04:36
Yes this another problem,
i got two solutions in mind:
1. write hard the ip adress in sql statement like now
2. use a var two place the ip adress at runtime ('{$default_ip}')

The second solution is my fav way,
because this works in pg too.
The question here is,
where i could init this var?

**Comment by MissAllSunday** [comment] 2016-09-01 14:18
I also prefer the second option, some mods also uses 127.0.0.1, specially feed posters and other similar auto posting mods.

As for when this replace can be done, it depends. it needs to be done right after the data has been retrieved from the DB.

**Comment by MissAllSunday** [comment] 2016-09-01 17:45
This is also somehow relevant: https://github.com/SimpleMachines/SMF2.1/issues/3069

**Comment by Sesquipedalian** [comment] 2016-09-08 03:19
Since mods may create their own tables that track IP addresses, there is no way to guarantee that `$bin` will be in binary format. So the `inet_dtop` function shouldn't assume that `$bin` is in binary format. There used to be a sanity check in that function to see if `$bin` was actually a string representation of an IP address before it tried to run `inet_ntop($bin)`. Reinstating that check, or something similar, would be good.

**Comment by albertlast** [comment] 2016-09-08 03:46
Since string is binary too,
is in my pov not possible to place a check for this,
see https://github.com/SimpleMachines/SMF2.1/issues/3504

**Comment by Sesquipedalian** [comment] 2016-09-08 07:42
This would do it:

```
if (!filter_var($bin, FILTER_VALIDATE_IP) === false)
    return $bin;
```

**Comment by albertlast** [comment] 2016-09-08 07:58
Nope,
Because  the binary of ipv6 could be a valid ipv6,
This problem raised already up.

---

Von: Jon Stovell notifications@github.com
Gesendet: 08.09.2016 09:42
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] inet_ntop(): Invalid in_addr value (#3548)

This would do it:

if (!filter_var($bin, FILTER_VALIDATE_IP) === false)
    return $bin

##

**Comment by Sesquipedalian** [comment] 2016-09-08 08:32
Can you remind me why they are being stored in binary in the first place?

**Comment by albertlast** [comment] 2016-09-08 08:49
many reasons which I not all know
-to be able to sort to use betwee
- right format for differet ipv6 styles
- validation
  -To save ipv6 and ipv4 in the same field

When your mod doesn't need this you don't had to use this,
But my recommendation from db side is,
To use varchar @mysql and inet @pg.
In smf exists the functions two handle this automatically.

---

Von: Jon Stovell notifications@github.com
Gesendet: 08.09.2016 10:32
An: SimpleMachines/SMF2.1
Cc: albertlast; Comment
Betreff: Re: [SimpleMachines/SMF2.1] inet_ntop(): Invalid in_addr value (#3548)

Can you remind me why they are being stored in binary in the first place?

##

**Comment by Sesquipedalian** [comment] 2016-09-08 22:00
Thanks, @albertlast. I think with my latest commits to #3570, I've taken care of the situation as well as possible. I agree that using `{$default_ip}` or `{localhost}` or something like that instead of hard-coding `127.0.0.1` is also a good idea, but the function still needs to handle being passed unpacked strings correctly, so I've built those safety checks into the function now.

**Closed as completed** 2016-09-22 23:04 UTC
