### ISSUE TITLE
Settings.php missing elements

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#5988] opened 2020-02-03 10:03 UTC
#### Description
```
<?php

/**
 * The settings file contains all of the basic settings that need to be present when a database/cache is not available.
 *
 * Simple Machines Forum (SMF)
 *
 * @package SMF
 * @author Simple Machines https://www.simplemachines.org
 * @copyright 2020 Simple Machines and individual contributors
 * @license https://www.simplemachines.org/about/smf/license.php BSD
 *
 * @version 2.1 RC2
 */

# Make sure the paths are correct... at least try to fix them.
if (!is_dir(realpath($boarddir)) && file_exists(dirname(__FILE__) . '/agreement.txt'))
	$boarddir = dirname(__FILE__);
if (!is_dir(realpath($sourcedir)) && is_dir($boarddir . '/Sources'))
	$sourcedir = $boarddir . '/Sources';
if (!is_dir(realpath($tasksdir)) && is_dir($sourcedir . '/tasks'))
	$tasksdir = $sourcedir . '/tasks';
if (!is_dir(realpath($packagesdir)) && is_dir($boarddir . '/Packages'))
	$packagesdir = $boarddir . '/Packages';
if (!is_dir(realpath($cachedir)) && is_dir($boarddir . '/cache'))
	$cachedir = $boarddir . '/cache';

########## Error-Catching ##########
# Note: You shouldn't touch these settings.
if (file_exists((isset($cachedir) ? $cachedir : dirname(__FILE__)) . '/db_last_error.php'))
	include((isset($cachedir) ? $cachedir : dirname(__FILE__)) . '/db_last_error.php');

if (!isset($db_last_error))
{
	// File does not exist so lets try to create it
	file_put_contents((isset($cachedir) ? $cachedir : dirname(__FILE__)) . '/db_last_error.php', '<' . '?' . "php\n" . '$db_last_error = 0;' . "\n" . '?' . '>');
	$db_last_error = 0;
}

?>
```

### Steps to reproduce
1. i just updated to latest version
2. ran upgrade.php via CLI and the results of the Settings.php file is missing a lot.

### Environment (complete as necessary)
- Version/Git revision: latest as of a few minutes before this was submitted.
- Database Type:
- Database Version:
- PHP Version: 7.1.33

### Additional information/references
when i load the forum with this Settings.php file, i get the following errors:
( ! ) Notice: Undefined variable: boarddir in C:\wamp64\www\github2.1\Settings.php on line 17
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0
2	0.0001	388840	require_once( 'C:\wamp64\www\github2.1\Settings.php' )	...\index.php:46

( ! ) Notice: Undefined variable: sourcedir in C:\wamp64\www\github2.1\Settings.php on line 19
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0
2	0.0001	388840	require_once( 'C:\wamp64\www\github2.1\Settings.php' )	...\index.php:46

( ! ) Notice: Undefined variable: tasksdir in C:\wamp64\www\github2.1\Settings.php on line 21
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0
2	0.0001	388840	require_once( 'C:\wamp64\www\github2.1\Settings.php' )	...\index.php:46

( ! ) Notice: Undefined variable: packagesdir in C:\wamp64\www\github2.1\Settings.php on line 23
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0
2	0.0001	388840	require_once( 'C:\wamp64\www\github2.1\Settings.php' )	...\index.php:46

( ! ) Notice: Undefined variable: cachedir in C:\wamp64\www\github2.1\Settings.php on line 25
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0
2	0.0001	388840	require_once( 'C:\wamp64\www\github2.1\Settings.php' )	...\index.php:46

( ! ) Notice: Undefined variable: boarddir in C:\wamp64\www\github2.1\index.php on line 56
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0

( ! ) Notice: Undefined variable: boarddir in C:\wamp64\www\github2.1\index.php on line 60
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0

( ! ) Notice: Undefined variable: sourcedir in C:\wamp64\www\github2.1\index.php on line 66
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0

( ! ) Warning: require_once(/QueryString.php): failed to open stream: No such file or directory in C:\wamp64\www\github2.1\index.php on line 66
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0

( ! ) Fatal error: require_once(): Failed opening required '/QueryString.php' (include_path='.;C:\php\pear') in C:\wamp64\www\github2.1\index.php on line 66
Call Stack
#	Time	Memory	Function	Location
1	0.0000	371264	{main}( )	...\index.php:0

my old Settings.php file is attached with a few minor changes [like removed password]
[Settings.txt](https://github.com/SimpleMachines/SMF2.1/files/4147254/Settings.txt)

**Comment by sbulen** [comment] 2020-02-03 17:51
I cannot reproduce this.  I even started with your settings.txt above & attempted to build an environment close to it - even a "." in the DB name & a ":80" port in the URL.  Everything worked fine.

Note the settings.txt provided above has some duplication in it for the paths & error file.  This is likely a holdover from the prior issues we were having.  This didn't hurt anything though, it worked fine even with the duplication.

**Comment by illori** [comment] 2020-02-03 18:11
I even put my file back and ran the upgrade again and got the same results.
Maybe php version is an issue?

**Comment by sbulen** [comment] 2020-02-03 19:00
I tried both 7.3 & 7.1.  Windows.  

My first thought is that maybe your git environment is somehow not up-to-date?  If you do a git status, does everything look OK?  Everything fetched/merged properly?

**Comment by illori** [comment] 2020-02-03 19:20
I sent you a pm with git status.

**Comment by illori** [comment] 2020-02-03 22:07
i have cleaned up my install
git clean -f -X 

i am still getting the same output from running the upgrade.php via CLI.

i checked Settings_bak.php and it is also missing content:

```<?php

/**
 * The settings file contains all of the basic settings that need to be present when a database/cache is not available.
 *
 * Simple Machines Forum (SMF)
 *
 * @package SMF
 * @author Simple Machines https://www.simplemachines.org
 * @copyright 2020 Simple Machines and individual contributors
 * @license https://www.simplemachines.org/about/smf/license.php BSD
 *
 * @version 2.1 RC2
 */
```

**Comment by illori** [comment] 2020-02-03 22:12
i have tried to run the upgrade from browser and i get the below. it does not even finish running the upgrade script, i get a failed to open /Subs.php and it goes no further.
```
<?php

/**
 * The settings file contains all of the basic settings that need to be present when a database/cache is not available.
 *
 * Simple Machines Forum (SMF)
 *
 * @package SMF
 * @author Simple Machines https://www.simplemachines.org
 * @copyright 2020 Simple Machines and individual contributors
 * @license https://www.simplemachines.org/about/smf/license.php BSD
 *
 * @version 2.1 RC2
 */
```

**Comment by illori** [comment] 2020-02-03 22:30
does a phpinfo file help any?
[phpinfo.zip](https://github.com/SimpleMachines/SMF2.1/files/4150519/phpinfo.zip)

**Comment by sbulen** [comment] 2020-02-03 22:55
Hate to ask, but...  Does Sources\Subs.php exist?

When you checkout release-2.1, does it tell you that you are current, like the following?
![image](https://user-images.githubusercontent.com/23568484/73698116-16835a80-4695-11ea-8a43-c43588ffa15b.png)

(For Illori, origin points directly to SMF.)

**Comment by illori** [comment] 2020-02-03 23:01
yes it does, but calls to to where it is are missing in Settings.php .


$sourcedir etc are not present.

**Comment by illori** [comment] 2020-02-03 23:06
C:\wamp64\www\github2.1>"C:\Program Files\Git\bin\git.exe" reset --hard
HEAD is now at 7e2b859aa Merge branch 'release-2.1' of https://github.com/SimpleMachines/SMF2.1 into release-2.1

C:\wamp64\www\github2.1>"C:\Program Files\Git\bin\git.exe" pull origin
Already up to date.

**Comment by sbulen** [comment] 2020-02-03 23:29
At the moment, I don't think you have an environment issue.  What is very suspicious is that message you sent earlier where get said it was 236 commits ahead of release-2.1.  That, I think, is a problem.  

For example, when I do a git reset hard, I get:
![image](https://user-images.githubusercontent.com/23568484/73698856-22701c00-4697-11ea-9e31-59557f4ecd3d.png)

And the last commit displayed there is in fact the last one merged.   I don't know what '7e2b859aa' is...  I think your git is way out of sync somehow.  

That's why I would go to your git bash prompt & do the following:
```
	git checkout release-2.1
	git fetch origin
	git reset --hard origin/release-2.1
```

**Comment by illori** [comment] 2020-02-04 00:19
C:\wamp64\www\github2.1>cd \

C:\>cd wamp64\www\github2.1\

C:\wamp64\www\github2.1>"C:\Program Files\Git\bin\git.exe" checkout release-2.1
Already on 'release-2.1'
Your branch is ahead of 'origin/release-2.1' by 436 commits.
  (use "git push" to publish your local commits)

C:\wamp64\www\github2.1>"C:\Program Files\Git\bin\git.exe" fetch origin

C:\wamp64\www\github2.1>"C:\Program Files\Git\bin\git.exe" reset --hard origin/release-2.1
HEAD is now at f1adaab44 Merge pull request #5985 from live627/tz

C:\wamp64\www\github2.1>cd C:\wamp64\www\github2.1\other

C:\wamp64\www\github2.1\other>copy upgrade* C:\wamp64\www\github2.1
upgrade-helper.php
upgrade.php
upgrade_1-0.sql
upgrade_1-1.sql
upgrade_2-0_mysql.sql
upgrade_2-0_postgresql.sql
upgrade_2-1_mysql.sql
upgrade_2-1_postgresql.sql
        8 file(s) copied.

C:\wamp64\www\github2.1\other>cd ..

C:\wamp64\www\github2.1>C:\wamp64\bin\php\php7.1.33\php.exe upgrade.php  1>up.txt

C:\wamp64\www\github2.1>del upgrade*

C:\wamp64\www\github2.1>"C:\Program Files (x86)\Notepad++\notepad++.exe" C:\wamp64\www\github2.1\up.txt

results of Settings.php below
```
<?php

/**
 * The settings file contains all of the basic settings that need to be present when a database/cache is not available.
 *
 * Simple Machines Forum (SMF)
 *
 * @package SMF
 * @author Simple Machines https://www.simplemachines.org
 * @copyright 2020 Simple Machines and individual contributors
 * @license https://www.simplemachines.org/about/smf/license.php BSD
 *
 * @version 2.1 RC2
 */

# Make sure the paths are correct... at least try to fix them.
if (!is_dir(realpath($boarddir)) && file_exists(dirname(__FILE__) . '/agreement.txt'))
	$boarddir = dirname(__FILE__);
if (!is_dir(realpath($sourcedir)) && is_dir($boarddir . '/Sources'))
	$sourcedir = $boarddir . '/Sources';
if (!is_dir(realpath($tasksdir)) && is_dir($sourcedir . '/tasks'))
	$tasksdir = $sourcedir . '/tasks';
if (!is_dir(realpath($packagesdir)) && is_dir($boarddir . '/Packages'))
	$packagesdir = $boarddir . '/Packages';
if (!is_dir(realpath($cachedir)) && is_dir($boarddir . '/cache'))
	$cachedir = $boarddir . '/cache';

########## Error-Catching ##########
# Note: You shouldn't touch these settings.
if (file_exists((isset($cachedir) ? $cachedir : dirname(__FILE__)) . '/db_last_error.php'))
	include((isset($cachedir) ? $cachedir : dirname(__FILE__)) . '/db_last_error.php');

if (!isset($db_last_error))
{
	// File does not exist so lets try to create it
	file_put_contents((isset($cachedir) ? $cachedir : dirname(__FILE__)) . '/db_last_error.php', '<' . '?' . "php\n" . '$db_last_error = 0;' . "\n" . '?' . '>');
	$db_last_error = 0;
}

?>
```

**Comment by sbulen** [comment] 2020-02-04 03:19
Ok. So i think git is proper now!  Progress!   HEAD is at f1adaab, like up on github!

The two next pieces are the settings.php and the db.  Is the app usable before you upgrade?   We can only upgrade a working app.   Next step is to get the app running.  If needed, a new install???

**Comment by Sesquipedalian** [comment] 2020-02-04 06:06
Reopened. I put the wrong issue number in the commit that made #5993.

**Comment by Sesquipedalian** [comment] 2020-02-04 06:17
Once your environment is all sorted out, @illori, try running again now that #5993 has been merged. The failure of the regular expressions reported in #5987 wouldn't be enough on their own to cause the symptoms reported in this issue, but they could conceivably contribute to this issue if some other problems were play.

**Comment by illori** [comment] 2020-02-04 09:50
much better now...

before the upgrade i have 

$db_port = 3306;

after the upgrade i have 
$db_port = 0;

also i notice there is this part as well

//$db_show_debug = true;
$db_character_set = 'utf8';

$db_show_debug = true;

the $db_show_debug should show one time right? so the commented one should be removed or? i did have it set to true before.

**Comment by Sesquipedalian** [comment] 2020-02-04 17:51
Yeah. Your original Settings.php has some duplicate entries to start with, so those are showing up multiple times in the output, too. I have an idea for a way to safely remove duplicates, but I will need to test it in multiple scenarios to make sure it doesn’t introduce any unexpected behaviour.

**Comment by sbulen** [comment] 2020-02-04 18:37
> Yeah. Your original Settings.php has some duplicate entries to start with, so those are showing up multiple times in the output, too. I have an idea for a way to safely remove duplicates, but I will need to test it in multiple scenarios to make sure it doesn’t introduce any unexpected behaviour.

I suspect that Illori's messed up settings.php was caused previously, by #5815.  It's not a normal situation.

My 2¢...  If a settings.php file has big structural issues like this, that should be fixed manually.  

I would rather wrap up the GDPR/RC3 work and move on past settings - other than necessary bug fixes.

I'm afraid these updatesettings changes are already kind of complex.  I'd rather not keep enhancing it.  I am not convinced we are done chasing bugs from the last set of changes...  Let's let it settle down.  

I suggest that Illori do a new install & then resume her nightly batch upgrades.  If that works, we can close this out.

**Comment by illori** [comment] 2020-02-04 18:42
My Settings.php file I believe is from a really old 2.1 beta install.

**Comment by sbulen** [comment] 2020-02-04 18:44
Do you have a backup from before 1/8?  

Your batch process runs every night, & updates settings.php...  Every night...

**Comment by illori** [comment] 2020-02-04 18:49
My Settings.php file is way before that. I have been restoring it from
backup.

**Comment by sbulen** [comment] 2020-02-04 18:53
Food for thought...  Anybody who ran an upgrade, install, or updated the settings file via ACP, using then-current GH code, from 1/9 thru 2/2, almost certainly has a corrupted settings.php file.

**Comment by sbulen** [comment] 2020-02-04 18:57
> My Settings.php file is way before that. I have been restoring it from backup.

Helpful to know.  All the more reason to start afresh, IMO.

**Comment by illori** [comment] 2020-02-04 19:05
When time allows I will try.

**Comment by Sesquipedalian** [comment] 2020-02-04 20:31
#5996 should be able to fix @illori's settings file.

**Comment by Sesquipedalian** [comment] 2020-02-05 22:04
Can this be closed now, @illori?

**Closed as completed** 2020-02-05 22:04 UTC
Labels: Upgrader
