### ISSUE TITLE
Double check box in quick moderation

### ISSUE THREAD

**Issue by Mavn** [SimpleMachines/SMF#3921] opened 2017-02-06 06:09 UTC
Google chrome 56 I have double check box in quick moderation

![2017-02-06_9-03-24](https://cloud.githubusercontent.com/assets/2140726/22636338/4ba03a82-ec4b-11e6-802d-237a37e727c4.png)
in firefox 53.0a2 (2017-01-30) Dev edition I haven't this issue

**Comment by frandominguezl** [comment] 2017-02-06 15:28
Can't reproduce the issue using Chromium

**Comment by realdigger** [comment] 2017-02-06 15:34
Chrome 56.0.2924.87

![chrome](https://cloud.githubusercontent.com/assets/1187218/22653553/34376390-eca3-11e6-82d7-31968499c8b2.png)

**Comment by frandominguezl** [comment] 2017-02-06 15:39
Can you post an URL to your forum in case it's public?

I used a fresh GitHub copy to test this...

**Comment by realdigger** [comment] 2017-02-06 16:02
> I used a fresh GitHub copy to test this...

Test your GitHub copy with Chrome bowser instead of Chromium.

**Comment by colinschoen** [comment] 2017-02-07 06:41
I'm not seeing that at all in that version of Chrome.

<img width="1021" alt="screen shot 2017-02-06 at 22 40 36" src="https://cloud.githubusercontent.com/assets/2927722/22680528/527bd132-ecbd-11e6-92e1-3f38bf973556.png">

**Comment by realdigger** [comment] 2017-02-07 11:27
> I'm not seeing that at all in that version of Chrome.

How can you see that if you don't have quick moderation checkboxes enabled?
Forum Profile - Look and Layout - Show quick-moderation as: checkboxes

**Comment by frandominguezl** [comment] 2017-02-07 18:15
Tested with Chrome 56.0... and couldn't reproduce the error
Are you using the latest github build?

**Comment by colinschoen** [comment] 2017-02-09 01:15
Whoops, haven't used this feature before. However, even with it enabled I still can't seem to reproduce this on `56.0.2924.87 (64-bit)`

<img width="1163" alt="screen shot 2017-02-08 at 17 14 31" src="https://cloud.githubusercontent.com/assets/2927722/22764864/17b85d2a-ee22-11e6-9b60-a5772ce6f187.png">

**Comment by Oldiesmann** [comment] 2017-02-09 18:00
Only a single checkbox for me as well. Same version of Chrome.

**Comment by realdigger** [comment] 2017-02-12 22:15
Looks like it was issue with one forum only.

**Comment by colinschoen** [comment] 2017-02-25 07:15
Closing as we are not able to duplicate.

**Closed as completed by colinschoen** 2017-02-25 07:15 UTC
