### ISSUE TITLE
db_change_column adds DEFAULT NULL when not required on primary key

### ISSUE THREAD

**Issue by tinoest** [SimpleMachines/SMF#7631] opened 2022-11-25 15:08 UTC
#### Description
DB Change Column add's DEFAULT NULL

SMF 2.1.3
`ALTER TABLE smf_tp_articles CHANGE COLUMN `id` `id` int(11) NOT NULL DEFAULT NULL auto_increment`

SMF 2.1.2
`ALTER TABLE smf_tp_articles CHANGE COLUMN `id` `id` int(11) NOT NULL auto_increment `

### Steps to reproduce
1. Install TinyPortal on SMF 2.1.2
2. Update to SMF 2.1.3
3. Uninstall TinyPortal
4. Install TinyPortal again

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1.3
- Database Type: MySQL
- Database Version: 8.0.29
- PHP Version: 

### Additional information/references

https://www.tinyportal.net/index.php?topic=36797.0

**Comment by tinoest** [comment] 2022-11-25 15:33
Also on Maria DB 10.6.11

```
Invalid default value for 'item_type'
File: /var/www/html/Packages/temp/TinyPortal/install.php
Line: 354


ALTER TABLE smf_tp_comments
CHANGE COLUMN `item_type` `item_type` varchar(255) DEFAULT '\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'NULL\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'' 

```

**Comment by sbulen** [comment] 2022-11-25 16:42
I believe this is a dupe of #7627 .

**Comment by sbulen** [comment] 2023-01-04 01:25
I have confirmed that PR #7604  has addressed this problem as well. The reinstall runs fine on current GitHub code.

I'll close out this issue.

**Closed as completed by sbulen** 2023-01-04 01:25 UTC
Labels: MySQL, Package Manager, Database
