### ISSUE TITLE
Package install create-dir instruction bug

### ISSUE THREAD

**Issue by psrustik** [SimpleMachines/SMF#3008] opened 2015-08-27 09:58 UTC
There is error _Modification parse error_ when installing mod with create-dir instruction.
But ignoring the error a folder is successfully created.

package-info.xml

```
<?xml version="1.0"?>                                                 
<!DOCTYPE package-info SYSTEM "http://www.simplemachines.org/xml/package-info">
<package-info xmlns="http://www.simplemachines.org/xml/package-info" xmlns:smf="http://www.simplemachines.org/">
        <id>smf21:samplepackage</id>                                  
        <name>SMF 2.1 Beta 2 sample package</name>                    
        <version>1.41</version>                                       
        <type>modification</type>                                     
        <install for="2.0 - 2.1.99">                                  
                <create-dir name="my_extension_dir" destination="$sourcedir"/>
        </install>
        <uninstall for="2.0 - 2.1.99">
                <remove-dir name="$sourcedir/my_extension_dir/"/>
        </uninstall>
</package-info>
```

![create-dir_bug](https://cloud.githubusercontent.com/assets/804867/9517758/9bc15c10-4ccb-11e5-9162-1c0838dadd9e.png)

**Comment by Oldiesmann** [comment] 2015-08-27 15:16
This appears to be a duplicate of #2929. Is this still an issue with the latest version from GitHub? There was a problem with the code that handles zip files that was fixed recently.

**Comment by psrustik** [comment] 2015-08-27 15:25
Hi.
It still in latest version from GitHub.
Problem in this code [Packages.php#L662](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Packages.php#L662)

**Comment by Oldiesmann** [comment] 2015-08-27 15:48
If you change line 660 to this, does it work properly?

```
        if (isset($action['filename']) && !file_exists($file) && !in_array($action['type'], array('require-dir', 'require-file')))
```

**Comment by psrustik** [comment] 2015-08-27 15:55
Error still when adding 'require-dir', 'require-file' . 

If change to this code

```
if (isset($action['filename']) && !file_exists($file) && $action['type'] != 'create-dir')
```

all ok
I using **create-dir** instruction

**Closed as completed** 2015-08-27 16:08 UTC
Labels: Package Manager

**Comment by psrustik** [comment] 2015-08-27 16:29
Thanks!

From latest version from Github the package was installed successfully
