### ISSUE TITLE
Undefined index 'approved' in subs-post causes XML parsing error

### ISSUE THREAD

**Issue by WhistlingDonkey** [SimpleMachines/SMF#6993] opened 2021-08-20 11:28 UTC
#### Description
A follow on to #6989.

The Error Log trace in the reported issue https://www.simplemachines.org/community/index.php?topic=578562 giving undefined index 'approved' on line 2348 of Subs-Post.php does not affect #6989 but it does affect the quick-edit box. When the save button is pressed an XML parsing error `junk after the document element` is generated. This causes the XHR process to fail resulting in the screen not completing to the "message saved" state, though the modification is saved.

### Steps to reproduce
1. Create a post, most likely with an inserted attachment.
2. Use the quick edit box to modify the post
3. Click save. You should get the undefined index error in the error log and the DOM console should show an XML parsing error. The screen should stay at the "Loading" stage but the modified post was saved.

### Environment (complete as necessary)
- Version/Git revision: Github a9b8608

### Additional information/references
I can not reproduce the issue any longer. I removed the 'approved' check on line 2348, saved the modified post, reinstated the 'approved' check and now it works fine without error even after clearing cookies and cache.

**Comment by BrickOzp** [comment] 2021-08-20 11:53
Is this the same error as fixed in **https://github.com/SimpleMachines/SMF2.1/commit/6352c16eee3d51e0600c9febc0becb5adb4bb064**?

**Comment by WhistlingDonkey** [comment] 2021-08-20 12:49
Yes, same error. I'm not sure what version of that line @jdarwood007 has running on simplemachines.org so the OP there could have been coming up against the old version but I was able to reproduce it on my test server even though I'm running the 6352c16 version. I'm trying to work out why it works correctly now after I removed the approved check, saved the post and then reapplied the approved check.

**Comment by Sesquipedalian** [comment] 2021-08-20 18:42
> ### Additional information/references
> I can not reproduce the issue any longer. I removed the 'approved' check on line 2348, saved the modified post, reinstated the 'approved' check and now it works fine without error even after clearing cookies and cache.

I cannot reproduce this either. If you find a way to reproduce it again, @WhistlingDonkey, feel free to reopen this.

**Closed as completed by Sesquipedalian** 2021-08-20 18:42 UTC
