### ISSUE TITLE
Can't open the admin panel

### ISSUE THREAD

**Issue by Sefank** [SimpleMachines/SMF#4677] opened 2018-03-30 00:53 UTC
When open the admin panel, it comes that
> Parse error: in /home/bae/app/Sources/Load.php(3055) : eval()'d code on line 51

**Comment by frandominguezl** [comment] 2018-03-30 07:42
Are you using the latest GitHub available version?

**Comment by Sefank** [comment] 2018-03-30 09:36
Yes, using commit ver b017107.

**Comment by wintstar** [comment] 2018-03-30 09:53
Which language package do you use?

I have with this commit no problems.

**Comment by XinYenFon** [comment] 2018-03-30 11:22
can't reproduce this issue.

**Comment by albertlast** [comment] 2018-03-30 21:35
Test please the pr #4680 maybe the issue get fixed or the error message get more clear.

**Comment by Sefank** [comment] 2018-04-02 02:31
Yes, it's a language package error. Thanks for the pr #4680 to find where it's wrong.

**Comment by albertlast** [comment] 2018-04-02 05:18
And the language pack is not the offical from smf2.1 beta4?

**Comment by wintstar** [comment] 2018-04-02 07:02
@albertlast, on simpelmachines.org either a note should be added to the downloads that the 2.1 language packs are not up to date or the language packs should be updated. Some of the error messages here, could thus be avoided.

**Comment by Sefank** [comment] 2018-04-02 08:07
@albertlast The offical one from smf2.1 beta 4? Should it be got from this repo? The language editor shows that the English version was only updated to beta 3.

**Comment by albertlast** [comment] 2018-04-02 08:21
The beta 4 language file got some new text array entries so the beta 3 doesn't work in beta 4

**Comment by Sefank** [comment] 2018-04-02 08:55
OK I will check them. Anyway thanks~

**Comment by wintstar** [comment] 2018-04-02 09:03
> The beta 4 language file got some new text array entries so the beta 3 doesn't work in beta 4

@albertlast, then this should be published on simpelmachines.org.

**Comment by albertlast** [comment] 2018-04-02 10:22
@wintstar since it the second time in a short time that you tell me what sm team had to do...
please look at my status "Collaborator" that mean i provide some amount of code but i'm not part of the sm.org team.

**Comment by wintstar** [comment] 2018-04-02 10:32
Sorry, @albertlast. After your great work here, I assumed you are part of the team.

> On simpelmachines.org either a note should be added to the downloads that the 2.1 language packs are not up to date or the language packs should be updated. Some of the error messages here, could thus be avoided.
>>The beta 4 language file got some new text array entries so the beta 3 doesn't work in beta 4

@Sesquipedalian, you could take it on here?

**Comment by albertlast** [comment] 2018-04-15 16:21
This got in my eyes fixed,
since we got here two problems
eval got issue of missing language stuff -> got fixed by pr
language file from beta 3 was used -> don't do it

**Comment by albertlast** [comment] 2018-04-28 07:50
@Sefank could we close this issue?

**Closed as completed** 2018-04-28 09:22 UTC
Labels: Localization
