### ISSUE TITLE
3 Login Errors

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4297] opened 2017-09-14 03:16 UTC
When there is a cookie/session issue, trying to login gives inappropriate error messages.  

To reproduce:
(1) Under Admin | Maintenance | Server Settings | Cookies & Sessions, change the value for "Enable Local Storage of Cookies".   (Changing this value properly affects _future_ cookie behavior, but screws up _active_ sessions...)
(2) Log out.
(3) Try to logon 3 times in rapid succession.  Quick is important.  

By the way, you are now LOCKED OUT...  You must delete your SMF cookie to log back in.  

The errors:  
(1)  When logging on, you get "Your session timed out when posting.  Please go back and try again."  Which makes no sense...  
![login-1](https://user-images.githubusercontent.com/23568484/30410306-132964be-98bf-11e7-8359-c6ca908e67b1.JPG)

(2)  On your 3rd attempt, it does not properly display the error message.  When trying to report "Sorry, but you've reached your login attempts threshold for account xxxxxx. Please wait 30 seconds and try again later.", instead, all you get is:
![login-2](https://user-images.githubusercontent.com/23568484/30410417-c42235de-98bf-11e7-9097-040fb204a8d3.JPG)

(3) The code checks for 5 login attempts.  Why did it fail after 3?  The problem is that validatePasswordFlood() is called from multiple places during login, doubling up on the count of attempts.   Your 3rd attempt internally is 5/6 due to the double-counting.   Not a huge issue, but an indication that some streamlining is in order.  

I considered logging these as 3 separate issues.  If you want me to do so I'll split them up.  

I do think this is kind of important, as it appears to me that there are certain admin tasks & settings updates that will basically lock folks out...  The only way to recover is to delete the cookie.

**Comment by albertlast** [comment] 2017-09-21 18:42
Was not able to validate issue 2 and 3.
2. created the right error message
3. do it after 5 tries and in the debugger i didn't notice any double call of validatePasswordFlood()

**Comment by Sesquipedalian** [comment] 2017-09-25 17:35
I'd say that this should actually be considered four issues. The first part is "Changing this value properly affects future cookie behavior, but screws up active sessions..." After that we have the two different bugs with wrong error messages, and finally the double count of validatePasswordFlood().

Regarding the first of these, I wonder if enabling/disabling cookie related settings (local storage, global cookies, etc.) should automatically invalidate all current cookies and end all sessions, thereby requiring everyone to log back in.

**Comment by albertlast** [comment] 2017-09-26 17:38
About 1 I got this issue today and was able to trace back from where this came (maybe i'm the only on how don't know from where this came)
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Security.php#L610
In my mind i would use here a unset/destroy of the session,
so that the user get the chance to relog after this error.

**Comment by sbulen** [comment] 2017-09-27 13:41
You won't see 2 or 3 above if you can't get the 3 login attempts within 10 seconds.   That's why doing it quickly is important.  You're trying to trigger the flood error.

**Comment by sbulen** [comment] 2017-09-27 14:11
Yes, L610 is the line where that message comes from.

**Comment by albertlast** [comment] 2017-09-27 14:12
Can we not destroy the session and everything is fine?

**Comment by sbulen** [comment] 2017-09-30 01:44
@albertlast - I do think you are right & that's the solution for (1) .  

I think there is a (2) has a separate root cause - I suspect when a flood is detected the error template is being called very early before it is properly initialized.  It's missing something - language?   Something so profound that it doesn't even know what to display when the flood error is triggered - just 'error'.  

I think (3) may necessitate a rewrite.  You can see the multiple calls to validatePasswordFlood() in a trace.   The bottom line is that 3 < 5, so that error should not be triggered at all on the 3rd try. 

(1) and (2) do NOT happen in 2.0.

I was experimenting with this, trying several things that I thought made sense, but given that the cookie, session & token logic are all intermingled, I was afraid of breaking something and, for example, possibly rendering the token or session checks ineffective.  

I don't GROK how it works yet...  At the moment, these issues are over my head.

**Comment by albertlast** [comment] 2017-09-30 04:39
Can you please give me a hint from where the validatePasswordFlood in your traces?

**Comment by sbulen** [comment] 2017-09-30 06:25
It is called both in Load.php, LoadUserSettings() and in LogInOut.php, Login2().  

That help?  Or I could provide the actual stack traces.

**Comment by albertlast** [comment] 2017-09-30 06:44
I mean where this function can be called i can see by my self,
but while the login process i see only the way:
![grafik](https://user-images.githubusercontent.com/1782906/31043424-94a894de-a5bb-11e7-9fe7-dff0a0c5a701.png)
So when this is the only way than is no double call of this function.

**Comment by sbulen** [comment] 2017-09-30 06:50
Actually, just did it...  The problem isn't that it's getting called from multiple _places_...   The problem is that is gets called multiple _times_ per login.  

Once while presenting the login prompt, and once after you press 'login'...   

Both times it was called from LoadUserSettings().  Trace follows.
![image](https://user-images.githubusercontent.com/23568484/31043456-e913b79c-a570-11e7-9c4e-5ef579195623.png)

I had to follow the exact steps above - e.g., change the cookie setting, log out, etc...

**Comment by albertlast** [comment] 2017-09-30 06:56
When i call http://localhost/SMF2.1/index.php?action=login than is the function not called.
Only after pushing Login button.

**Comment by sbulen** [comment] 2017-09-30 07:01
To see these symptoms, you need to follow the exact steps listed above - change cookie settings, logout, log back on.   

The stack above is traversed once after hitting the login link, and once again after typing credentials and pressing 'login'.

**Comment by albertlast** [comment] 2017-09-30 07:08
When you look at this code line: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L433
you see that you stacktrace shouldn't happen because you are in this moment a guest,
which mean the line https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L480 is never called,
So you should check why you'r a no guest at this time.

**Comment by sbulen** [comment] 2017-09-30 11:04
Yes.   It is working off of old session info.   None of this happens if you delete the cookie or session first.

**Comment by sbulen** [comment] 2017-09-30 11:56
Even knowing this, I have tried several changes, nothing worked.  

2.0 works.   What's the big change throughout this logic?   2FA.   I think something key & structural happened there somewhere.  Just haven't found it yet.  I was thinking of doing a 2.0 vs 2.1 trace comparison, to see where the big deviation is...

**Comment by albertlast** [comment] 2017-09-30 12:28
Maybe the logout didn't removed the session/information in right way.

**Comment by sbulen** [comment] 2017-09-30 12:41
Yep.  Sure sounds easy, doesn't it?

**Comment by albertlast** [comment] 2017-09-30 12:45
dunno, since i'm not able to reproduce this,
i can only say what i think.

**Comment by sbulen** [comment] 2017-10-08 15:39
I have been trying to get to the true root cause.  I believe the source of these issues is actually with the logout logic.  If you properly logout, under normal circumstances, cookie contents are cleared out and you get redirected to the board index and things end cleanly.  Subsequent logins do not have any issue.  

For some reason, after changing cookie settings, when you logout the cookie appears to be confused.  The ID still has the user ID (which shouldn't happen) but the password was changed by the logout.  So it thinks you have a proper ID but bad password, and the validatePasswordFlood logic is triggered - as well as some other issues.  

Note this doesn't just impact the admin, it impacts other users logged in at the time the cookie settings change.

**Comment by albertlast** [comment] 2017-10-08 15:45
While creating this pr,
i notice that the path of smf cookie is switching between "/" and "/<forumDirectory>",
this create issues on cookie handling,
to change a cookie you need to know which path the cookie got otherwise you create a new one and
the old keep existing...

**Comment by sbulen** [comment] 2017-10-08 15:55
Possibly related - I have noticed that session_set_save_handler() is not always called.  If I understand it correctly, this is what takes us from file-based sessions to DB-based sessions.  That might be confusing things as well???

**Comment by sbulen** [comment] 2017-10-08 16:08
One other thing I observed - the change I was definitely going to make....  

Line 175 of LogInOut.php issues a call to checkSession with no parameters.  checkSession  defaults to thinking you are making a 'post'.  This is where the session IDs don't match and you get the erroneous 'session timed out' error.  

checkSession is confusing a post with a user update with a post of the login form.  

Changing checkSession() to checkSession('login') fixes that.   After that change, the login logic properly detects that there is something strange going on with the cookie and gives you a proper message telling you so.

**Comment by albertlast** [comment] 2017-10-08 16:09
the session timeout message i fixed with this: https://github.com/SimpleMachines/SMF2.1/pull/4353/files#diff-513c4f9c501cbefcc14420c01848f23cL813

**Comment by sbulen** [comment] 2017-10-08 16:11
Understood.  Your PR is introduces measures that protect from a broken cookie.  

I was trying to figure out how to prevent the broken cookie.

**Comment by sbulen** [comment] 2017-10-08 16:16
I don't think the checkSession invoked during Login2 should even be making the 'session timed out' test...  You're logging in...

**Comment by sbulen** [comment] 2017-10-12 03:49
My theory...

While stepping through the logout process in the debugger, I noticed that $session_id was incorrect during logout.  It took me a while to realize that the issue was that I was not looking at the CURRENT $session_id, I was looking at the NEW $session_id.  Something is triggering the generation of a new $session_id before we are expecting it.  

So, this is what I think is going on:
  -  You are working in session 1111, the cookie settings are changed, & you log out.
  -  During logout, the $session_id is now session 2222, it is no longer working on session 1111
  -  The logic to destroySession tries to delete session 2222, which doesn't exist in the DB yet; as a result, session 1111 persists in the DB
  -  The logout process updates the member's hash salt value, used in the password hash
  -  When you logon, you are still using session 1111, which points to your member ID (not guest as expected); $user_info is populated, etc.; note even your new cookie points to session 1111 - which should have been destroyed
  -  The password check fails because it is comparing a password hashed with the new salt to a password hashed with the old salt
  -  As a result, validatePasswordFlood is called

I haven't figured out what makes it start to use the new session ID so early.

**Comment by albertlast** [comment] 2017-10-12 04:09
Since we fixed all issue around here,
i see no reason to look deeper in the code.

**Comment by sbulen** [comment] 2017-10-12 04:17
I always prefer to get to root cause.  At the very least, we are spawning unnecessary sessions.  Who knows what other issues we haven't encountered yet due to our session functions working on the wrong sessions...

**Comment by albertlast** [comment] 2017-10-12 04:20
Well i fixed the root cause, but your ignore this...

**Comment by Sesquipedalian** [comment] 2017-10-20 17:32
Reopening after reverting #4353

**Comment by sbulen** [comment] 2017-10-20 21:43
This should be resolved by #4356. 

I am out of town at the moment, but will retest upon return in a couple days.   Just to be safe, since the code in this area has been in flux.

**Comment by Sesquipedalian** [comment] 2018-01-10 11:18
After a good deal of investigation and poking around, I've found that there are *two* problems that need to be fixed in order to solve this bug. 

First, as both @sbulen and @albertlast already know, the regular expressions for testing the cookie content need to be updated to match JSON'ed rather than serialized data. 

But moreover, during my testing I kept getting other, similar errors even once the the regex was changed. This turned out to be because of a not-so-obvious bug introduced when we added support for global domain cookies. It only shows up when (1) the forum is hosted on a subdomain, (2) the "Enable local storage of cookies" option is enabled, and then (3) the admin disables that option. When this happened, our attempts to reset the cookie would fail because the domain we sent in our new cookie did not match the one in existing cookie. The browser (quite rightly) refused to change the existing cookie when it saw this mismatch.

I've put together a PR that fixes both of these problems, #4481. I ask both @sbulen and @albertlast to test it. Once it is merged, @albertlast, then perhaps you can rebase some of your other improvements onto it.

**Closed as completed** 2018-01-14 08:55 UTC
Labels: Login/Sessions
