### ISSUE TITLE
Bug with default theme options

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6205] opened 2020-07-31 01:54 UTC
#### Description
This option only shows the first post in the topic for some reason.

### Steps to reproduce
1. Go to your profile -> Look and Layout -> Board and topic Display
2. Check the box for Show most recent posts at the top in topic view.
3. Go to a topic and create a reply and when it redirects back only the first post shows of the topic.

### Environment (complete as necessary)
- Version/Git revision: 2.1 Latest
- Database Type: Mysql
- Database Version: mysql  Ver 15.1 Distrib 10.2.19-MariaDB, for Linux (x86_64) using readline 5.1
- PHP Version: 7.4

### Additional information/references

**Comment by Butterflysaway** [comment] 2020-07-31 02:08
No error messages are thrown when this occurs.

**Comment by albertlast** [comment] 2020-07-31 02:56
try this: https://github.com/SimpleMachines/SMF2.1/pull/5765

**Comment by Butterflysaway** [comment] 2020-07-31 04:33
Didn't fix the issue.

**Comment by albertlast** [comment] 2020-07-31 04:57
than i had to disable seek by desc view...

**Comment by Butterflysaway** [comment] 2020-07-31 05:02
I just removed it from my site.  I've only had to disable a few features so far due to bugs.  Not bad I guess.  Should be fully removed by the smf devs as it doesn't work anyway.

**Comment by albertlast** [comment] 2020-07-31 05:08
well the feature in general works fine, i implemented a feature to handle big threads better,
but this feater (seeking) doesn't work well with desc view.
so i had to disable this optimiztation for the case of desc view.

**Comment by SychO9** [comment] 2020-07-31 09:43
duplicate of https://github.com/SimpleMachines/SMF2.1/issues/5764

**Comment by MissAllSunday** [comment] 2020-07-31 22:40
Indeed, lets us have a single place for this issue

**Closed as completed by MissAllSunday** 2020-07-31 22:40 UTC
