### ISSUE TITLE
Installer:  Not working at all - knocked back to Welcome 

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#4483] opened 2018-01-12 03:21 UTC
I'm trying to sneak in some testing, and the installer isn't working at all at the moment.

I keep getting bumped back to Step 1 (Welcome) after completing Step 3 (Database Settings).  No error messages, nothing, just get dumped back a step or two.  

This is happening in my Windows environment (php5.6, MySql 5.7) and my unix environment (php5.6, MySql 5.5).

**Comment by sbulen** [comment] 2018-01-12 03:30
Note the upgrader works fine.  So...  If you want a current git version to test with, you gotta install 2.0.15 & upgrade it to 2.1...

**Comment by illori** [comment] 2018-01-12 11:05
does https://github.com/SimpleMachines/SMF2.1/blob/3cff847b25de82e9631fa7c883730a63dc53da92/other/install.php work for you? if so that means the recent changes broke it.

**Comment by albertlast** [comment] 2018-01-12 15:07
I tested the setup with mysql and pg and it works.

**Comment by sbulen** [comment] 2018-01-13 05:43
@illori changing that file alone does not work.  However, if I use a backup I have from 12/28 it works.  

It'd be nice if someone else could try an install.  

@albertlast  - what versions of php & mysql worked for you?  I wonder if it's a version issue.

**Comment by sbulen** [comment] 2018-01-13 05:55
Something interesting - I get the exact same results (knocked back to welcome) if I type in total random input for DB values.  It is like error reporting &/or edits are being suppressed.

**Comment by albertlast** [comment] 2018-01-13 05:58
windows php 7.2 maria 10.1
did you use maybe https while the setup progress?

**Comment by sbulen** [comment] 2018-01-13 06:00
Yes, in both environments - like normal these days.

**Comment by albertlast** [comment] 2018-01-13 06:04
try it without maybe is ther the root cause.

**Comment by sbulen** [comment] 2018-01-13 06:16
Tried it without https, same thing.

**Comment by sbulen** [comment] 2018-01-13 07:18
OK...  Brute force...   I started dropping commits one at a time, testing the install after each, until I got a clean install.  After dropping the last 7 commits, it worked.  The last working state is on Jan 5, after Colin's profile field fix.

**Comment by albertlast** [comment] 2018-01-13 07:38
So the httpsOn pr is the first how not work?

**Comment by sbulen** [comment] 2018-01-13 11:42
Yes

**Comment by albertlast** [comment] 2018-01-13 12:01
Whenn you add this changes to your install.php:
https://github.com/SimpleMachines/SMF2.1/pull/4474/files#diff-84252cd3efeb19d2101b84d40680a3d0
than the install break again?

**Comment by sbulen** [comment] 2018-01-13 16:31
If I start with the Jan 5 state (right after PR #4452), and install PR #4474 , the install cannot start.  The error message is:
`Fatal error: Call to undefined function httpsOn() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\VAN21\Settings.php on line 201`

**Comment by albertlast** [comment] 2018-01-13 16:35
this is the fix for this: https://github.com/SimpleMachines/SMF2.1/commit/fef8ec51e095de885ed8d7e48400e4fc6cedf646

**Comment by sbulen** [comment] 2018-01-13 16:37
I knew you were going to ask that, so I just installed PR #4480 .  This successfully reproduces the 'Knocked back to Welcome' issue.   

So the issue is in #4474/#4480 somewhere.

**Comment by albertlast** [comment] 2018-01-13 16:40
use a xdebug and give me feedback (i keep not able to produce the error)

**Comment by sbulen** [comment] 2018-01-13 16:47
So you know what I've tried...  Last night, I was convinced it was a version issue and did a bunch of install tests on different versions.  These all have the issue:
unix, MySql 5.5 (Percona), php5.4
unix, MySql 5.5 (Percona), php5.6
unix, MySql 5.5 (Percona), php7.0
unix, MySql 5.5 (Percona), php7.1
windows, MySql 5.7, php5.6

I can't test MariaDB or php7.2 or pg at this time.

**Comment by albertlast** [comment] 2018-01-13 16:55
this error is not related to your php and mysql version (i hope you realize that by your testing).
So you need to use a debugger and finde the place where to code get stuck.
You could place breakpoints on the header call and look which value the secure stuff got and
check if httpsOn is called (shouldn't but maybe it's called..)

**Comment by Sesquipedalian** [comment] 2018-01-13 18:33
What happens if you replace `$secure` with `$httpsOn` in Settings.php? Normally, variable names are irrelevant, but `ForumSettings()` in install.php defines a local-scoped `$secure` before including Settings.php, where `$secure` has a global scope. I wouldn't think that should break anything, but... maybe?

**Comment by albertlast** [comment] 2018-01-13 18:41
since the code reset the var to false everytime,
i miss on imagination that this solve the issue

**Comment by sbulen** [comment] 2018-01-13 19:28
The new code in Settings.php is definitely part/all of the problem.  If I change that back to the way it was, the problem goes away.  

I don't know _why_ it is causing the problem...   But it is.  

The DatabaseSettings() ends up being called a couple of times after you enter DB info and press Continue.  The call to "make sure it works" here returns properly the first time, but the second time thru, you end up starting all over:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/other/install.php#L817

**Comment by Sesquipedalian** [comment] 2018-01-13 19:36
I'm surprised that line uses `require()` rather than `require_once()`. What happens if you change that?

**Comment by sbulen** [comment] 2018-01-13 19:40
In the installer, Settings.php is updated & re-invoked a few times, each time with more settings set.  As it goes along, it gets more complete depending on the step of the install.  

I.e., you don't want a require_once.

**Comment by Sesquipedalian** [comment] 2018-01-13 19:45
Fair enough.

**Comment by sbulen** [comment] 2018-01-13 20:27
I'm tied up for most of the day - I may be able to take another quick peek tonight, but I'll be out of town for at least a couple days after that.   

I.e., someone else may need to pick this up.

**Comment by sbulen** [comment] 2018-01-14 05:45
**_Here's the problem..._**   

The 'if file exists install.php' logic in settings.php is a special redirect that is ONLY INTENDED TO BE EXECUTED ONCE.  It is then deleted by updateSettingsFile().   Look at the logic at the top of the special install.php version of updateSettingsFile that does this, ~line1766:
https://github.com/SimpleMachines/SMF2.1/blob/5c1955aece013ab3d79e12dc5a4b0c7603041cf6/other/install.php#L1766

The new logic doesn't match the old one, so it is not properly detected & deleted.  In DatabaseSettings() near 'make sure it works', install.php ~L817 invokes settings.php again, but since the redirect logic wasn't deleted, the redirect is invoked and you're back at step 1 all over again.  This is why it happens after entering the DB params.  

**_To fix:_**
Multiple possible fixes.  The most obvious one is to fix the logic in updateSettingsFile to recognize and erase the new version of the redirect.  It's not getting detected & deleted because it uses more lines than the old one...    

I'd prefer removing the redirect from settings.php altogether.  If it is only supposed to run once during install, why not just put it early in install.php?

**_To reproduce:_**
I'm not sure why you couldn't reproduce the error - it'll happen every time.  My only guess is that you didn't actually copy the _new, fresh & empty_ settings.php along with the install*.* files from the /other directory as intended prior to installation.  If you "reused" a settings.php file, with the DB settings already set, you will not see this happen, because the installer doesn't need to make all the same updates to settings.php.  

I will leave this to others to fix - mainly because I'm heading out of town shortly & will only have my phone, not my computer.

**Comment by albertlast** [comment] 2018-01-14 07:10
i only move the install.php and db related install file from other and
delete the settings.php in the root dir.
The setup create then a mucht smaller settings.php by his own,
as this in other directory.

Installer created settings.php: https://pastebin.com/m7SmxmEY
vs settings.php in other: https://pastebin.com/wa06mnyS

**Comment by Sesquipedalian** [comment] 2018-01-14 07:35
Good detective work, @sbulen.

**Comment by sbulen** [comment] 2018-01-14 09:58
Without copying settings.php,  you're not emulating what the actual install package will be like.  Your test is incomplete.

There might - hypothetically speaking - be a change someone makes to settings.php itself that needs testing.

**Closed as completed** 2018-01-17 06:51 UTC
Labels: Installer
