### ISSUE TITLE
issues with merging topics

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2765] opened 2015-03-08 11:10 UTC
http://www.simplemachines.org/community/index.php?topic=534371.0

seems that when you merge topics the count on the board index may be incorrect for number of topics in the board.

depending on number of topics, this may make the board show as having no topics at all.

seems that after the merge the number of topics in the board [if both topics in the same board] go down by 2.

**Comment by margarett** [comment] 2015-03-09 22:10
I'm trying to follow this but it seems that the maths are wrong... It scrambles both the count of topics in boards as well as replies topics. Odd...

**Comment by margarett** [comment] 2015-03-09 23:26
Yeah, the issue is quite clear. But the code is pretty much the same as in 2.0 in this point so I still can't tell what causes it...

Gotcha, but I'm still failing the maths :tongue: 
WITHOUT redirection topic, moving in the same board, 2 topics are discounted in board totals, then removeTopic removes another one, when only 1 should be discounted in total...

margarett continues to talk to himself :laughing:  (missing the /me BBC here ehehehehe)

**Comment by illori** [comment] 2015-03-10 00:43
does it have to do with the fact that in 2.0 there was never a redirection topic for merging topics?

**Comment by margarett** [comment] 2015-03-10 00:55
Yes. The code changes in the function are related to that. But the maths are just weird :P 
The call to removeTopic is new in 2.1, and is responsible for an extra removal. Yet, there is still another topic count lost somewhere...
Now I just turned off the computer, will think about that later :)

**Comment by margarett** [comment] 2015-03-21 01:15
Looking at this again. I'll be damned if I understand how the maths work in this function :tongue:

**Comment by FearThe1337** [comment] 2015-05-22 12:13
Busy working on this. There are indeed multiple things wrong. (Hope to have a fix for most of it in the next few days).
Some statistics are removed double... and some are being removed while they should not be removed.

**Comment by FearThe1337** [comment] 2015-05-22 14:16
Submitted [PR 2869](https://github.com/SimpleMachines/SMF2.1/pull/2869) for this. (Ignore first commit mentioned in this issue, the whitespace was spaces instead of tabs, and was fixed in the second commit)

**Closed as completed** 2015-05-29 22:42 UTC
