### ISSUE TITLE
Emulation Support

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#2899] opened 2015-06-11 21:30 UTC
I was playin with the package manager and went to emulation support. This is what mine looks like. It's not supposed to be like that:
![screenshot-www smfhelper com 2015-06-11 17-29-03](https://cloud.githubusercontent.com/assets/3620111/8118857/8d00ac60-105f-11e5-8453-005d21a344d0.jpg)

**Comment by illori** [comment] 2015-06-12 14:22
i can duplicate this issue. using the revert link does not correctly revert the field.

i wonder if because http://www.simplemachines.org/smf/latest-versions.txt has not been updated to include beta 2 this is happening. you are using the beta 2 from github? maybe we can ask the site team to update that file as that is what stores that list and see if that fixes the issue?

**Comment by smfbigguy** [comment] 2015-06-12 21:04
I am using beta 2 yes.

**Comment by illori** [comment] 2015-06-13 10:45
seems that there is an issue with the emulate_versions array, when SMF Beta 2 is missing from the list the array does not have the right number of keys in it.

```
Array
(
    [0] => 2.0 RC2
SMF 2.0 RC3
SMF 2.0 RC4
SMF 2.0 RC5
SMF 2.0
SMF 2.0.1
SMF 2.0.2
SMF 2.0.3
SMF 2.0.4
SMF 2.0.5
SMF 2.0.6
SMF 2.0.7
SMF 2.0.8
SMF 2.0.9
SMF 2.0.10
SMF 2.1 Beta 1
)
```

instead of 

```
Array
(
    [0] => 2.0 RC2
    [1] => 2.0 RC3
    [2] => 2.0 RC4
    [3] => 2.0 RC5
    [4] => 2.0
    [5] => 2.0.1
    [6] => 2.0.2
    [7] => 2.0.3
    [8] => 2.0.4
    [9] => 2.0.5
    [10] => 2.0.6
    [11] => 2.0.7
    [12] => 2.0.8
    [13] => 2.0.9
    [14] => 2.0.10
    [15] => 2.1 Beta 1
    [16] => 2.1 Beta 2
)
```

the code does not know how to handle the drop down box with the first array.

**Comment by MissAllSunday** [comment] 2015-06-16 16:21
It is indeed caused by Beta 2 been missing from that file.

Code can be added to prevent this:

``` php
    $context['default_version'] = preg_replace('~^SMF ~', '', in_array($forum_version, $context['emulation_versions']) ? $forum_version : end($context['emulation_versions']));
```

But it will cause some confusion among users, plus, this will only happen until 2.1 reaches a stable release, after that, releases will not be that frequent and that latest-file will be updated before an actual release is made.

**Comment by live627** [comment] 2015-07-20 00:52
Is this still an issue?

**Comment by illori** [comment] 2015-07-20 09:16
yes still an issue, the file above has not been updated to include beta 2.

**Comment by live627** [comment] 2015-07-20 23:12
I have no idea which file it is... is it on the sm server?

**Comment by illori** [comment] 2015-07-21 00:45
yes, it is the file i linked above. i also posted to the site team to update the file.

**Comment by jdarwood007** [comment] 2015-07-23 00:43
How would the developers like to fix it?

We used to not list any beta/dev versions in things like latest-versions and other information files from our site.

The correct fix should be in the code, but we can add beta 2 easily to the site.

**Comment by live627** [comment] 2015-07-23 01:15
>  we can add beta 2 easily to the site.

Do it..

**Comment by Oldiesmann** [comment] 2015-07-23 14:01
Beta 2 has been added to the site now (I meant to do it prior to the release but overlooked it somehow). We can look into adding code to prevent these problems in the future as well.

**Comment by smfbigguy** [comment] 2015-07-24 02:02
Well, I just installed the latest from here about an hour ago and this is not fixed yet. What are the strange characters right at the start, lol. 
![screenshot-www smfhelper com 2015-07-23 22-01-11](https://cloud.githubusercontent.com/assets/3620111/8866110/86eae69a-3186-11e5-9e45-cce541aadf1e.jpg)

**Comment by smfbigguy** [comment] 2015-07-24 02:47
Also when installing a mod I no longer get a server error as I reported before. I get an error that tells me a backup could not be made...going back a page and trying again to install the same package resolves this and the package installs fine.

**Comment by illori** [comment] 2015-07-24 10:34
looks like this file has an empty line below the beta 2 line, this is breaking the drop down.

if the empty line is removed there is no problem.

**Comment by Oldiesmann** [comment] 2015-07-27 16:29
Not sure how that blank line got in there, but it should be fixed now, and you'll see a fix whenever the "Fetch Simple Machines Files" task is run again.

**Comment by illori** [comment] 2015-07-27 20:23
i dont know why but this seems to still add something that is breaking the function at the end of the Beta 2 line... if you delete that line and type it again in the database the drop down goes back to normal.

**Comment by NanoSector** [comment] 2015-07-28 14:50
It does not properly split it by line endings. It expects /r/n but does not always get that.

I've almost fixed this.

**Comment by Oldiesmann** [comment] 2015-07-30 16:57
I've been editing the file on Linux, so it should have UNIX line endings if that makes any difference.

**Closed as completed** 2015-07-30 18:04 UTC
Labels: Package Manager

**Comment by Oldiesmann** [comment] 2015-07-30 18:05
The weird character at the beginning was a Byte Order Mark which apparently KWrite adds by default, but the code has been changed to use a different format so we don't have to worry about different line endings.
