### ISSUE TITLE
[3.0]: Avatar changing

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#8023] opened 2024-01-16 04:03 UTC
### Basic Information

When trying to use a SVG for a avatar, a fatal PHP error occurs and the avatar is not saved

### Steps to reproduce

1. Go to Forum Profile
2. Choose an external image
3. Enter: https://www.php.net/images/logos/php-logo-white.svg

### Expected result

Forum Profile is saved and avatar changed

### Actual result

Fatal PHP error

### Version/Git revision

3054fc2

### Database Engine

All

### Database Version

N/A

### PHP Version

8.1.24

### Additional Information

@Sesquipedalian I'm seeing multiple avatar-related issues.  Not just this one, but its the one I'm not certain on how we intend to fix, since we are passing things through Image handler and then trying to use $image->type, which is not defined.

**Comment by jdarwood007** [comment] 2024-01-16 04:30
Changing the title here.  I found a few more problems

- Can not use a webp image.
- When you do set an image, the preview seems to be 'sticky' for that page load and does not refresh until the next page load
- The avatar does not detect which type was set correctly.

**Comment by frandominguezl** [comment] 2024-05-22 20:16
I couldn't reproduce with the latest build

SVG test:
![imagen](https://github.com/SimpleMachines/SMF/assets/10365222/9fb452b2-cbb3-4f98-8814-7abe4dd57cfb)

Webp test:
![imagen](https://github.com/SimpleMachines/SMF/assets/10365222/19ea0279-d646-48a9-8c32-258e0aaa9435)
_Test image: https://tmpr.s3.eu-central-1.amazonaws.com/assets/imgs/webp-test.webp_

**Comment by DiegoAndresCortes** [comment] 2024-05-23 02:13
Maybe #8226 fixed this too?

**Comment by Sesquipedalian** [comment] 2024-05-23 04:41
> Maybe #8226 fixed this too?

Maybe. At any rate, it seems that we can close this.

**Closed as completed by Sesquipedalian** 2024-05-23 04:41 UTC
Labels: Avatars
