### ISSUE TITLE
here a todo..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#2521] opened 2014-11-23 20:05 UTC
for local cookies...

in Session.php:
    // @todo Set the session cookie path?
    if (!empty($modSettings['localCookies']))
    @ini_set('session.cookie_path', $parsed_url['path'] . '/');

works..

But .. I don't know how the template return a false even if the ckeckbox ckecked...

**Comment by Dragooon** [comment] 2014-11-26 15:45
This is a direct duplicate of #2516, post it there.

**Closed as completed by Dragooon** 2014-11-26 15:45 UTC
