### ISSUE TITLE
URL parser doesn't recognize some .example URLs

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7576] opened 2022-10-25 18:08 UTC
#### Description
If I [post](https://www.simplemachines.org/community/index.php?topic=583784.msg4137766#msg4137766) something like "`https://forum.my.example`", the auto-linker writes this code:
```
<a href="https://forum.my" class="bbc_link" target="_blank" rel="noopener">https://forum.my</a>.example
```

I tried to reproduce this with other obscure/long TLDs (like `.blackfriday`), but only `.example` seems to be affected.

These work (the final slash, added by my Chromium browser during c&p, indicates where the autolinker ends the link):
* https://foo.example/
* https://www.example/

These don't work (the final slash, added by my Chromium browser during c&p, indicates where the autolinker ends the link):
* https://foo.bar/.example
* https://www.foo/.example
* https://www.foo.bar/.example

### Steps to reproduce
1. See above

### Environment (complete as necessary)
- Version/Git revision: Whatever currently runs on SMorg
- Database Type: Whatever currently runs on SMorg
- Database Version: Whatever currently runs on SMorg
- PHP Version: Whatever currently runs on SMorg

### Additional information/references

**Comment by Sesquipedalian** [comment] 2022-10-26 08:21
Yes, `example` should be added to this short list of special use domain names that the autolinker supports:
https://github.com/SimpleMachines/SMF/blob/ee2af858718a640edf626cc50879ec65962516eb/Sources/Subs.php#L7462-L7464

FYI, the reason it wasn't included in that list before now is that `.example` does not exist in DNS and will not resolve. Since the autolinker was designed to recognize valid URLs, it has only ever supported TLDs that are on the [official list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt) of top level domains in DNS and those few special use domain names that have a decent chance of resolving. But I suppose the `.example` TLD deserves to be linked as well, despite the fact that it doesn't resolve.

**Comment by Sesquipedalian** [comment] 2022-10-26 09:42
Actually, on further consideration, I think the correct behaviour would be to *not* autolink the URL at all if the top level domain name is an unresolvable, reserved domain like `example` or `invalid`. These are intentionally unresolvable and therefore are not supposed to be used in active links.

**Comment by m4z** [comment] 2022-10-26 09:50
That works for me too. All I care about that the linking isn't partial. :sweat_smile:

**Closed as completed** 2022-12-20 02:54 UTC
Labels: Parsers (BBC/Markdown)
