### ISSUE TITLE
Global variables in Settings.php?

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#4281] opened 2017-09-03 19:23 UTC
Re. https://github.com/SimpleMachines/SMF2.1/pull/4275#issuecomment-326824379

Maybe we should global variables inside Settings.php? Reason I didn't make a PR yet is because it'll likely break all older SMF installs if we do this.

**Comment by Sesquipedalian** [comment] 2017-09-03 23:00
They already are global. :)
https://github.com/SimpleMachines/SMF2.1/pull/4275#issuecomment-326837163

**Comment by NanoSector** [comment] 2017-09-03 23:11
I think you should wait before closing this issue as it is genuinly something I believe we should think about. As I explained in my followup comment https://github.com/SimpleMachines/SMF2.1/pull/4275#issuecomment-326837281 it depends on where you actually include Settings.php. If it's inside a function, its variables are only available inside that function.

Therefore, under specific circumstances, variables aren't available where you'd expect them. Adding globals to Settings.php solves this and makes it so it doesn't matter where you include it, the variables will be global.

**Comment by sbulen** [comment] 2017-09-03 23:18
Like $cookiename?   It is already in settings.php...

Even variables in settings.php (like $boardurl) must be "exposed" to a function via declaring it global.    

In a train now, but IIRC, I think the only true globals in php must be static.

**Comment by Sesquipedalian** [comment] 2017-09-03 23:30
Settings.php is included using require_once as one of the very first things that happens in index.php. PHP is in the global scope at that point in index.php, and as the PHP documentation notes, all the variables brought in from Settings.php by the include are also put in the global scope. The issue in #4275 was simply that any global variable needs to be declared as such within a local context if you want access to it.

**Comment by NanoSector** [comment] 2017-09-03 23:46
Yes, in index.php this is the case. However the issue that was fixed with the mentioned PR has a case where it is not included in global scope and therefore caused issues. I’m willing to bet it is not the only occurrence of such scenario in SMF, so either we properly identify and document them or we implement globals inside settings.php.

Van: Jon Stovell
Verzonden: maandag 4 september 2017 01:30
Aan: SimpleMachines/SMF2.1
CC: NanoSector; Author
Onderwerp: Re: [SimpleMachines/SMF2.1] Global variables in Settings.php? (#4281)

Settings.php is included using require_once as one of the very first things that happens in index.php. PHP is in the global scope at that point in index.php, and as the PHP documentation notes, all the variables brought in from Settings.php by the include are also put in the global scope. The issue in #4275 was simply that any global variable needs to be declared as such within a local context if you want access to it.

**Comment by sbulen** [comment] 2017-09-03 23:47
The mystery here, is why $cookiename had to be added back to solve this issue.  **_$cookiename is not referenced anywhere within the function in question.  THAT is that part that confuses me..._**   

Why, exactly, did $cookiename have to be added back?   

I've seen this elsewhere, e.g., #4103 had to fix a few of them.

**Comment by NanoSector** [comment] 2017-09-03 23:50
$cookiename is used in setLoginCookie later in that function, but it is never globalled properly.

Van: sbulen
Verzonden: maandag 4 september 2017 01:47
Aan: SimpleMachines/SMF2.1
CC: NanoSector; Author
Onderwerp: Re: [SimpleMachines/SMF2.1] Global variables in Settings.php? (#4281)

The mystery here, is why $cookiename had to be added back to solve this issue. $cookiename is not referenced anywhere within the function in question. THAT is that part that confuses me...
Why, exactly, did $cookiename have to be added back?
I've seen this elsewhere, e.g., #4103 had to fix a few of them.

**Comment by sbulen** [comment] 2017-09-03 23:56
Actually, that's incorrect.  $cookiename is not referenced in the call to setLoginCookie:

```
	// Automatically log them in ;)
	if (isset($incontext['member_id']) && isset($incontext['member_salt']))
		setLoginCookie(3153600 * 60, $incontext['member_id'], hash_salt($_POST['password1'], $incontext['member_salt']));

```

It is used _within_ setLoginCookie, and it is properly declared as a global in setLoginCookie...   

So...  Why did $cookiename need to be added back?   If you open install.php, and so a search, the ONLY reference to $cookiename in the entire sourcefile is that global declaration.  Which is NOT used in install.php...  It is used in a function called by install.php...

**Comment by NanoSector** [comment] 2017-09-04 00:03
it had to be added because just including Settings.php doesn't move it into global scope. setting it to be global BEFORE including the file makes it so that when it's included (and therefore placed into the function scope) it gets globalled from the function scope and thus it becomes a proper global. if we don't do this it'll just stay within function scope and never gets moved to global, which causes setCookieName to get confused in the end.

**Comment by sbulen** [comment] 2017-09-04 00:14
Yep, I get it now!   Thanks...   The problem isn't that $cookiename isn't used...  The problem is that it was never made global....

Bear in mind that the installer is *creating* all the relevant settings.php entries, so it has a bunch of "bootstrap" code...  Unlike the rest of SMF, the installer doesn't have the luxury of running settings.php every cycle.  It can only do so in the last couple of install steps, after settings.php has been created/updated.  

But you are correct, for any of those variables to become global, they needed to be declared global within the step that called settings.php.  Installer is the perfect example.

I understand your concern now...   Interesting thought, would declaring them global simply within settings.php avoid all such quirky issues down the road?   Probably...

**Comment by sbulen** [comment] 2017-09-04 00:27
But what about the two other examples in PR #4104 ...

One is $txt, in a function that loads the language file.  Following your logic, should the language file itself make $txt global instead?   

The other is the need for $db_connection in forum_settings()...  That one still confuses me, I'm not sure it follows the model above...

**Comment by Sesquipedalian** [comment] 2017-09-04 00:28
> Yes, in index.php this is the case. However the issue that was fixed with the mentioned PR has a case where it is not included in global scope and therefore caused issues. I’m willing to bet it is not the only occurrence of such scenario in SMF, so either we properly identify and document them or we implement globals inside settings.php.

It isn't an issue anywhere in SMF's normal operation. Settings.php is included by both index.php and SSI.php in the global scope, so all it's variables are available in the global scope. Upgrade.php likewise includes Settings.php in the global scope, so the situation is the same there. In each of these cases, there is no need to check for anything else, because the scope for the Settings.php variables is set by that first inclusion.

The only exception is in install.php (which I now realize is what you were talking about; _mea culpa_). There Settings.php is included only inside various functions. But there are reasons for that, as @sbulen noted in his comment above, so I don't think we should mess with the way it is handled there, either.

EDIT: Removed a bit where I second-guessed myself when I shouldn't have. :blush:

**Comment by sbulen** [comment] 2017-09-04 01:01
Actually, I just checked in a debugger...  

Sesquipedalian is correct - Upon execution of the require_once in index.php, all values in Settings.php are globals.  

I don't think I've seen this doc'd anywhere.   I don't know WHY they are global, without an explicit global declaration anywhere.  Are any variables created in index.php automatically global?  

Thus...  I now agree with Sesquipedalian, this could be closed.   install.php is a special case, for the reasons cited above.

**Comment by Sesquipedalian** [comment] 2017-09-04 07:01
> I don't think I've seen this doc'd anywhere. I don't know WHY they are global, without an explicit global declaration anywhere. Are any variables created in index.php automatically global?

It's simply that, in PHP, variables defined in the global scope (i.e. not inside of a function) are by definition global variables. You can check out http://php.net/manual/en/language.variables.scope.php and http://php.net/manual/en/function.include.php if you want to dig a little deeper. :)

**Closed as completed by Sesquipedalian** 2017-09-04 07:01 UTC

**Comment by NanoSector** [comment] 2017-09-04 14:46
I never disagreed that the require_once in index.php did global the variables. The only reason I brought up this issue is so that we could check if any other occurrences of including settings.php in a function scope should be fixed.

**Comment by Sesquipedalian** [comment] 2017-09-04 18:56
A grep search across the code base for 'Settings.php' reveals that install.php and proxy.php are the only files where Settings.php is included within a local scope. Everywhere else it happens in the global scope. Since those two exceptions are both appropriate and both work, I think everything is fine. :)
