### ISSUE TITLE
Confusion of terms "watch" and "follow", and reference to a "notify" button that does not exist

### ISSUE THREAD

**Issue by AngelinaBelle** [SimpleMachines/SMF#1839] opened 2014-06-19 10:58 UTC
To avoid confusion, we should use one term to describe watched or followed topics or boards.

Should it be "watched" or "followed"?
- In the notifications portion of the user profile, the term"follow" is used -- but there is no "follow" button for the user to use.
- the SA has the title "watched topics"
- the user starts watching/following by using a button labeled "watch" topic or board.
- The helpful text at the bottom "watched topics" says  "To receive notifications from a topic, click the "notify" button while viewing it." But there is  no notify button.

**Comment by illori** [comment] 2014-06-19 19:21
basically a duplicate of #1320

**Comment by AngelinaBelle** [comment] 2014-06-19 19:30
Possibly. I was initially thinking only about fixing the strings. discussion at 
http://www.simplemachines.org/community/index.php?topic=524062.0

**Comment by Dragooon** [comment] 2014-06-20 13:43
Closing

**Closed as completed by Dragooon** 2014-06-20 13:43 UTC
