### ISSUE TITLE
0001696: [Paid Subscriptions] prices don't use the correct decimal separator

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1777] opened 2014-06-07 20:06 UTC
The prices shown in the paid subscriptions templates don't use the number format as set in the number_format setting.

Ref: http://dev.simplemachines.org/mantis/view.php?id=1696

**Comment by Oldiesmann** [comment] 2014-06-11 19:30
So basically it should use the decimal separator specified in the admin center rather than whatever the appropriate one is for the system's locale? (SMF currently uses sprintf() to format the prices, and PHP says that it's "locale aware", so it uses the default system locale since SMF doesn't specify one).

**Comment by sbulen** [comment] 2017-03-08 17:35
I believe this was raised again more recently & is now a dupe of: Allow decimals in Paid Subscriptions? #3764

**Comment by sbulen** [comment] 2017-03-30 01:48
As a dupe, I think this can be closed.

**Comment by frandominguezl** [comment] 2017-08-22 11:29
@Antes can you close this? We can keep on the discussion in #3764 as Mantis is not used anymore

**Closed as completed** 2017-08-22 11:53 UTC
Labels: Paid Subs
