### ISSUE TITLE
Upgrade from 2.0 : error to CREATE INDEX idx_likes in MyISAM engine

### ISSUE THREAD

**Issue by gayratv** [SimpleMachines/SMF#6083] opened 2020-04-24 18:50 UTC
#### Description
--during Upgrade from 2.0 : error to CREATE INDEX idx_likes in MyISAM engine--

### Steps to reproduce
1. php upgrade.php
2.  smf_messages have ENGINE  MyISAM, cp1251_general_ci collation

during upgrade I', see sql command:
CREATE INDEX idx_likes ON smf_messages (likes DESC)

MySQL Error:
#1178 - The storage engine for the table doesn't support descending indexes

Please, remove index creation with DESC argument.
I'm fix this problem to move table to InnoDB, but my table have 1.5 million records and InnoDb is not good choice in my case

### Environment (complete as necessary)
- Version/Git revision:2.1  Latest commit c09c8c9
- Database Type: MySQL
- Database Version: 8
- PHP Version: 7.3.

### Additional information/references

**Comment by sbulen** [comment] 2020-04-24 19:03
This one is a dupe of #6066

**Closed as completed** 2020-04-24 20:11 UTC
Labels: Upgrader
