### ISSUE TITLE
(Incompletely configured) Paid subs errors use language of the user in error log

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7812] opened 2023-07-30 14:20 UTC
#### Description
If Paid Subscriptions are configured incompletely (for example, generally enabled, but no PayPal address set), whenever a user accesses the "Paid Subscriptions" menu (that this is visible might also be considered a bug) from either the user drop-down or the "Actions" tab in the Profile view, the following error is displayed to the user in the language that the user has configured (which is as expected):
> Der Administrator hat die Einstellungen für Bezahl-Abonnements noch nicht festgelegt – bitte versuchen Sie es später noch einmal.

In English, that's:
> Sorry, the admin has not yet finished setting up paid subscriptions. Please check back later.

However, the same error, also in the language of the user that triggered the error, is displayed in the ACP error log:
> [username]
> [user IP address]
> [hex string]
> https://[myforum]/index.php?action=profile;area=subscriptions;u=[user id]
>
> Type of error: General
> Error message
> Der Administrator hat die Einstellungen für Bezahl-Abonnements noch nicht festgelegt – bitte versuchen Sie es später noch einmal.

Backtrace:
> Backtrace information
> 0: fatal_error()
Called from […]/Sources/Profile-Actions.php on line 771 / https://[…].de/index.php?action=admin;area=logs;sa=errorlog;file=[A-Za-z0-9]+==;line=771
> 1: subscriptions()
> Called from […]/Sources/Profile.php on line 818 / https://[…].de/index.php?action=admin;area=logs;sa=errorlog;file=[A-Za-z0-9]+=;line=818
> 2: ModifyProfile()
> Called from […]/index.php on line 184 / https://[…].de/index.php?action=admin;area=logs;sa=errorlog;file=[A-Za-z0-9]+==;line=184

### Environment (complete as necessary)
- Version/Git revision: 2.1.4
- Database Type: Postgres (but probably any)
- Database Version: 13.11ish (but probably any)
- PHP Version: 7.4 (but probably any)

**Comment by DiegoAndresCortes** [comment] 2023-07-30 18:59
Maybe related to #4066 ?

**Comment by Sesquipedalian** [comment] 2023-07-30 19:36
Duplicate of #4066.

**Comment by Sesquipedalian** [comment] 2023-07-30 19:38
GitHub's phone app is a bit goofy about closing issues, it seems...

**Closed as not planned** 2023-07-30 19:38 UTC
