### ISSUE TITLE
2.1 RC3 Upgrade changes group properties

### ISSUE THREAD

**Issue by LexArma** [SimpleMachines/SMF#6318] opened 2020-10-24 18:40 UTC
#### Description
Having a variety of different types of groups on 2.0, I noticed upgrade to 2.1 changed the properties of some (not all) of the groups. Groups changed from private to requestable, from requestable to free for example. Sadly, I have no definitive map of changes that happened, so hard to narrow this one down. All I can say for certainty is that I had to redefine most of my groups. 

### Steps to reproduce
1. Have groups of all different access levels in 2.0
2. Upgrade to 2.1
3. Find out some of these levels have changed. 

### Environment (complete as necessary)
- Version/Git revision: Update from 2.0.17 to 2.1 RC3 public
- Other details can be hunted down if needed, but I don't have much at hand at the moment.

### Additional information/references
- Original DB clone still available, the result DB in use and errors manually fixed so a direct copy of results not available anymore.

**Comment by sbulen** [comment] 2020-10-26 19:06
Yikes...  

I haven't been able to reproduce this.  Membergroup types seem to stay in sync.  

Still trying, will go for more groups & more complexity...

**Comment by sbulen** [comment] 2020-10-26 19:10
This looks like a likely culprit, might be getting executed more than once:
https://github.com/SimpleMachines/SMF2.1/blob/265ae25671c5a2ec5c6adf6a6dada7b03d4bbc77/other/upgrade_2-0_mysql.sql#L3025

**Comment by sbulen** [comment] 2020-10-26 19:20
Lex - 
What is the history of the forum?  Did it start as 1.0 or 1.1?  Or was it migrated from another platform to 2.0.x?  (The latter would explain things, I think...)

**Comment by LexArma** [comment] 2020-10-26 20:12
A very long and multi part history. Originally from an unknown version of SMF on Xsorbit,  imported to 1.1.something then gradually patched to latest 1.1, then upgraded to 2.0 RC something, then patched to 2.0.17, now upgraded to 2.1 RC3. 

I have no idea what exactly caused it, but more than one or two groups changed - luckily I noticed fast, as some groups suddenly appeared in my group legend on the front page (groups such as "ban test grp" :P )

There is of course the possibility that something was just a bit off in just the right way for this to be some random fluke - but ...

**Comment by sbulen** [comment] 2020-10-26 22:36
OK, reviewing code, including early 2.0 RC, late 2.0 RC, and current 2.0 upgrade packages, this is what I think happened...  (Sometimes I feel more like an archeologist than a dev...)

The group_types changed between 1.1 & 2.0...  The 2.0 step in the upgrader checks to see if the group_type for the admin group (id_group = 1) is 1.  If so, it figures you are under the 2.0 regimen and leaves you alone.  If not, it assumes you are in the 1.1 regimen, and renumbers some of the group_types by adding 1 to them...    This is clearly something you don't want to do twice...

But you ran the upgrader, way back when, to get to a 2.0 RC.  But...  And I just checked this...  The early 2.0 RC upgraders did not have this step.  The earliest version of the group_type fix is in 2.0 RC4.  

So...  My guess at this point is that your admin group (id = 1) before the 2.1 RC3 upgrade had a value in group_type that was not = 1.  You probably edited the membergroups in 2.0 to make them work correctly in 2.0 nonetheless.  Happy as a clam for years.  Then, the 2.1 RC3 upgrader came along and realized you didn't have the fix applied, so it applied the "fix" for you, changing some of the types...  How thoughtful...

I believe this can happen to others who upgraded from 1.x prior to 2.0 RC4.  

My recommendation for a fix is to NOT increment the group_types if the forum's version is anywhere in the 2.0 realm...  Assume 2.0 folks are solid.  Only tweak the group_types if coming from 1.x.  This should be in the 2.0 & 2.1 code for the 2.0 upgrade step.

**Comment by LexArma** [comment] 2020-10-27 04:51
This sounds plausible. I sadly don't have much records on what I've done along the way, but could be just what happened. If a fix is needed, and if that's the way to fix it -  I'll leave that up to you. :)

**Comment by live627** [comment] 2021-02-08 10:10
@LexArma do you still have your db backup from 2.0? Can you check the group type of id_group 1? It should be `1`, but might be `0`.

**Comment by LexArma** [comment] 2021-02-08 14:07
I should have the backup still, yes. I'll get back to you once I can dig around a bit, probably in the next couple of days.

**Comment by LexArma** [comment] 2021-02-09 06:26
It does look like membergroups ran from 1 to 36, and Admin was group_id 1. But group_type was 0, just as sbulen guessed.

**Comment by live627** [comment] 2021-02-09 07:21
Then here's what    I think  happened: 2.0 RC4 introduced protected groups which pushed requestable from 2 to 3 and free from 3 to 4 (I'm probably off by one). That upgrader step executed  on your end because your admin group wasn't protected.

This will only happen on installations that used the 2.0 betas that didn't run the upgrader when they updated to RC4.

**Comment by LexArma** [comment] 2021-02-09 15:28
I do find it somewhat odd that I would have skipped an upgrader, even by mistake, but it's not completely impossible. So that definitely is an alternative for what might have happened.

**Comment by sbulen** [comment] 2021-02-11 06:38
> I do find it somewhat odd that I would have skipped an upgrader, even by mistake, but it's not completely impossible. So that definitely is an alternative for what might have happened.

You didn't skip one.  The pre RC4 upgraders didn't have the fix.  You probably had to do a minor tweak by hand to get things to work.  The 2.1 upgrader saw a clue that made it think you still had 1.1 groups, & it maliciously helped you...

**Comment by sbulen** [comment] 2021-02-11 19:04
One major clarification learned while testing: 1.x didn't have group_types at all.  These were introduced in 2.  This specific fix that caused an issue here - incrementing the group types - is specific to 2.0 versions prior to 2.0 RC4.

**Closed as completed** 2021-02-15 20:43 UTC
Labels: Upgrader
