### ISSUE TITLE
3.1

### ISSUE THREAD

**Issue by ghost** [SimpleMachines/SMF#7895] opened 2023-11-22 01:32 UTC
#### Description
Cannot find database source script! Please check file Db/APIs/mysql.php is within your forum source directory.
It's installed the same as I've always done my upgrades.

### Steps to reproduce
1.  Fresh Install
2.  Try to Install

### Environment (complete as necessary)
- Version/Git revision: [d7f5e0d](https://github.com/SimpleMachines/SMF/commit/d7f5e0db6ada87be2713b41088709edd99335a1e)
- Database Type: MySQL 8.0
- Database Version: MySQL 8.0
- PHP Version: 8.2

### Additional information/references

**Comment by jdarwood007** [comment] 2023-11-22 02:20
Duplicate of #7849

**Closed as completed** 2023-11-22 03:00 UTC
Labels: Installer

**Comment by ghost** [comment] 2023-11-22 17:34
still does'nt work

**Comment by Sesquipedalian** [comment] 2023-11-23 22:23
We didn't close this report because the problem is fixed. We closed it because it is a duplicate of another issue report, and we don't need multiple reports for the same issue.

**Comment by ghost** [comment] 2023-11-30 03:43
okay
