### ISSUE TITLE
Members receiving Likes when turned off

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5465] opened 2019-02-25 19:27 UTC
RC1

With all alert settings unchecked, regular members still receive likes form admin, and other members.

**Comment by SychO9** [comment] 2019-05-30 14:54
I can't reproduce this, @lurkalot are you editing the notification settings from the admin panel or are you editing your own notification settings ?
Also did you test with a more recent version ?

**Comment by lurkalot** [comment] 2019-05-30 18:18
It might well be sorted now, I'll have to check and see if it's still happening for me..

**Comment by SychO9** [comment] 2019-08-10 12:39
bump !

@lurkalot can you please check again ?

**Comment by lurkalot** [comment] 2019-08-10 17:51
Sorry missed this and your previous comment.   I have now unchecked everything in my alert settings over at Bigguy's site which is where it was happening.  Just need to wait now and see what happens.

**Comment by lurkalot** [comment] 2019-08-14 07:54
As far as I can see it's working as expected now.  So looks like it's fixed.

**Comment by SychO9** [comment] 2019-08-14 10:12
Okay, Thank you I've never been able to reproduce it either, so feel free to close this.

**Closed as completed** 2019-08-15 06:55 UTC
Labels: Notifications
