### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#4702] opened 2018-04-06 01:12 UTC
As of this post I have upgrade to the latest GH ver. Please see post at SMF. Spell check does not work right

https://www.simplemachines.org/community/index.php?topic=542792.msg3968271#msg3968271

**Comment by albertlast** [comment] 2018-04-07 05:34
did you see here a red text like shown in the pic?
![grafik](https://user-images.githubusercontent.com/1782906/38451774-271507e4-3a36-11e8-89a9-9d1120181151.png)

**Comment by smfbigguy** [comment] 2018-04-07 13:21
Yes I saw that and as I said it is enabled on my server. SMF has detected it. I also tried this on a different server and a different install of SMF and it did not work there either.

**Comment by albertlast** [comment] 2018-04-07 14:26
So long the red test is ther,
pspell is not activated on your server(has no relationship with smf).

**Comment by smfbigguy** [comment] 2018-04-07 17:05
It is not there. It is not red and the pop up that pops up says it works.
![firefox_screenshot_2018-04-07t17-04-31 070z](https://user-images.githubusercontent.com/3620111/38457881-50f87f5e-3a64-11e8-926c-28aa998c9a09.png)

**Comment by albertlast** [comment] 2018-04-07 17:12
@Sesquipedalian or so could look into i'm not able to activate this on my test env.

**Comment by smfbigguy** [comment] 2018-04-08 15:26
Also, I just checked but in the php info in the admin panel of SMF it also shows pspell enabled. I have used Edge, IE 11, Firefox and seamonkey browsers and get the same result in all of them.

**Comment by smfbigguy** [comment] 2018-04-10 00:06
I just install the SMF articles mod and the spell check works in it. Just not in the forum when making a post or topic.

**Comment by smfbigguy** [comment] 2018-04-10 03:08
This is the only error I can find when pushing the button spell check

`TypeError: sceditor.instance(...).storeLastState is not a function`

**Comment by smfbigguy** [comment] 2018-04-10 03:26
Found this in editor.js

```
// Start up the spellchecker!
smc_Editor.prototype.spellCheckStart = function()
{
	if (!spellCheck)
		return false;

	var e = $('#' + this.sUniqueId).get(0);

	sceditor.instance(e).storeLastState();
```

**Comment by Sesquipedalian** [comment] 2018-04-10 19:56
It looks like the `storeLastState()` and `setTextMode()` functions were removed in [this PR](https://github.com/SimpleMachines/SMF2.1/pull/2786/files#diff-c962f66d2fef87254e2ffaf9b1f07e1c). Restoring them was easy enough, but then the spell checking script ran into more problems further down the line and failed. So we are going to need to do more work to get it working correctly again.

**Comment by smfbigguy** [comment] 2018-04-10 20:52
Just glad you guys found it. Thanks for taking your time to look at it. :)

**Comment by Sesquipedalian** [comment] 2018-05-01 15:25
@smfbigguy: Please test #4744 to see if it solves the issue for you.

**Comment by smfbigguy** [comment] 2018-05-01 21:35
I will test it now.

**Comment by smfbigguy** [comment] 2018-05-01 21:44
No it does not. It does not say it is saving a draft anymore but it does nothing. Also, the drop down menus for drafts and attachments are stuck open. See screenshot.
![firefox_screenshot_2018-05-01t21-42-54 050z](https://user-images.githubusercontent.com/3620111/39495189-534d58ea-4d67-11e8-8285-3de8c98db3fb.png)

**Comment by Sesquipedalian** [comment] 2018-05-01 21:51
Thanks. I'll need to keep fiddling with it, then.

**Comment by smfbigguy** [comment] 2018-05-01 22:00
Yup. If ya have anything else to test, post it up. :)

**Comment by betonkamil** [comment] 2018-07-01 11:59
Aloooo

**Comment by betonkamil** [comment] 2018-07-01 12:01
Smf 2.1 rc ne zaman cikacak  oyuncak ettiniz smf yi ondan sonrada forum siteleri bitti diyorsunuz 
3 yildir smf bitmezmi  forum sitelerini bitiren sizsiniz

**Comment by Archer70** [comment] 2018-07-06 00:39
@smfbigguy I'm having trouble replicating the issues you're having on Sesq's branch. I don't suppose you have a live demo I could mess with? Are there any new errors in the log or browser console?

**Comment by smfbigguy** [comment] 2018-07-06 12:12
My site www.whatsurbeef.net is a live demo. Been running 2.1 since april or may. I have spellcheck turned off right now but can turn it back on. Also I just updated yesterday to the latest on GH.

**Comment by Archer70** [comment] 2018-07-06 16:42
Awesome, I'll look into it today. Thanks.

**Comment by smfbigguy** [comment] 2018-07-06 19:06
I have turned spellcheck on and I will enable registration again. I have it shut down cause I don't have the gdpr mod in place yet.

**Comment by Archer70** [comment] 2018-07-06 21:49
If you patch in the javascript functions from the last commit through the browser console, you can get an empty spellcheck window to open up. Problem is the window is empty because ?action=spellcheck is returning a "200 OK" response with an empty body. No HTML. Not sure why that is, as it seems to work fine on my fresh install. I'll dig some more later.

This can be tested by going to the New Topic page and pasting this into the JS console, then clicking "Spell Check"
```javascript
e = $('#message').get(0)
sceditor.instance(e).storeLastState = function() {
    this.wasSource = this.inSourceMode();
};
sceditor.instance(e).setTextMode = function() {
    if (!this.inSourceMode()) this.toggleSourceMode();
};
```

Also, I think it's unrelated, but your portal is throwing JS errors. Looks like it's a problem with a shoutbox variable being undefined.

**Comment by smfbigguy** [comment] 2018-07-06 22:10
If I knew where to patch it I would for sure. I don't know where to put that code. I know about ehportal throwing errors. He is working hard to get those out of the way I'm sure.

**Comment by smfbigguy** [comment] 2018-07-06 22:13
Not sure if this sheds any light on anything:

https://stackoverflow.com/questions/27921537/returning-http-200-ok-with-error-within-response-body

**Comment by Archer70** [comment] 2018-07-06 22:23
The JS I pasted above doesn't have to go in a file. You "hot patch" it by pasting into the console of the browser's developer tools (ctrl+shift+i) in Chrome. It will have to be done each time you reload the page as well.

![screenshot from 2018-07-06 15-21-55](https://user-images.githubusercontent.com/2660927/42402564-779ae8a0-8130-11e8-8f28-7f6c57ac630f.png)


I'll take a look at that link now!

**Comment by smfbigguy** [comment] 2018-07-07 01:14
The link is probably nothin but I appreciate you checkin it out.

**Comment by Archer70** [comment] 2018-07-07 02:46
I don't suppose there are any errors in the admin panel log after I messed with things today?

**Comment by smfbigguy** [comment] 2018-07-07 02:53
Nope....checked that out. Never has been anything.

**Comment by Archer70** [comment] 2018-07-07 22:32
Alright, I'm almost positive I've tracked it down to this bit in Subs-Post.php, around line 1466:

```php
	// Create a pspell or enchant dictionary resource
	$dict = spell_init();

	if (!isset($_POST['spellstring']) || !$dict)
		die;
```

`<input name="spellstring">` is present in the frontend, so my guess is that `!$dict` is causing the issue.

@smfbigguy if you could do me a big favor and change those lines to the following code on your test site, it would be very helpful in getting to the bottom of this. It shouldn't disrupt the forum at all, because the output will be in the spellcheck window.

```php
	// Create a pspell or enchant dictionary resource
	$dict = spell_init();

	if (!isset($_POST['spellstring']))
		exit('empty spellstring');
	if (!$dict)
	{
		exit(
			'existing: '.
			(function_exists('enchant_broker_init') ? 'enchant|':'').
			(function_exists('pspell_new') ? 'pspell' : '').
			'<br>using: '.
			(isset($context['provider']) ? $context['provider'] : 'none')
		);
	}
```

**Comment by jdarwood007** [comment] 2018-07-07 22:57
FYI,  Those modules are most likely on their way out: 
https://wiki.php.net/rfc/umaintained_extensions
https://wiki.php.net/todo/extensions

**Comment by Archer70** [comment] 2018-07-07 23:10
Well that's lovely. Personally I've never used the spell check feature in SMF. I'm wondering if this is an excuse to get rid of it when those extensions are removed.

**Comment by smfbigguy** [comment] 2018-07-08 11:38
I have tried this. Did all maintenance on the forum and turned off cache. All it did was say it was saving a draft. I don't get it. I even updated the forum a few days ago so it should be the latest from here.

**Comment by smfbigguy** [comment] 2018-07-08 11:54
If it works on everyone else's test sites and JUST not on mine than I will have to go over my server settings. I am positive everything is right but I will check again. Has ANYONE run into this like I have ??

**Comment by smfbigguy** [comment] 2018-07-08 15:01
Well, I have gone over my server, changed php versions, updated the server and changed a crap load of things. pspell is installed and still not working on my server so I really don't know what to say.

**Comment by Archer70** [comment] 2018-07-08 19:55
I tried it again today, and it works for me after patching the JS. @Sesquipedalian I believe if you merge in your PR, and @smfbigguy updates again, everything will start working..

![screenshot from 2018-07-08 12-52-03](https://user-images.githubusercontent.com/2660927/42423374-edea5c56-82ad-11e8-812a-0e5cd9b15530.png)

**Comment by smfbigguy** [comment] 2018-07-08 21:14
I will update again if I need to. Not today I hope, lol. If I have to I will though. I just realized that's my site, lol. Damn I wish I could get it to work, lol.

**Comment by NanoSector** [comment] 2018-08-14 12:41
I can confirm that the JS change fixes spell checking, although the results are still a little worthless IMHO :P

![image](https://user-images.githubusercontent.com/1280380/44092222-1748d6c4-9fd0-11e8-9132-66326c178d3c.png)

**Comment by NanoSector** [comment] 2018-08-14 12:45
Also I noticed that the window will be empty when there are no dictionaries installed. It doesn't throw an error but the function spell_init will return false.

**Comment by jdarwood007** [comment] 2018-08-14 23:34
So #4744 fixes this?  Can you give it a approved review then?

**Closed as completed** 2018-08-15 00:06 UTC
Labels: Editor, JavaScript
