### ISSUE TITLE
"install.php?step=2" is blank

### ISSUE THREAD

**Issue by Geremia** [SimpleMachines/SMF#7584] opened 2022-10-29 21:19 UTC
[Quote from: Geremia16 on October 27, 2022, 08:19:41 PM](https://www.simplemachines.org/community/index.php?msg=4137991):
"install.php?step=2" is a blank page. I get lots of errors in Apache's error\_log:  
```
[Thu Oct 27 17:16:48.006075 2022] [php7:notice] [pid 21416:tid 140032570541760] [client ::1:48266] PHP Notice:  Trying to access array offset on value of type null in /var/www/htdocs/smf/install.php on line 386, referer: https://<redacted>/smf/install.php?step=0
[Thu Oct 27 17:16:48.006165 2022] [php7:notice] [pid 21416:tid 140032570541760] [client ::1:48266] PHP Notice:  Undefined index:  in /var/www/htdocs/smf/install.php on line 818, referer: https://<redacted>/smf/install.php?step=0
[Thu Oct 27 17:16:48.006178 2022] [php7:notice] [pid 21416:tid 140032570541760] [client ::1:48266] PHP Notice:  Trying to access array offset on value of type null in /var/www/htdocs/smf/install.php on line 818, referer: https://<redacted>/smf/install.php?step=0
[Thu Oct 27 17:16:48.006208 2022] [php7:error] [pid 21416:tid 140032570541760] [client ::1:48266] PHP Fatal error:  Uncaught Error: Function name must be a string in /var/www/htdocs/smf/install.php:818\nStack trace:\n#0 /var/www/htdocs/smf/install.php(164): DatabaseSettings()\n#1 {main}\n  thrown in /var/www/htdocs/smf/install.php on line 818, referer: https://<redacted>/smf/install.php?step=0
```

### Environment (complete as necessary)
- Version/Git revision: 2.1.2
- Database Type: Postgres
- Database Version: 15
- PHP Version: 7.4.32

**Comment by albertlast** [comment] 2022-10-30 15:04
what is the name of you database user?

**Comment by sbulen** [comment] 2022-10-31 04:46
I cannot reproduce this, despite multiple attempts.  And others are not seeing this.

All signs in the initial support thread on this:
https://www.simplemachines.org/community/index.php?topic=583981.0

...point to this being an environment issue, not an SMF issue.

I'll leave this open about a week - just in case someone does find a way to reproduce.  If not, this will be closed.

**Comment by sbulen** [comment] 2022-11-01 00:14
Issue confirmed to be an environment issue:
https://www.simplemachines.org/community/index.php?msg=4138262

Closing this.

**Closed as completed by sbulen** 2022-11-01 00:14 UTC
Labels: Not enough details
