### ISSUE TITLE
"Listen to the letters" incorrect play time

### ISSUE THREAD

**Issue by MisterVector** [SimpleMachines/SMF#6224] opened 2020-08-16 03:43 UTC
Nothing too big, but when attempting to listen to the letters of a captcha, the playtime is not correct:

![image](https://user-images.githubusercontent.com/437096/90326022-039ced00-df38-11ea-9888-3985eac4f9d1.png)

**Comment by frandominguezl** [comment] 2020-08-26 14:47
Some additional info. This only appears to be occuring on Firefox.

**Comment by frandominguezl** [comment] 2020-09-01 16:12
I've digged into this a few times already. From what I could gather, the content-length header is the same for both browsers so, there should be some logic behind each browser that isn't handling properly said length.

I've read on StackOverflow that this may be problem on how different browsers handle file's metadata, but I didn't actually find anything useful to fix this issue. Maybe someone with more experience in the field can propose a workaround for serving .wav files.

**Comment by live627** [comment] 2020-10-16 13:22
ff 80.0 here, and it reads 7s max for me.

**Comment by live627** [comment] 2020-10-16 14:24
Seems like random refreshes will do the weird length thing.

**Comment by BrickOzp** [comment] 2021-02-12 06:52
I am not able to reproduce this with ff 85.0.1. Did refresh multiple times.
Do you still have this issue?

**Comment by frandominguezl** [comment] 2021-02-12 10:29
85.0.2 here. I do still have the issue.

**Comment by Sesquipedalian** [comment] 2021-08-13 21:01
When I tried to reproduce the issue, I never saw exactly the same symptoms, but I definitely saw some unexpected behaviours and errors trying to retrieve and play the .wav file. Specifically, when browsers sent the "Range" header as part of the request, our response was malformed. Browsers seem to take different approaches to dealing with that, so that might explain the inconsistency we've seen when trying to reproduce this issue.

@MisterVector and @frandominguez03, please test #6937 to see if it solves this issue for you.

**Comment by MisterVector** [comment] 2021-08-27 04:21
I don't know if this was the case before your PR, but I'm noticing two different versions of the sound player:

![image](https://user-images.githubusercontent.com/437096/131071156-fea22495-a8ef-4392-b781-680b1b12ba95.png)

If I press F5 pretty quickly, sometimes I will get the version with the correct time. Other times I fiddle around by opening a private session, attempt to register, then go to "listen to the letters" and get the proper time. More times than not, I'll get the version with the incorrect time.

Since this problem doesn't occur with Internet Explorer, Microsoft Edge (tried with new version), or Google Chrome, I wonder if it would be worth our time to let the firefox team know about this?

**Comment by Sesquipedalian** [comment] 2021-08-27 19:37
After Googling around a bit more in light of your comments here, @MisterVector, and @live627's comments on the PR, it looks like the situation is something like this:

Assuming I understand things correctly, Firefox prefers to perform its own analysis of the audio file's internal self-description header to determine the audio's duration, ignoring some of the key information provided in the HTTP header. If there is a discrepancy between what is calculated based on the internal header and what would be calculated if the HTTP header is not ignored, Firefox will prefer the former, *even if it doesn't make sense based on the file's actual size*. Other browsers will choose the value calculated using the HTTP header if the one based on the internal header alone doesn't make sense.

So if I understand the situation correctly (and I may very well be wrong), then we probably are sending out audio files that contain incorrect information in their internal headers, even though we are sending the correct information in our HTTP headers. Other browsers are covering for our mistake by choosing the sane option between the two different values, while Firefox is trying to play it safe and therefore choosing the insane option.

Unfortunately, I currently have no idea how to fix the internal headers of the generated WAV files. The `pack()` call on line 110 below appears to be responsible for creating the audio's internal header, but there are no comments and I have no idea what, if anything, it might be doing correctly or incorrectly.
https://github.com/SimpleMachines/SMF2.1/blob/2f6e030191162dac1d9bd00a7b9e40da5d16f2d1/Sources/Subs-Sound.php#L101-L113

Given all this, I am inclined to label this issue as "Won't fix" and give up on it. After all, the full audio does it fact play, so the incorrect duration value that Firefox shows is ultimately just a cosmetic problem.

**Comment by live627** [comment] 2021-08-28 12:09
The canonical WAVE format starts with the RIFF header:

Offset | Size | Name | Description
--- | --- | --- | ---
0 | 4 | ChunkID | Contains the letters "RIFF" in ASCII form (0x52494646 big-endian form).
4 | 4 | ChunkSize | 36 + SubChunk2Size, or more precisely: 4 + (8 + SubChunk1Size) + (8 + SubChunk2Size) This is the size of the rest of the chunk  following this number.  This is the size of the  entire file in bytes minus 8 bytes for the two fields not included in this count: ChunkID and ChunkSize.
8 | 4 | Format | Contains the letters "WAVE" (0x57415645 big-endian form).

The "WAVE" format consists of two subchunks: "fmt " and "data":
The "fmt " subchunk describes the sound data's format:

Offset | Size | Name | Description
--- | --- | --- | ---
12 | 4 | Subchunk1ID | Contains the letters "fmt " (0x666d7420 big-endian form).
16 | 4 | Subchunk1Size | 16 for PCM. This is the size of the rest of the Subchunk which follows this number.
20 | 2 | AudioFormat | PCM = 1 (i.e. Linear quantization) Values other than 1 indicate some  form of compression.
22 | 2 | NumChannels | Number of Channels. Mono = 1, Stereo = 2, etc.
24 | 4 | SampleRate | Number of Samples per second, or Hertz.
28 | 4 | ByteRate | (SampleRate * NumChannels * BitsPerSample / 8)
32 | 2 | BlockAlign | (NumChannels * BitsPerSample / 8) The number of bytes for one sample including all channels. 
34 | 2 | BitsPerSample 

The "data" subchunk contains the size of the data and the actual sound:

Offset | Size | Name | Description
--- | --- | --- | ---
36 | 4 | Subchunk2ID | Contains the letters "data" (0x64617461 big-endian form).
40 | 4 | Subchunk2Size |  (NumSamples * NumChannels * BitsPerSample / 8) This is the number of bytes in the data. You can also think of this as the size of the read of the subchunk following this  number.
44 | * | Data | The actual sound data.


Based on the above, the only header that seems to be wrong in our generated audio file is ByteRate, which looks to be in bits, not bytes. However, that didn't fix the problem for me. I suppose a way to fix the OP's problem would be to mask it—nest the player in a noscript tag, and then a JavaScript to play it.

**Closed as completed** 2021-09-01 18:11 UTC
Labels: Captcha

**Comment by MisterVector** [comment] 2021-09-02 23:00
I still see the incorrect time. Merged the latest changes including this fix and tried going to "Listen to the letters" only to be shown the incorrect time... I think the one thing I gathered from this is that the firefox team ought to be aware of this.

**Comment by jdarwood007** [comment] 2021-09-02 23:53
If a firefox developer is able to provide insights that would be great, otherwise we will just need to look more into it.  Seems like this could be an example of either other browsers doing it right or they are ignoring something that we are doing wrong and firefox is handling it right.
