### ISSUE TITLE
Logout user get checked validatePasswordFlood

### ISSUE THREAD

**Issue by albertlast** [SimpleMachines/SMF#4369] opened 2017-10-20 20:27 UTC
With reverting pr https://github.com/SimpleMachines/SMF2.1/pull/4363
the logout user get again checked if the passwordflooded while calling the board normaly.
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L479

**Comment by sbulen** [comment] 2017-10-20 22:01
This is a dupe of #4297.

**Closed as completed** 2017-10-20 22:04 UTC
