### ISSUE TITLE
Upgrader does not fix $tasksdir

### ISSUE THREAD

**Issue by jdarwood007** [SimpleMachines/SMF#7932] opened 2023-12-04 03:05 UTC
#### Description
Just a reference from #7930.  When tasks was renamed to 'Tasks' to fix other issues and align to more standards, the underlaying setting is not updated in Settings.php.  Upgrader needs to resolve this.
Setting this to Alpha 2 as we don't have the new upgrader logic, but it needs tracked so we fix it.

**Comment by Sesquipedalian** [comment] 2023-12-04 20:11
This should be fixed in the current upgrader logic before we move on from Alpha 1, because the change that introduced the problem is part of Alpha 1.

**Comment by jdarwood007** [comment] 2023-12-04 22:30
Understood.  We need to make the upgrader/installer changes then for Alpha 1.

**Comment by Sesquipedalian** [comment] 2023-12-04 22:41
Well, we need to make minor fixes to the upgrader and installer now. The major structural reworking can happen afterward.

**Comment by jdarwood007** [comment] 2023-12-04 22:51
Well I added to #7853 for the upgrader to do non database changes for cleanup, which is what this would need to do.  I can pull those upgrader changes out and then we can have this be one of the first things it tackles.  The logic to migrate the Settings.php would also be able to fix this, but we can move that logic to occur during this cleanup step.

**Comment by Sesquipedalian** [comment] 2023-12-04 23:12
Putting the upgrader logic into its own PR makes sense. I agree with your comment elsewhere that we need to move the changes to the upgrader and installer to the Alpha 2 milestone, since many other changes will depend on that. So we should do that as the first task in Alpha 2, and then go on to use that for changes such as moving the language files, etc., etc.

**Closed as completed** 2023-12-05 23:05 UTC
Labels: Upgrader
