### ISSUE TITLE
alt parameter of img bbcode tag not always parsed properly

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#3027] opened 2015-09-05 18:09 UTC
http://www.simplemachines.org/community/index.php?topic=539499.0

If you specify alt, height and width for the img tag, the height gets parsed as part of the alt text instead of being parsed as its own parameter. Putting quotes around the alt text doesn't fix it as those get parsed as part of the alt text as well.

**Comment by matthew-kerle** [comment] 2016-02-29 17:37
I sent you a fix for this on Facebook Messenger.

**./Sources/Subs.php:**
Find:
`php
$alt = empty($matches[3][$match]) ? '' : ' alt=' . preg_replace('~^&quot;|&quot;$~', '', $matches[3][$match]);`

Replace:
`php
$alt = empty($matches[3][$match]) ? '' : ' alt="' . preg_replace('~^&quot;|&quot;$~', '', $matches[3][$match]) . '"';`

**Comment by matthew-kerle** [comment] 2016-02-29 17:38
"preg_match_all('~&lt;img\s+src=((?:&quot;)?)((?:https?://|ftps?://)\S+?)\1(?:\s+alt=(&quot;._?&quot;|\S_?))?(?:\s?/)?&gt;~i', $data, $matches, PREG_PATTERN_ORDER);
It catches alt with quotes alt="" for instance, but then they're removed when they're put in the tag, so when the BBC is parsed...it breaks."
- "Which would force the alt attribute to always have double-quotes around the value, and if it already has them, strip them and re-add them to be safe."

**Comment by Sesquipedalian** [comment] 2016-03-10 02:59
I tested those suggested changes, @Labradoodle-360, but they didn't seem to make any difference.

From my tests, it looks like the cause of this bug is that the parser only handles the parameters correctly if they are in the specific order listed in parse_bbc(): alt, title, width, height.

Test input:

```
Works:
[img alt=Test width=100 height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img alt=Test title=Foo width=100 height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]

Doesn't work:
[img alt=Test height=100 width=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img alt=Test title=Foo height=100 width=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img alt=Test width=100 title=Foo height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img alt=Test width=100 height=100 title=Foo]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img title=Foo width=100 alt=Test height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img title=Foo alt=Test width=100 height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]

Really doesn't work:
[img width=100 alt=Test height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img width=100 height=100 alt=Test]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img width=100 title=Foo alt=Test height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img width=100 alt=Test title=Foo height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
[img width=100 height=100 alt=Test title=Foo]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]
```

Test output:

```
Works:<br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="Test" title="" width="100" height="100" class="bbc_img resized"><br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="Test" title="Foo" width="100" height="100" class="bbc_img resized"><br>
<br>
Doesn't work:<br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="Test height=100" title="" width="100" class="bbc_img resized"><br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="Test" title="Foo height=100" width="100" class="bbc_img resized"><br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="Test width=100" title="Foo" height="100" class="bbc_img resized"><br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="Test width=100 height=100" title="Foo" class="bbc_img resized"><br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="" title="Foo width=100 alt=Test" height="100" class="bbc_img resized"><br>
<img src="http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png" alt="" title="Foo alt=Test" width="100" height="100" class="bbc_img resized"><br>
<br>
Really doesn't work:<br>
[img width=100 alt=Test height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]<br>
[img width=100 height=100 alt=Test]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]<br>
[img width=100 title=Foo alt=Test height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]<br>
[img width=100 alt=Test title=Foo height=100]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]<br>
[img width=100 height=100 alt=Test title=Foo]http://avatars.simplemachinesweb.com/smf/avatar_23_1337883444.png[/img]<br>
```

This doesn't pin down exactly where the problem is yet, but it does at least identify that the issue lies with handling out of order parameters. Hopefully that info will be helpful in further tracking down the source of the problem.

**Comment by Sesquipedalian** [comment] 2016-03-15 06:44
I was playing with this some more, and I am starting to suspect that there are two separate issues here.  

First, it seems like the regex we build using `$possible['parameters' ]` is broken. For the examples above that produced any HTML output (i.e. the "Works" and "Doesn't Work" sections), the regex always matches on the first try, even when it should fail.

The second problem is that `pc_next_permutation()` doesn't seem to be doing anything at all. For the third group of tests, the code loops through 5040 iterations but never actually tries any alternative permutations. Maybe we are just giving the function the wrong input?

**Comment by Sesquipedalian** [comment] 2016-03-15 20:39
#3345 seems to fix this nicely. Testing and feedback on it appreciated.

**Closed as completed** 2016-03-18 15:55 UTC
Labels: Parsers (BBC/Markdown)
