### ISSUE TITLE
Smileys don't show when posting or replying in IE11.

### ISSUE THREAD

**Issue by lurkalot** [SimpleMachines/SMF#5391] opened 2019-02-07 20:45 UTC
2.1 RC1  
Smileys don't show when posting or replying in IE11. 

They seem fine in Edge, Chrome and Firefox.

![smileys1](https://user-images.githubusercontent.com/6047983/52441696-4dbe3a80-2b19-11e9-9295-f607cdf2e899.png)

![smileys2](https://user-images.githubusercontent.com/6047983/52441705-557ddf00-2b19-11e9-8328-2888491b11a1.png)

**Comment by Sesquipedalian** [comment] 2019-02-07 21:59
* Sesquipedalian is tempted to declare IE11 a bug.

**Comment by lurkalot** [comment] 2019-02-07 22:34
lol...

**Comment by Arantor** [comment] 2019-02-07 23:14
IE 11 is supported at least through 2020 and for some editions of Windows, through 2025.

**Comment by live627** [comment] 2019-02-08 00:23
> Sesquipedalian is tempted to declare IE11 a bug.

 live627 is tempted to declare Sesquipedalian a bug.

**Comment by Sesquipedalian** [comment] 2019-02-08 15:47
> IE 11 is supported at least through 2020 and for some editions of Windows, through 2025.

Fear not. Though I am beset by temptation, I shall resist it. 😉

**Comment by Gwenwyfar** [comment] 2019-02-08 17:41
> IE 11 is supported at least through 2020 and for some editions of Windows, through 2025.

Which basically just means how stubborn the devil is in not letting go of the task of haunting web dev's lives.

At least most chrome bugs, as annoying as they might be, can be tossed as "their bugs, their problem".

**Comment by live627** [comment] 2019-02-12 22:58
I went to recreate this issue but I can see smilies as guest.

![reply](https://user-images.githubusercontent.com/431799/52673713-c721a880-2ede-11e9-8c16-f0d5cb678468.png)

**Comment by Sesquipedalian** [comment] 2019-02-13 18:15
I cannot reproduce this either.
<img width="1327" alt="screen shot 2019-02-13 at 10 11 26 am" src="https://user-images.githubusercontent.com/191731/52730114-db65b400-2f77-11e9-9f53-00a57266c295.png">

Closing.

**Closed as completed by Sesquipedalian** 2019-02-13 18:15 UTC
Labels: Editor
