### ISSUE TITLE
 Page can not scroll all the way down

### ISSUE THREAD

**Issue by wintstar** [SimpleMachines/SMF#3195] opened 2015-12-16 07:45 UTC
Last pull request #3192 from jdarwood007/release-2.1 … 

Forum version: SMF 2.1 Beta 2 (more detailed)
Current SMF version: SMF 2.1 Beta 2
GD version: bundled (2.1.0 compatible)
MySQLi version: 5.6.26
PHP: 5.6.12 (more detailed)
Server version: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.12

For large Boards with many categories,, page can not scroll all the way down

![bug-footer](https://cloud.githubusercontent.com/assets/2753863/11834833/387799e2-a3d0-11e5-98a6-bc6550020580.PNG)

open 
root/themes/default/css/index.css
find

```
#footer {
    margin: 4em 0 0 0;
    padding: 10px 5%;
    background: #3e5a78;
    border-top: 3px solid #b2b6bd;
    position:absolute; 
    bottom: 0;
    width: 100%;
}
```

replace with

```
#footer {
    margin: 4em 0 0 0;
    padding: 10px 5%;
    background: #3e5a78;
    border-top: 3px solid #b2b6bd;
    bottom: 0;
    width: 100%;
}
```

**Comment by XinYenFon** [comment] 2015-12-20 18:31
Can't reproduce this issue on;
- Firefox 42/43
- IE11 (on Windows 10)
- MS Edge

How much categories / boards / which browser ?

**Comment by wintstar** [comment] 2015-12-20 18:39
```
Firefox 42/43
IE11 (on Windows 10)
MS Edge
```

3 Boards with 10 Categories and opened Statistics.

**Comment by XinYenFon** [comment] 2015-12-20 18:51
I have 11 categories with 50+ boards. Try Ctrl+F5 or cache clearance via admin.

**Comment by wintstar** [comment] 2015-12-20 19:56
I remove this value position:absolute; , the issue is resolved
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Themes/default/css/index.css#L1252

Board Cache and Browser cache have i deletet

**Comment by colinschoen** [comment] 2015-12-28 14:41
Which browser?

**Comment by wintstar** [comment] 2015-12-28 14:43
Firefox 42/43
IE11 (on Windows 10)
MS Edge

**Comment by XinYenFon** [comment] 2016-02-04 19:40
I updated my build still can't reproduce this.

**Comment by MissAllSunday** [comment] 2016-09-01 18:03
@wintstar  Are you still able to reproduce this issue?

**Comment by XinYenFon** [comment] 2016-09-01 18:30
This fixed long time ago actually.

**Comment by MissAllSunday** [comment] 2016-09-01 19:53
OK,  dunno if issues can be closed by mail. 

#close

**Closed as completed** 2016-09-01 20:01 UTC
