### ISSUE TITLE
0004316: Brackets in username break quoting (WYSIWYG)

### ISSUE THREAD

**Issue by XinYenFon** [SimpleMachines/SMF#1502] opened 2014-04-05 07:10 UTC
Step 1: Quote a user with brackets in their name
Step 2: Activate WYSIWYG view

Result: trailing quote tag disappears

Mantis: http://dev.simplemachines.org/mantis/view.php?id=4316

Quote tag now not disappearing but quote place not toggling to WYSIWYG mode.

**Comment by jdarwood007** [comment] 2018-07-15 20:55
@Antes I can't reproduce this bug anymore.  This most likely was resolved with the change over to SCEditor.  Closing but if you find out you can reproduce it, let us know.

**Closed as completed by jdarwood007** 2018-07-15 20:55 UTC
Labels: Editor
