### ISSUE TITLE
Heavy bug in the sceditor !!

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3292] opened 2016-02-26 16:37 UTC
Problem as follow:
1. I open the editor in bbc mode
2. I insert a image attach, they i have upload before. the bbc tag is show as:
 **[attach name=Download.png type=image/png]25[/attach]**
3. now I switch to the WYSIWYG mode .. only a link is shown (not the image)
4. I switch back to the bbc mode, now the bbc tag is show as:
 **[iurl=http://mydomain/index.php?action=dlattach;attach=25;type=preview;file]Download.png[/iurl]**

If I insert the image attach in WYSIWYG, the IURL tag is also used.

If I save that, the image is newer shown and a edit of this message is not more possible !!
Not with the bbc mode, not with the WYSIWYG mode.
Only one thing will help on this situation .. modify the message in the database (remove the iurl tag)

**That is a absolute no go !!!**

**Comment by Oldiesmann** [comment] 2016-02-26 17:14
Are you using the latest files from GitHub? That issue should be fixed now (I fixed that a few months ago).

**Comment by live627** [comment] 2016-02-26 21:56
Update your files before reporting a bug, kthx.

**Comment by PortaMx** [comment] 2016-02-27 01:40
Well .. I download just a release from here .. But ..
The ugrade dont work .. errors on all **safe_unserialize** because these function is not exists.

The release that I **currently** use, have the timestamp 16.02.2016 what mean ~10 day old.
So if I hear you, then this relase is ready .. but I seems it's not ready.
If I fault, let me known ...

Thanks

**Comment by live627** [comment] 2016-02-27 03:31
https://github.com/SimpleMachines/SMF2.1/issues/3289

**Comment by MissAllSunday** [comment] 2016-02-27 19:44
I can reproduce this but everything I've tried has failed...

**Comment by Oldiesmann** [comment] 2016-03-01 16:45
Which issue are you able to reproduce - the inline attachment issue or the safe_unserialize issue?

If it's the safe_unserialize issue, and you're having trouble fixing it properly, your best bet would be to just define an "upgrade_safe_unserialize" function in upgrade.php and use that instead (the "upgrade_" name prevents errors if/when Subs.php gets pulled in later on).

**Comment by Yariksat** [comment] 2016-03-01 17:26
I confirm that the problem is the same as in the first post topic. Make a to do the video, to see the problem?

**Comment by MissAllSunday** [comment] 2016-03-01 17:36
The safe_serialize issue was already fixed a few days ago.

I'm talking about inserting an attached image.

**Comment by Oldiesmann** [comment] 2016-03-02 17:13
The inserting an attached image issue should have been fixed a long time ago. It was working perfectly the last time I tested it.

**Comment by MissAllSunday** [comment] 2016-03-02 20:02
Nope, something mess up with the attached images in wysiwyg mode, theres also some weird issues with showing attachments.

**Comment by Oldiesmann** [comment] 2016-03-02 20:26
I'll look into it when I get a chance. I had inline attachments working fine in the WYSIWYG editor a few months ago.

**Comment by Oldiesmann** [comment] 2016-03-02 20:27
Just updated my test board... Once I did a hard refresh (CTRL+R), inline attachments worked fine again, so try that and see if it helps.

**Comment by MissAllSunday** [comment] 2016-03-02 20:32
Theres also issues with the the attachments directory, on a clean install it doest  set the var correctly,

Going to the attachment settings shows an error:  Warning: Invalid argument supplied for foreach() in \htdocs\21\Sources\ManageAttachments.php on line 2472

Trying to add a new path results in the following errors:

Warning: Invalid argument supplied for foreach() in \htdocs\21\Sources\ManageAttachments.php on line 2472

Warning: array_keys() expects parameter 1 to be array, null given in \htdocs\21\Sources\ManageAttachments.php on line 2512

Warning: array_merge(): Argument #2 is not an array in \htdocs\21\Sources\ManageAttachments.php on line 2512

Warning: max(): When only one parameter is given, it must be an array in \htdocs\21\Sources\ManageAttachments.php on line 2512

**Comment by MissAllSunday** [comment] 2016-03-02 20:50
Ugh nope,  it seems we are talking about two different things here... 

I line attachments work just fine...  That's not the issue.  The issue is previewing an image attachment. 

Set your editor to wysiwyg mode,  upload some pictures,  insert those pics into the editor box,  there should be an image and not a link. 

I just tried on two clean installs,  uploaded four images at once only one showed as image all the other was converted to links.

**Comment by Oldiesmann** [comment] 2016-03-03 17:18
The first time I try it, it doesn't work, but if I refresh the page, it does. I'm not sure why though. It was working fine at one point.

**Comment by MissAllSunday** [comment] 2016-03-03 17:43
Its rather erratic, even if I change the regex to just search for the word "image" in type  there are still some occasions where an image will be converted to an iurl tag.

We will need to check if a link its an image, thing is, doing so creates a lot more issues, starting with having to do an asynchronous call right in the middle of a synchronous one which is simply not possible.

**Comment by MissAllSunday** [comment] 2016-03-03 20:00
Regarding attachmentUploadDir  for some reason install is creating bad json strings on Windows:

'{$attachdir}' => json_encode(array(1 => dirname(**FILE**) . '/attachments')),

Creates a line like this one:  {"1":"D:\xampp\htdocs\21\/attachments"}

Which of course is bad syntax.

I don't know if the json_encode function does create that string or if its later modified when inserting to the DB.  My guess is that the extra \ is removed sometime before being saved to the DB.

 I also wonder, it might be better to json_decode that setting just once, on reloadSettings()  rather than doing it multiple times across several files.

**Comment by Oldiesmann** [comment] 2016-03-04 18:12
Did some more digging on this. It appears for some reason the width of the thumbnail image is being returned as 0, so that's why image attachments are getting inserted as links. I'm still trying to figure out why that's happening though. Once that's figured out it should be pretty easy to fix the other issues.

**Comment by Oldiesmann** [comment] 2016-03-04 19:10
Playing around with this some more and think I have it figured out.

On line 404 of jquery.sceditor.smf.js, if you change `contentIMG.width` to `contentIMG.getAttribute('width')`, it works properly, and the proper attach bbcode shows up when you switch to source mode.

I have no idea why that works, but it does.

I still need to play with other attachment types (regular files) and figure out the proper fix for the "attrs is not a function" error you get when trying to go from source to WYSIWYG with iurl or img, but it's a start at least.

**Comment by Yariksat** [comment] 2016-03-05 07:33
Very simply, it works. I checked by making manual changes

**Comment by PortaMx** [comment] 2016-03-05 07:47
I have tested the patch, but that worked not alsoluty correct .. it's more randow ;-)
Now i changed the line to

`if ((typeof attrs.type !== "undefined" && !attrs.type.match(/image.*/)) || contentIMG.width === "undefined"){`

That work every time ansolute perfect !!

**Comment by Oldiesmann** [comment] 2016-03-05 17:46
That won't work when you're trying to insert an image attachment but a thumbnail couldn't be generated for some reason, as contentIMG.width will never be undefined - it will always be a number, even when the src isn't a URL to an image.

**Comment by Oldiesmann** [comment] 2016-03-05 18:19
Finally figured out what's going on with regular attachments as well. When the code sees an anchor (`<a>`) tag without a "target" attribute, it automatically returns it as iurl. Modifying the code for the url tag to check for the "data-attachment" attribute fixes it properly for regular attachments.

**Comment by PortaMx** [comment] 2016-03-05 18:27
Well, you are right .. my mistake. I have made the fix not correct .. must be

`if ((typeof attrs.type !== "undefined" && !attrs.type.match(/image.*/)) || contentIMG.getAttribute('width')){`

After I clear the Browser cache it works ..

**Comment by Oldiesmann** [comment] 2016-03-05 18:54
That won't fix it either. If you insert an image and contentIMG.getAttribute('width') is defined (which it should be for most images), then it still inserts it as a link rather than a linked image. The code I posted above seems to work.

Also, I've found the issue causing regular (non-image) inline attachments to get converted to iurl. The problem is that we weren't checking for data-attachment when parsing things for the regular URL tag - it was just assuming any `<a>` tag without a "target" attribute should be an iurl. Adding relevant JavaScript code there will fix it (I'll be committing the fixes for that shortly).

However, I did find a couple more attachment-related bugs while testing things:
1. If you upload a file, you can't delete it before making a post. Instead you just get a message saying there was an error deleting the file. When you make the post, the file is still attached.
2. When you try to post only an attachment that isn't an image, it makes a post saying "No message is associated with this attachment" and keeps the file attached as expected. However, it also does this if the inline attachment is the first thing in the post:

```
[attach name=x]id[/attach]
Other text here.
```

Instead you end up with this:

```
No message is associated with this attachment.
Other text here.
```

**Comment by Oldiesmann** [comment] 2016-03-07 18:58
#3329 should fix a couple more issues with the attachment directory not getting set properly during installation...

**Comment by Yariksat** [comment] 2016-03-29 18:01
Now if after investments smilies they are displayed BB code

[attach name=b080281b9ec6ff269f077a6550df8213.jpg type=image/jpeg]7293[/attach]

 :biggrin:

**Closed as completed** 2016-09-01 17:44 UTC
