### ISSUE TITLE
php 7.0 error uploading & installing .zip packages

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#7313] opened 2022-02-11 23:59 UTC
#### Description

2.1 doesn't like installing .zips on php 7.0, in either windows or linux.   

Note that php 7.3 & 7.4 work fine. Note that tar.gz works fine.

![image](https://user-images.githubusercontent.com/23568484/153686072-43b8e253-5f26-432d-aec0-4fae3a25f93e.png)

Error log:
![image](https://user-images.githubusercontent.com/23568484/153686350-64fb1810-9e1b-4a61-a6b6-ffea2bdb4adc.png)

### Steps to reproduce
1. Use php 7.0
2. Install a .zip package

### Environment (complete as necessary)
- Version/Git revision: current
- Database Type: mysql
- Database Version: 5.7
- PHP Version: 7.0

### Additional information/references
7.0 is the new 5.4...

**Comment by Sesquipedalian** [comment] 2022-02-12 00:04
Best fix for people affected by this is to use a version of PHP that is not EOL.

**Comment by jdarwood007** [comment] 2022-02-12 00:05
| PHP Version | OS | ZIP Upload Result | 
| ------ | ------ | ------ | 
| 8.0 | Linux | Success | 
| 7.4 | Linux | Success | 
| 7.3 | Linux | Success | 
| 7.2 | Linux | Success | 
| 7.1 | Linux | Success | 
| 7.0 | Linux | Fail | 
| 8.0 | Windows | Success | 
| 7.4 | Windows | Success | 
| 7.3 | Windows | Success | 
| 7.2 | Windows | Untested | 
| 7.1 | Windows | Untested | 
| 7.0 | Windows | Fail |

**Comment by jdarwood007** [comment] 2022-02-12 00:14
For more information. @sbulen pointed out, its because of the 3rd param to unpack function, which was only added in [7.1.0](https://www.php.net/manual/en/function.unpack.php)

This PR introduced this, fixing another issue:  https://github.com/SimpleMachines/SMF2.1/pull/7180

**Comment by Bopske** [comment] 2022-02-12 15:27
Just tried testing a mod upload on PHP 7.0.0 (since SMF 2.1.1 states it restores PHP 7.0 compatibility)

and indeed this does not work anymore... so the claim that SMF2.1.1 supports PHP 7.0.0 does not hold atm...

**Comment by isaak654** [comment] 2022-02-13 11:24
If this won't be fixed, I would suggest to put a block for PHP 7.0 and also fixing the wording "Restores support for PHP 7.0": https://www.simplemachines.org/community/index.php?topic=580657.0

**Comment by jdarwood007** [comment] 2022-02-13 15:37
At this point, it is a known issue and it takes a specific set of circumstances to reproduce it.
1. PHP 7.0
2. Customization must be a zip file

We have support to run the system on 7.0, but with this, its a known issue that isn't worth the development time to fix up the code.

PHP 7.0 reached EOL in before 2019.  So its been out of service for 4+ years.  https://www.php.net/supported-versions.php
If you can, even upgrading to 7.1 would fix it.   Although 7.1 went EOL before the end of 2019.

As a FYI.  The next version of SMF beyond the 2.1 line will be bumping up the version requirements as well.

Most of our developers are on 7.4 or 8.0 and only doing minimum testing for anything older.

**Comment by Sesquipedalian** [comment] 2022-02-13 17:32
It is also worth noting that you can always unzip the archive on your local machine and then upload the resulting folder via FTP to your packages directory on the server. SMF's package manager will be perfectly happy to work with the unzipped data.

**Comment by Bopske** [comment] 2022-02-13 18:01
Yes it does, but it keeps throwing error messages everytime one access the o op packages admin page… 

I am not saying this MUST be fixed, just that this is an issue that will come op sooner or later, so better be upfront about it…

**Comment by m4z** [comment] 2022-02-13 19:56
If you have existing zip files in your Package directory, each zip will generate 8 of these errors each time you access the Package Manager, and the zipped mods won't show up under "Browse Packages".

**Comment by Sesquipedalian** [comment] 2022-02-13 23:26
Hm. Well, that might change things a bit...

As always, however, **I promise you nothing.**

**Comment by Sesquipedalian** [comment] 2022-02-13 23:58
Okay, folks, please test #7319.

**Closed as completed** 2022-02-15 07:23 UTC
Labels: Package Manager, PHP version support
