### ISSUE TITLE
"sslRedirect" yields to lots of "Undefined" and other errors...

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#5135] opened 2018-11-10 17:36 UTC
#### Description
In 2.1, if we're forcing SSL, and you access the forum via a regular HTTP URL, it's supposed to throw a "You must login via SSL" error (though apparently not just if you're trying to login?) then redirects to the https version of the URL. However, this somehow yields to a couple dozen "Undefined" errors.

### Steps to reproduce
1. Go to the http version of a forum URL
2. Login and check the error log

### Environment (complete as necessary)
- Version/Git revision: latest
- Database Type: MariaDB
- Database Version: 10.0.36
- PHP Version: 7.1.23

### Additional information/references
An example of one of the errors, with backtrace...

```
Type of error: General
Error message: 2: Invalid argument supplied for foreach()
File: /.../Sources/Subs.php
Line: 3740
URL of page causing the error: https://www.christianphotographers.com/community/index.php?topic=88.0;prev_next=next;sslRedirect

#0: smf_error_handler()
Called from /.../Sources/Subs.php on line 3740
#1: template_footer()
Called from /.../Sources/Subs.php on line 3228
#2: obExit()
Called from /.../Sources/Errors.php on line 372
#3: setup_fatal_error_context()
Called from /.../Sources/Errors.php on line 231
#4: fatal_lang_error()
Called from /.../Sources/Load.php on line 1886
#5: loadTheme()
Called from /.../index.php on line 189
#6: smf_main()
Called from /.../index.php on line 150
```

Note that this is after I changed the code to `fatal_lang_error('login_ssl_required', false);` instead of the buggy `fatal_lang_error($txt['login_ssl_required'], true);`. Oddly enough though the Baidu search engine spider seems to be the only thing triggering this at the moment. Google and Yandex have both been by since I upgraded to 2.1 and neither one has caused these issues (possibly they're smart enough to detect the change to https).

**Comment by albertlast** [comment] 2018-11-10 19:18
> In 2.1, if we're forcing SSL, and you access the forum via a regular HTTP URL, it's supposed to throw a "You must login via SSL" error (though apparently not just if you're trying to login?) then redirects to the https version of the URL. However, this somehow yields to a couple dozen "Undefined" errors.

Nope it supposed to redirect you to the https page: https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L1885
and when something goes wrong it show the error message:
```
You can only login via HTTPS
```

See it work fine: http://www.christianphotographers.com/community/

Ther is no ``fatal_lang_error($txt['login_ssl_required'], true)``.

**Comment by Sesquipedalian** [comment] 2018-11-13 06:08
I can't reproduce this. Also, the line numbers in the error message and backtrace don't match up with the current code. So I'm not sure what is happening on your setup, @Oldiesmann.

**Comment by smfbigguy** [comment] 2018-11-13 23:54
I have been getting sslredirect errors as well. The next time it pops up I will post here.

**Comment by smfbigguy** [comment] 2018-11-14 12:39
![ssl](https://user-images.githubusercontent.com/3620111/48483053-5c2ddc00-e7e0-11e8-90eb-c5a9f6704c32.png)

**Comment by albertlast** [comment] 2018-11-14 13:54
Your line of code are off to the github version.
Could you use the newest github version?

**Comment by smfbigguy** [comment] 2018-11-14 14:35
I just finished installing from GH yesterday morning. The lines may be off because of EhPortal being installed.

**Comment by albertlast** [comment] 2018-11-14 14:46
Could you upload your subs.php, so that we can look into?

**Comment by smfbigguy** [comment] 2018-11-14 16:45
Sorry had  to go to work. Here it is. I had to zip it.
[Subs.zip](https://github.com/SimpleMachines/SMF2.1/files/2581711/Subs.zip)

**Comment by albertlast** [comment] 2018-11-14 17:03
Well your subs got some heavy changes at some places,
so i'm not sure if the issue happen in a default setup,
but since the place is not checked well, the changes could valid any way:
https://github.com/SimpleMachines/SMF2.1/pull/5145
Try this pr if this fix you issue.

**Comment by smfbigguy** [comment] 2018-11-14 17:07
Ok, made the changes. I'll post back later. I gotta go to work again.

**Comment by smfbigguy** [comment] 2018-11-14 23:25
It's still giving errors.

**Comment by albertlast** [comment] 2018-11-15 04:11
Did the backtrace change?

**Comment by live627** [comment] 2018-11-15 04:22
lol I'm filling your error log, I'm so very naughty.

**Comment by smfbigguy** [comment] 2018-11-15 11:46
Lol. I will when more come up but yes it is filling up the logs still.

**Comment by albertlast** [comment] 2018-11-15 16:07
From what i see the root cause could be the ehportal,
because old meantion too that he use ehportal.

**Comment by smfbigguy** [comment] 2018-11-15 16:46
Well, so far there are no more errors. I woulda thought there would have been by now. I was also thinking of Ehportal but I'm not to sure.

**Comment by smfbigguy** [comment] 2018-11-15 23:27
Here is a screenshot of all errors since I left for work. There would be to many backtraces to screenshot so if you want one just ask.

![firefox_screenshot_2018-11-15t23-24-36 178z](https://user-images.githubusercontent.com/3620111/48588210-208c3280-e904-11e8-8700-ee255890919d.png)

**Comment by albertlast** [comment] 2018-11-16 04:39
Since this all errors from one call would be the first one the most interesting,
The first error is the lowest one
With the Errors.php(219) 
Please provide us from this the backtrace

**Comment by smfbigguy** [comment] 2018-11-16 05:07
Since my last post there have been code changes to some of my files and I am waiting to see what happens with that at the present moment. I can not provide that backtrace as I cleared my log. I am sorry. I can show you the edit that was made just now.

https://www.whatsurbeef.net/index.php?topic=1139.msg7018#msg7018

**Comment by smfbigguy** [comment] 2018-11-16 23:40
Ok, After the fix from Albertlast and updating EhPortal plus leaving the site for the whole day to see any errors....there is none. Not one error so far.

**Comment by albertlast** [comment] 2018-11-17 04:47
Could you remove my changes?
Maybe they not needed any more.

**Comment by smfbigguy** [comment] 2018-11-17 14:28
Yes I will, I have to go out for a second or two but when I get back I will revert the changes and see what happens.

**Comment by smfbigguy** [comment] 2018-11-17 19:48
OK, I removed your changes. Now lets see what happens.

**Comment by smfbigguy** [comment] 2018-11-18 01:20
Ok, after 5 hours and numerous guests online and members, there have been no errors. This is after I removed Albertlast's code. EhPortal has been update to the latest stable release and all is good I think....I'm very sure, lol.

**Comment by smfbigguy** [comment] 2018-11-18 22:44
We may be able to close this now. @Oldiesmann Have your errors been fixed.

**Comment by albertlast** [comment] 2018-11-19 05:33
The version 1.24 is not public at the moment.

**Comment by Oldiesmann** [comment] 2018-11-19 07:47
Mine haven't but I'm guessing if I change that fatal_lang_error to a die() they'll go away. Surprisingly though Baidu seems to be the only one triggering it and I can't trigger it myself no matter how hard I try.

**Comment by live627** [comment] 2018-11-19 10:41
that's why this is rather difficult

**Comment by albertlast** [comment] 2018-11-21 14:47
so close thise issue?

**Closed as completed** 2019-02-13 09:40 UTC
Labels: Login/Sessions
