### ISSUE TITLE
Integration Hooks Management is enabled regardless of the core feature being enabled

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#295] opened 2013-02-12 19:19 UTC
Just installed 2.1 from the GitHub repo.

Noticed that Admin > Configuration > Modification Settings > Integration Hooks is still available regardless if Integration Hooks Management is enabled in Admin > Configuration > Core Settings

Bug? :)

**Comment by matthew-kerle** [comment] 2013-02-12 20:42
Yep, as discussed in the topic over at SimpleMachines it's a bug. There was no condition added for the $subAction.

I'll throw out a solution, the method being that of which Suki suggested.

**Comment by NanoSector** [comment] 2013-02-12 21:51
According to emanuele it is as it is intended to be.

**Comment by Arantor** [comment] 2013-09-27 15:12
Random thought: what if we didn't make it an option on the Core Features page but just had it enabled by default regardless?

**Comment by Oldiesmann** [comment] 2013-09-27 16:05
The way things are currently coded, if you visit that page and the "core feature" isn't enabled, you can only enable/disable the hooks. If the feature is enabled, you can also remove them.

I'd prefer that the entire page be hidden if that feature is disabled, due to the possibility of breaking your forum by enabling/disabling a particular hook (though to be honest I'm not sure what the difference is between disabling it and actually removing it).

**Comment by illori** [comment] 2013-09-27 16:07
this feature to me just sounds like a good way for an admin to break their forum if they disable a hook or remove it without even knowing what a hook is.

**Comment by Arantor** [comment] 2013-09-27 16:09
Wait... even when the Core Feature is disabled you can still go to the page in question? If that's true, why is it even optional?

**Comment by illori** [comment] 2013-09-27 16:11
yep you can, and why is it under modification settings?

**Comment by Oldiesmann** [comment] 2013-09-27 16:15
Where else would you put it Illori? That seems like the most logical place for it to me.

**Comment by illori** [comment] 2013-09-27 16:18
i would make it its own menu branch and not a sub branch like it is now. yes it deals with mods but it is not a mod

as the modification settings page says "There are no modifications installed that have added any settings to this area yet." that makes me and many users assume that that whole section is for MODs and this is not a mod it is a core feature.

**Comment by Arantor** [comment] 2013-09-27 16:20
I'd put it under the Maintenance area personally.

**Comment by illori** [comment] 2013-09-27 16:22
that would make it harder for an admin to accidentally end up there

**Comment by emanuele45** [comment] 2013-09-27 16:27
Arantor wrote:

> Wait... even when the Core Feature is disabled you can still go to the
> page in question? If that's true, why is it even optional?

http://www.simplemachines.org/community/index.php?topic=497339.msg3489407#msg3489407

**Comment by Arantor** [comment] 2013-09-27 16:36
So I asked the same question 7 months ago and nothing's changed :P

**Comment by jdarwood007** [comment] 2013-09-28 22:17
Seems weird that integration hooks are a core enabled feature.  But disabling it should disable the page and disable the integration hooks system

**Comment by emanuele45** [comment] 2013-09-28 22:36
Actually you should probably read again both the issue and the topic. :stuck_out_tongue: 

Okay, let's try to explain it again here too:
1) integration hooks works the same as in 2.0, they don't need to be enabled, or disabled in core features to work,
2) the page `?action=admin;area=modsettings;sa=hooks` is always available,
3) the core feature, once enabled, allows to enable/disable/remove single functions (or files to be included) added by mods though the hooks system. Its intent is **not** (in any way or shape) to enable/disable the integration hooks system.

I added the option it because I didn't want to let the admin play with hooks without them **do** something (it's more a "devel" option or something like that, at the beginning I didn't even want to add it TBH).
I added it to the core features page because I didn't know where put it.

Do you want to move it somewhere else? Feel free.
Do you want to have the option to disable/remove hooks available by default without the need to activate anything? I find it risky, but feel free.
Do you want to remove that option and leave an informative page? Feel free, I'm not against. (Less (crappy, I wrote it and I know it it) code too.)

**Comment by Arantor** [comment] 2013-09-28 22:57
So, if the page is always available, what benefit does having the 'Core Feature' option give?

Specifically it does not fit with how Core Features works; the whole idea is that things disabled in there should not be active. That's how all the other options work, and so this should work the same.

If the option toggles some kind of admin area, fine... but it should either enable it or disable it when activated/deactivated; right now it does not look right in that you turn off the Feature but the page that it seems to relate to remains available.

Personally, and this is just me, I'd remove the option of it, and leave the page there, just moved to the admin panel. This removes any confusion over whether things are supposed to be enabled or disabled (this all ultimately comes out of the fact that we have a page that is supposed to be doing something and appears like it isn't doing it) - even if this is intended behaviour, it is not intuitive.

**Comment by jdarwood007** [comment] 2013-09-28 23:14
Personally, If it is in the core feature section, I would expect turning it off would turn off the integration section.  Perhaps it is just the wording of it to me.  I could see this as less confusing and more in-itune to what we want to do.
"Advanced Hooks/Integration Feature Controls"
"This feature allows advanced controls over the hooks/integration features in which customizations and bridges may be using to extend your SMF functionality."

Also on the page we need to add something like
"This feature allows advanced controls over hooks/integrations provided by installing mods, themes, bridges, authentication methods, bridges, etc.  By changing these features you may unexpectedly cause malfunctions or other parts of these SMF extensions to fail.  Please consult the customization's support documents for any extensions you wish disable hooks for."

**Comment by illori** [comment] 2013-09-28 23:23
i tried to get oldies to add a warning on this page, but he said that we dont do it for other pages in the admin panel, why add it here... [and i like the suggested warning from sleepy]

**Comment by Oldiesmann** [comment] 2013-09-29 18:17
Looking at the code (I haven't created any phony hook functions to test it yet), it seems that you can enable or disable individual hooks all the time, but you can only remove individual hooks entirely if that feature is enabled. This still allows users to break their forum without even reading that warning.

If we set it up such that they have to enable that feature to even access that page, and someone complains about their forum being broken, we can point to the part that says "Changing hooks can prevent your forum from working properly, so use this feature only if you know what you are doing.". I don't see why an additional warning is needed if we force them to enable a specific feature before being able to do anything with it.

**Comment by Arantor** [comment] 2013-09-29 19:33
Here's the thing... the Core Feature doesn't seem like that's what it should be doing >_<

**Comment by illori** [comment] 2013-09-29 19:35
or at least it does not act like the other core features do by default.

**Comment by Oldiesmann** [comment] 2013-09-30 04:36
It doesn't do what you'd think it would do at the moment, but it shouldn't be too difficult to fix that.

**Comment by Arantor** [comment] 2013-09-30 15:50
So what 'should' it do? There is a fundamental mismatch between expectation and reality, but I'm not entirely clear what the expectation should be either...

**Comment by illori** [comment] 2013-09-30 15:51
if we go by the other "core features" the page should not be visible anywhere at all when not enabled. that would be a good start IMO on fixing this.

**Comment by Oldiesmann** [comment] 2013-09-30 16:44
I agree. If the feature is disabled in the "core features" list, that page shouldn't be visible or accessible anywhere. If it is enabled, then they should be able to do everything they can currently do if it's enabled.

**Comment by Arantor** [comment] 2013-10-04 00:30
And therein lies the first part of the problem. Right now that's just not what's happening.

**Comment by NanoSector** [comment] 2013-10-06 14:30
So should we fix this or not?

**Comment by Arantor** [comment] 2013-10-06 20:29
Oh it should be fixed but no-one's entirely sure what the 'least worst' fix for any of it is.

**Comment by NanoSector** [comment] 2013-10-07 10:46
Seems rather logical to me - Make it work like people assume it works, which is by disabling the button and such entirely when the feature is disabled.

**Comment by Arantor** [comment] 2013-10-11 03:04
#706 solves this by making it enabled all the time and buried away in the maintenance area.

**Closed as completed by Arantor** 2013-10-11 03:04 UTC
Labels: Minor Bug
