### ISSUE TITLE
Version Information: Administration Centre

### ISSUE THREAD

**Issue by Acans** [SimpleMachines/SMF#566] opened 2013-08-10 05:47 UTC
2.1 thinks that the current version is 1.1.18 in the admin centre, but shouldn't it at least be saying 2.0.4 as the latest version?

**Comment by Oldiesmann** [comment] 2013-08-10 06:18
The way the version file works, if your version isn't 2.0.x, it falls back to 1.1.18 (because at the time 2.0 was released, 2.1 didn't yet exist). Once we release a beta of 2.1, we'll update the file accordingly. It's not worth the trouble to fix it now.

**Comment by emanuele45** [comment] 2013-08-10 11:03
Duplicate of #334

**Closed as completed by emanuele45** 2013-08-10 11:03 UTC
