### ISSUE TITLE
Search allows query by wildcard only

### ISSUE THREAD

**Issue by Gwenwyfar** [SimpleMachines/SMF#4605] opened 2018-03-10 17:25 UTC
This should probably be forbidden, or you'll get the entire forum as a result.

![wildcard](https://user-images.githubusercontent.com/28991853/37244906-e5c7e482-246e-11e8-8afa-728770ba4bf1.png)

**Comment by albertlast** [comment] 2018-03-10 17:28
I think it's a difficult request (no issue in my pov),
because a *a* or '* *' in my eyes very similiar.

**Comment by Gwenwyfar** [comment] 2018-03-10 17:32
You can't search for "a" because it hits minimum character limit. And I imagine this may be a problem for large forums.

**Comment by albertlast** [comment] 2018-03-10 17:41
I was mention ``*a*`` and ``* *``

**Comment by Gwenwyfar** [comment] 2018-03-10 17:43
Oh. Well, I don't know how much of a problem this can really be, so just leaving this for discussion.

**Comment by albertlast** [comment] 2018-03-10 17:45
for discussion we got the sm.org,
so when this a real issue is than we need to fix it.
When we like to discuss about this than is here the wrong place.

**Comment by albertlast** [comment] 2018-03-10 20:30
wildcard ``**`` search works only in mysql,
will look into tomorrow what the diff between pg and mysql logic is.

**Comment by albertlast** [comment] 2020-10-23 03:33
@Gwenwyfar @MissAllSunday  in the pr #4711 i mention #4606 and #4605 are closed by the pr,
but this here is still open.

**Comment by MissAllSunday** [comment] 2020-10-23 13:34
Linked issues are only closed when a PR gets merged, in the case of #4606 the PR got closed but never merged, hence this and any other referenced issue didn't got closed.

**Comment by albertlast** [comment] 2020-10-23 16:33
oh ic

**Comment by BrickOzp** [comment] 2021-01-08 12:51
I do not get any result when using ** for searching the entire forum on my test forum. Is this issue still valid?

**Comment by MissAllSunday** [comment] 2021-03-16 15:40
Will remove from RC4 for now. If anyone else can reproduce this issue please open a new issue.

**Closed as completed by MissAllSunday** 2021-03-16 15:40 UTC
Labels: Question, Search
