### ISSUE TITLE
Remove useless/unused bbc's

### ISSUE THREAD

**Issue by mcblaber** [SimpleMachines/SMF#1684] opened 2014-05-27 19:30 UTC
Old discussion URL - http://www.simplemachines.org/community/index.php?topic=516416

I think its about time we really remove the obsolute bbc's that 99.9% of SMF users don't use. Such as glow, shadow, marquee, and FTP. This will help make the slow parse_bbc a bit faster and can open up the possibility for more useful bbc's in the future. (Like a spoiler bbc for instance.)

**Comment by illori** [comment] 2014-05-27 19:38
i thought @dragooon did some work on the parser that would make this a non-issue. [or not so much of an issue]

**Comment by Dragooon** [comment] 2014-05-27 19:39
The parser work was mostly for memory issues, this might help speed up things a bit.

**Comment by mcblaber** [comment] 2014-05-27 19:40
Regardless I don't think we should have something practically no one uses. Hasn't the marquee tag been non-html compliant for years now?

**Comment by illori** [comment] 2014-05-27 19:48
do you mean the move tag? it does use marquee

although it is not completely valid

Line 230, Column 48: Element marquee not allowed as child of element div in this context. (Suppressing further errors from this subtree.)

```
                            <div class="inner" id="msg_94"><marquee>test</marquee></div>
```

**Comment by mcblaber** [comment] 2014-05-27 20:39
Yes the move tag, forgot SMF used different terminology for it. :P

**Comment by Oldiesmann** [comment] 2014-05-27 21:28
The marquee tag isn't valid HTML and never has been, but is just something that most browsers have come to support over the years. Wikipedia has more details: https://en.wikipedia.org/wiki/Marquee_tag

**Comment by mcblaber** [comment] 2014-05-28 00:03
Regardless of validity, I don't think it's needed. I can't think of 1 forum that has actually used it once. (Along with glow and FTP)

**Comment by margarett** [comment] 2014-05-28 00:34
And it's being unsupported fast... There was a support topic (more or less recently) where that question emerged.

**Comment by Oldiesmann** [comment] 2014-05-28 17:11
If we do remove it, we should offer it as a mod so those who do use it (as few as they may be) can still have it.

**Comment by XinYenFon** [comment] 2014-10-25 17:24
This is actually duplicate of #1545 can be closed :)

**Closed as completed** 2014-11-18 16:58 UTC
Labels: Parsers (BBC/Markdown)
