### ISSUE TITLE
Database error when attempting to export PMs?

### ISSUE THREAD

**Issue by Oldiesmann** [SimpleMachines/SMF#6805] opened 2021-06-26 03:58 UTC
#### Description
This error popped up in the error log of the seniors forum I host/run (RC3). I was unable to reproduce it on my test board running the latest GitHub build so it's possible this has been fixed already.

### Steps to reproduce
1. Go to your profile and select the option to export data including PMs
2. You will get this error in your error log

### Environment (complete as necessary)
- Version/Git revision: 2.1 RC3
- Database Type: MariaDB
- Database Version: 10.3.29
- PHP Version: 7.3.28

### Additional information/references
```
Database Error: '{db}.pm2.from_name' isn't in GROUP BY


		SELECT pm.id_pm, pm.msgtime, pm.subject, pm.body, pm.id_member_from, nis.from_name, nis.id_members_to, nis.to_names
		FROM smf_personal_messages AS pm
		INNER JOIN
		(
			SELECT pm2.id_pm, COALESCE(memf.real_name, pm2.from_name) AS from_name, GROUP_CONCAT(pmr.id_member) AS id_members_to, GROUP_CONCAT(COALESCE(mem.real_name, mem.member_name)) AS to_names
			FROM smf_personal_messages AS pm2
				INNER JOIN smf_pm_recipients AS pmr ON (pm2.id_pm = pmr.id_pm)
				INNER JOIN smf_members AS mem ON (mem.id_member = pmr.id_member)
				LEFT JOIN smf_members AS memf ON (memf.id_member = pm2.id_member_from)
			WHERE pm2.id_pm > 0
				AND (
					(pm2.id_member_from = 1154 AND pm2.deleted_by_sender = 0)
					OR (pmr.id_member = 1154 AND pmr.deleted = 0)
				)
			GROUP BY pm2.id_pm, memf.real_name
			ORDER BY pm2.id_pm ASC
			LIMIT 250
		) AS nis ON nis.id_pm = pm.id_pm
		ORDER BY pm.id_pm ASC

File: /.../Sources/News.php
Line: 2593
```

**Comment by Sesquipedalian** [comment] 2021-06-26 15:58
Duplicate of #6309

**Closed as completed by Sesquipedalian** 2021-06-26 15:58 UTC
