### ISSUE TITLE
Attachment settings problem ..

### ISSUE THREAD

**Issue by PortaMx** [SimpleMachines/SMF#3510] opened 2016-07-03 11:40 UTC
The test senario ..
1. Go to Admin - Forum - Attachements and Avatars - Attachment settings.
 -- works
2. Now go to Attachment Directorys
-- a error occous: bad jsons

Why?
At this point (around line 3379 in the Subs.php) the variable $modSettings['attachmentUploadDir'] IS a rry, so a json_decode fails.

I added a small test function (is_JSON) to the Subs.php and change the code to follow:

`
            if (!empty($modSettings['currentAttachmentUploadDir']))
            {
                if (!is_array($modSettings['attachmentUploadDir']) && smf_is_JSON($modSettings['attachmentUploadDir']))
                    $modSettings['attachmentUploadDir'] = smf_json_decode($modSettings['attachmentUploadDir'], true);
                $path = $modSettings['attachmentUploadDir'][$modSettings['currentAttachmentUploadDir']];
            }
`

The function smf_is_JSON itself:

`
function smf_is_JSON($data)
{
    call_user_func_array('json_decode', func_get_args());
    return (json_last_error() === JSON_ERROR_NONE);
}
`

This works also for PHP 5.3 ..

**Comment by Arantor** [comment] 2016-07-03 11:46
Looks like a duplicate of #3505

**Comment by PortaMx** [comment] 2016-07-03 12:14
Possible I think...
So SMF can use my fix for this solution 😋

**Closed as completed** 2016-07-10 17:40 UTC
