### ISSUE TITLE
Repair board errors

### ISSUE THREAD

**Issue by Butterflysaway** [SimpleMachines/SMF#6254] opened 2020-09-09 00:14 UTC
#### Description
 removed
 Today at 02:08:27 AM
 removed
 removed
Backtrace information Type of error: General
2: Unknown: Cannot call session save handler in a recursive manner
 https://website.com/index.php?action=admin;area=repairboards;step=22;substep=5789500;f0b8b0be=removed

 removed
 Today at 02:08:27 AM
 removed
 removed
Backtrace information Type of error: General
2: Cannot modify header information - headers already sent
 https://website.com/index.php?action=admin;area=repairboards;step=22;substep=5789500;f0b8b0be=removed
 /var/www/website.com/public_html/Sources/Subs.php (Line 7159)

### Steps to reproduce
1. Repair the board.
2. Doesn't happen every time.  Just when clicking the link produced in the error.  Not sure why it occurs or what's causing it.

### Environment (complete as necessary)
- Version/Git revision: latest smf2.1
- Database Version: mariadb
- PHP Version: 7.4 latest

**Comment by Butterflysaway** [comment] 2020-09-09 00:16
backtrace for the 2nd error shown.

#0: smf_error_handler()
Called from unknown on line -1
#1: header()
Called from /var/www/website.com/public_html/Sources/Subs.php on line 7159
#2: send_http_status()
Called from /var/www/website.com/public_html/Sources/Errors.php on line 169
#3: fatal_error()
Called from /var/www/website.com/public_html/Sources/Subs-Db-mysql.php on line 714
#4: smf_db_error()
Called from /var/www/website.com/public_html/Sources/Subs-Db-mysql.php on line 489
#5: smf_db_query()
Called from /var/www/website.com/public_html/Sources/Session.php on line 190
#6: sessionWrite()
Called from unknown on line -1

No backtrace information for the first error.

**Comment by live627** [comment] 2020-09-09 06:47
The timing of this is incredible. I just got around to finality looking at this routine which in my test forum just... loads forever. Seems to be a query at fault somewhere.

Thee output of the errors found during each step is saved in the session. You apparently have so many errors that it couldn't store the session.

**Comment by sbulen** [comment] 2020-09-09 06:50
Could it be the source of the session issues, too?  If it couldn't be stored (65K), the writeSession would fail...

**Comment by live627** [comment] 2020-09-09 07:16
a symptom in this case

**Comment by Butterflysaway** [comment] 2020-09-09 14:46
Should probably mention that I recently removed around 500k unactivated accounts without doing so on smf itself. I was running repair board to clean up logs, personal messages, sessions, etc

**Comment by Butterflysaway** [comment] 2020-09-09 14:53
I may just add all the cleanup for that to my automated script. I basically have a MMORPG game using the members table from smf for accounts to track when a player logs in the game after downloading it and purge accounts if they haven't logged in after x amount of days. It stops all spam on my forum from bots.

**Comment by albertlast** [comment] 2020-09-09 16:05
you should use the member delete function: deleteMembers
https://github.com/SimpleMachines/SMF2.1/blob/b9674508df9874c6d356e1b99fc95b553c2e1e6d/Sources/Subs-Members.php#L19-L35
Which can be providd with an array of userid's.

**Comment by MissAllSunday** [comment] 2020-12-06 15:19
A PR has been merged with a fix that mentions this issue, @Butterflysaway are you still able to reproduce this?

**Comment by sbulen** [comment] 2021-03-13 19:35
> 
> 
> Should probably mention that I recently removed around 500k unactivated accounts without doing so on smf itself. I was running repair board to clean up logs, personal messages, sessions, etc

**_I recommend closing this..._**

We saw this same issue during the beta for 2.0.18 (internal msg 4079485).  Repair boards keeps track of outstanding issues to solve in an array that gets saved to the session.  The data field on the session table is TEXT, and holds a max of 64K bytes.  Once you start introducing things like 500,000+ errors to be fixed, the data is truncated on the session. The session then cannot be decoded.  You're stuck.

We found that changing the data field on the session record from TEXT (64K) to MEDIUMTEXT (16MB) allowed the process to continue properly to completion.

I think if you are going to do this on any regular basis like this, you may need to change the data field to MEDIUMTEXT permanently.

I do not think this is a real operational issue for SMF.  Once you start doing things like deleting half a million records by hand, some offline & special treatment should be expected.

The SMF fix would be to change the data column to MEDIUMTEXT.  Given this is such a unique case, I am not sure we should do this.

**Comment by albertlast** [comment] 2021-03-13 19:42
or use postgres wher the size are unlimted :)

**Closed as completed** 2021-03-13 19:57 UTC
Labels: Administrative
