### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by smfbigguy** [SimpleMachines/SMF#5030] opened 2018-10-02 16:20 UTC
As per this post, the calendar is throwing errors caused by spiders:
https://www.simplemachines.org/community/index.php?topic=562437.msg3990510#msg3990510

### Steps to reproduce
1. Enable calendar
2. Give spiders enough permissions to see calendar
3. This will produce the errors in the post from SMF

### Environment (complete as necessary)
- Version/Git revision:
- Database Type: mariadb (from what phpmyadmin says)
- Database Version: 10.2.18
- PHP Version: 5.6

### Additional information/references

**Comment by smfbigguy** [comment] 2018-10-02 16:22
Pretty sure I did all that right.

**Comment by albertlast** [comment] 2018-10-02 18:08
Well I mention the issue already here: https://github.com/SimpleMachines/SMF2.1/issues/4886#issuecomment-425987040
but this issue got not reopen...

**Comment by smfbigguy** [comment] 2018-10-02 22:20
It's reopened now. :)

**Comment by Sesquipedalian** [comment] 2018-10-25 07:09
I am trying to find a way to reproduce this, but I haven't been able to. Are you still seeing these errors, @smfbigguy? If so, can you give me fuller information and more exact instructions on how I can reproduce it?

**Comment by smfbigguy** [comment] 2018-10-25 10:39
I had turned off permissions for spiders to see the memberlist. That took care of the error. I turned it back on just now so I will post the first error that comes up.

**Comment by smfbigguy** [comment] 2018-10-25 22:27
All I can do is give ya this. I still get the errors but they are from guests as well as google. It's just people trying to see stuff they can't I would imagine and being asked to login. That's all the info I have.
![bt](https://user-images.githubusercontent.com/3620111/47533964-a972f980-d883-11e8-8523-e17b64b5babb.jpg)
![firefox_screenshot_2018-10-25t22-23-54 698z](https://user-images.githubusercontent.com/3620111/47533965-a972f980-d883-11e8-88bd-127f177f0a9e.png)

**Comment by Sesquipedalian** [comment] 2018-10-25 23:15
Could you please go to `?action=admin;area=reports;rt=group_perms;st=print` and grab a screenshot of that? Hopefully that will help me figure out how to configure the permissions on my test forum in order to be able to reproduce the errors.

**Comment by smfbigguy** [comment] 2018-10-25 23:31
Yup, here ya go

![firefox_screenshot_2018-10-25t23-31-16 314z](https://user-images.githubusercontent.com/3620111/47536135-94e72f00-d88c-11e8-9a53-246ef67021cd.png)

**Comment by smfbigguy** [comment] 2018-10-25 23:32
Battle is not installed anymore and neither is articles. There is a spot in Ehportal for articles but I don't use it.

**Comment by jdarwood007** [comment] 2018-10-26 01:00
From what I can tell in the back trace, it seems this is being triggered when a guest hits the post page.

**Comment by Sesquipedalian** [comment] 2018-10-26 03:59
> Yup, here ya go

Thanks. I'm getting on a plane tomorrow for a few days of travel, but I'll look forward to working on this more next week. Hopefully this info will help me to reproduce the error when I do.

> From what I can tell in the back trace, it seems this is being triggered when a guest hits the post page.

Which is weird. I haven't been able to reproduce it, not even when I fake my user agent to impersonate the GoogleBot spider.

**Comment by SychO9** [comment] 2018-10-26 11:30
When I visit @smfbigguy 's forum as a guest and try to access the calendar, the login_cookie_times is undefined, which has been fixed in #4886 
I don't think there is anything to fix here, his forum setup just isn't up to date with the latest changes
look for yourself, you can't reproduce it, because there's nothing to reproduce
https://www.whatsurbeef.net/index.php?action=calendar

![melocal](https://user-images.githubusercontent.com/20267363/47563745-16899c00-d923-11e8-80bb-11471c1df39d.png)
My Local setup

![whatsurbeef](https://user-images.githubusercontent.com/20267363/47563746-17223280-d923-11e8-866f-36882e98e19a.png)
His forum

**Comment by smfbigguy** [comment] 2018-10-26 12:00
That may be true. I will update today when I get home from work. I don't have time to do it this morning. It has been a week or to since an update to the site.

**Comment by smfbigguy** [comment] 2018-10-26 12:01
Your screenshot looks different than mine for some reason.

![firefox_screenshot_2018-10-26t12-01-06 640z](https://user-images.githubusercontent.com/3620111/47565114-589be900-d8f5-11e8-81a8-41753b58d990.png)

**Comment by SychO9** [comment] 2018-10-26 12:02
That's because I'm not opening the login box, I'm accessing the calendar as a guest

**Comment by smfbigguy** [comment] 2018-10-26 12:04
Oh ok. :)

**Comment by jdarwood007** [comment] 2018-10-26 21:52
Did updating the git checkout resolve it?

**Comment by smfbigguy** [comment] 2018-10-26 22:23
I am going to update tonight. Just got home from work.

**Comment by smfbigguy** [comment] 2018-10-27 00:09
I have completed an update right from GH. I just got finished. Well, installing mods now.

**Comment by smfbigguy** [comment] 2018-10-27 02:53
I have had over 60 people on the forums so far since my last post and no errors...for this issue. I started a new topic on SMF about something else. We figured it out but not sure if it's a bug. I won't go into that here though.

**Comment by smfbigguy** [comment] 2018-10-27 23:04
I think this can be closed.

**Comment by Sesquipedalian** [comment] 2018-10-29 21:06
Great. Thanks for testing, @smfbigguy. If the problematic behavous reappears, we can reopen this.

**Closed as completed by Sesquipedalian** 2018-10-29 21:06 UTC
Labels: Calendar

**Comment by smfbigguy** [comment] 2018-10-29 22:30
Sounds good.
