### ISSUE TITLE
gravatar enabled, avatar does not show up in profile

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2275] opened 2014-09-10 11:16 UTC
if you enable gravatar for forum users, force gravatars to be used instead of normal avatar in the admin panel it selects an avatar for the users but it does not show it in the profile nor next the users name in the top menu. this may be because the no avatar option is selected where it should show the avatar anyway? if you select use my gravatar in the profile then it shows up.

**Comment by MissAllSunday** [comment] 2014-09-10 15:09
It seems this is a problem with chrome/opera/firefox.  IE shows them just fine...  I have no idea why, must be some browser security measure or something?  is not only related to SMF, other sites that uses gravatar seems to have this same issue

**Comment by illori** [comment] 2014-09-10 15:11
then why does it work correctly when i select the use my gravatar option? then i see the avatar in the profile.

**Comment by MissAllSunday** [comment] 2014-09-10 15:14
doh!   Nervermind...  its ghostery....  its blocking gravatars...

I assume you have ghostery as well?  if thats the case then I go ahead and close this

**Comment by illori** [comment] 2014-09-10 16:51
i have ghostery but i dont have gravatar blocked.

**Comment by illori** [comment] 2014-09-10 17:25
please reopen this.

**Comment by MissAllSunday** [comment] 2014-09-10 23:09
Then I can't reproduce this at all.

**Comment by illori** [comment] 2014-09-11 09:10
have you set it that gravatar is not an option, set your profile to no avatar [confirm none is shown] then enable gravatar again?

**Comment by Dragooon** [comment] 2014-09-11 13:24
Basically avatar is not being shown under Forum Profile section when No Avatar is selected there but Gravatar is forced for all users. I'm not sure if that's intentional or not.

**Comment by MissAllSunday** [comment] 2014-09-11 13:41
I can still see my gravatar just fine.  Thing is, there isn't any room for any possible variations, the avatar gets set on one place only, if there is any quirks I'm betting is due to a cache issue or something similar.

**Comment by NanoSector** [comment] 2014-09-11 13:43
My cache is disabled and I also have this problem.

**Comment by illori** [comment] 2014-09-11 13:44
maybe if gravatar is forced, the option to have no avatar should be disabled. that should resolve this issue i believe.

**Comment by MissAllSunday** [comment] 2014-09-11 14:13
Well, that what it should be doing anyway, if there is any other option besides gravatar then it means you aren't really enforcing it.

Anyway, can't reproduce this. In fact, if I select no avatar while enforcing gravatars is on, I still get the gravatar because thats how the logic on forcing a gravatar works on Load.php it checks for enforcing a gravatar and if its set, it shows a gravatar.

**Comment by illori** [comment] 2014-09-11 14:15
if i click no avatar it removes the gravatar which i have set in the admin panel to force.

**Comment by NanoSector** [comment] 2014-09-11 14:21
Oh I can't reproduce that either, it only misses in the profile button and the little popup. It shows on my profile.
Though isn't it a bit odd that it shows the no avatar option while it is going to enforce an avatar anyway?

**Comment by jsqx** [comment] 2014-09-11 15:22
I don't know it is the same but no avatar from the gallery or loaded doesn't show in mini popup on the top. Once was shown. 

![minipopup](https://cloud.githubusercontent.com/assets/8003629/4236477/63a949e0-39c7-11e4-8cb2-89f7249da2a7.png)

And miniature of avatar is losing the quality.

**Comment by jsqx** [comment] 2014-09-13 18:03
I would like to ask if avatar will be shown in mini popup? As like was once.

**Comment by NanoSector** [comment] 2014-09-13 21:50
I remember it being in there at one point. Not sure. There's no code in the profile mini template related to avatars, though.

**Comment by live627** [comment] 2014-09-14 04:29
It was replaced with the smaller one on the button.

**Comment by jsqx** [comment] 2014-09-14 11:44
And it won't back? But it was good, showed of real avatar size, now is empty without this.

**Comment by XinYenFon** [comment] 2014-10-10 23:57
seems $context['member']['avatar'] has no problem with forced/non-forced Gravatar, but $context['user']['avatar'] has problems :P

**Comment by Dragooon** [comment] 2014-11-15 17:31
Closing this, No Avatar option is still valid even if Gravatar is forced.

**Closed as completed by Dragooon** 2014-11-15 17:31 UTC
Labels: Avatars

**Comment by illori** [comment] 2014-11-15 18:30
I don't agree. If the admin is forcing the user to have a default avatar
that is gravatar they should not be allowed to have no avatar.
