### ISSUE TITLE
Undefined indexes on cron

### ISSUE THREAD

**Issue by NanoSector** [SimpleMachines/SMF#2302] opened 2014-09-12 22:40 UTC
I think I reported this before... Not sure, can't find it.

The database value you're trying to insert does not exist: id_member
File: /mnt/data/Web/smf21/Sources/Mentions.php
Line: 93

Undefined index: id
File: /mnt/data/Web/smf21/Sources/tasks/CreatePost-Notify.php
Line: 44

Both are called from the cron.php url.

**Comment by XinYenFon** [comment] 2014-09-13 05:14
I'm sure I reported it check my issues

-----Original Message-----

**Comment by Oldiesmann** [comment] 2014-09-13 16:33
Duplicate of #1980.

**Closed as completed by Oldiesmann** 2014-09-13 16:33 UTC
