### ISSUE TITLE
Field inscription over avatar

### ISSUE THREAD

**Issue by Yariksat** [SimpleMachines/SMF#3585] opened 2016-09-16 15:11 UTC
Profile in settings does not work to disconnect users from installing signs on avatar. Disabling this nick - still can see and edit the signature of the avatar.

**Comment by MissAllSunday** [comment] 2016-09-17 15:38
I'm sorry, I couldn't understand what you are trying to say.

**Comment by Yariksat** [comment] 2016-09-19 15:30
It does not work in the access rights you want to access the signature of the avatar.
Users can still edit them

**Comment by illori** [comment] 2016-09-19 20:22
that still does not make a lot of sense. what exactly are you doing? what permissions are in place? who is trying to do what exactly?

**Comment by Yariksat** [comment] 2016-09-20 14:37
To note ban
![30](https://cloud.githubusercontent.com/assets/17574854/18674693/c1902316-7f58-11e6-9898-99f6e44e67eb.jpg)
The user sees the field
![31](https://cloud.githubusercontent.com/assets/17574854/18674817/25e51a7e-7f59-11e6-821e-0623753d9144.jpg)

**Comment by frandominguezl** [comment] 2016-09-20 14:48
That's a lot better. Just to be sure, the image below is an image from your profile or from an user profile? As admin, you can still editing that field for you and for users.

**Comment by Yariksat** [comment] 2016-09-20 16:50
The user profile of test certainly

**Comment by frandominguezl** [comment] 2016-09-21 14:50
But are you accessing the user profile via your ADMIN account? Because I cannot reproduce the issue in my test site.

**Comment by Yariksat** [comment] 2016-09-22 03:28
No, this profile test account
SMF upgrade to 2.0.11

**Comment by frandominguezl** [comment] 2016-09-22 18:08
You can disable the cutom titles via Admin > Configuration > Features and Options > General > Enable custom titles

Try this and tell us :)

**Comment by Yariksat** [comment] 2016-09-25 08:10
If you turn off so the field is turned off completely
  I need that it worked in 2.0.11

**Comment by frandominguezl** [comment] 2016-09-25 09:06
This is not the place to ask for support of 2.0.x. For that, you should go to our Community Forums - http://www.simplemachines.org/community/

Anyway, that feature work on 2.0.11

**Comment by Yariksat** [comment] 2016-09-25 11:57
I have SMF 2.1 and this function does not work as it should.
It must be switched off when I put a ban on the access rights and the user should not see it.

**Comment by illori** [comment] 2016-09-25 12:42
duplicated issue...
Profile_modify.php on line 560 checks on permission profile_other, it should check on profile_title instead.

**Comment by Yariksat** [comment] 2016-09-25 14:11
Thanks, it works

**Comment by illori** [comment] 2016-09-25 15:53
why did you close this? the fix is not part of the repo yet. please reopen so this can be officially fixed.

@MissAllSunday please reopen so this can get fixed.

**Comment by Yariksat** [comment] 2016-09-25 16:41
Fix is working, verified.
Everything works as must to work

**Closed as completed** 2016-09-27 14:21 UTC
