### ISSUE TITLE
Registered Members - Every member of the forum is a member of this group.

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#398] opened 2013-06-05 20:19 UTC
on the group membership page it has the option to change your primary group to the "Registered Members" group which does not exist by that name... it is "Regular Members"

and it states incorrectly that "Every member of the forum is a member of this group." only if you are not in another primary group are you in "Regular Members".

This group has no real purpose and is not a group you can select to join but by the admin user.

i would recommend removing this from the group membership page.

**Comment by emanuele45** [comment] 2013-06-05 22:27
[00:23] emanuele    registered members is needed
[00:24] emanuele    because registered members is a group you can select to assign to yourself as primary
[00:25] emanuele    even as regular user you can decide to make "registered users" primary group from that interface
[00:26] emanuele    so definitely it cannot be removed from there

**Comment by illori** [comment] 2013-06-05 23:02
but it is not named registered members in the admin panel, it is regular members, so change the name of it?

also not everyone is in the group, so it should not show to everyone, or change the text that shows below it.

**Comment by Arantor** [comment] 2013-09-27 15:10
Seems to me there's a wider issue. Perhaps it should apply to everyone who is a registered member.

**Comment by Arantor** [comment] 2013-11-07 05:18
We can't meaningfully change that at this stage, thinking about it, mostly because of the number of issues it could cause in terms of upgrading and permissions. This is something we can fix more thoroughly in future versions but not in what was intended as an interim release.

**Closed as completed** 2013-11-07 05:28 UTC
