### ISSUE TITLE
"Undefined index: label" in SMF 2.1 - Beta 2

### ISSUE THREAD

**Issue by cyraid** [SimpleMachines/SMF#3654] opened 2016-10-24 18:18 UTC
"Undefined index: label" error in "Themes/default/languages/Who.english.php" line 68 (generic_menu_dropdown_above sub template - eval?)

Did someone forget an 'isset'? I get this error quite frequently in the error log.

**Comment by albertlast** [comment] 2016-10-24 21:25
please use a fresh version of github version
the beta2 is very very old

**Comment by illori** [comment] 2016-10-24 21:34
also disable template eval, bugs reported with eval in them are useless as it does not tell where the error is happening.

**Comment by cyraid** [comment] 2016-10-24 21:42
How would one go about upgrading from 2.1 Beta 2 to the github version? I downloaded the zip (SMF2.1-release-2.1.zip), but I'm not sure the 'upgrade' process? Do I just unzip and copy settings.php, agreement.txt?

**Comment by illori** [comment] 2016-10-24 21:49
http://wiki.simplemachines.org/smf/Contributing_to_SMF#How_to_install_SMF_from_github

**Comment by albertlast** [comment] 2016-10-25 05:42
ther is no upgrade from beta2 to github

**Comment by cyraid** [comment] 2016-10-25 15:19
Well.. Tried the upgrade like illori suggested, but failed near the end with "malformed JSON" (I'm guessing it's the one Poll I had), and now I'm getting "Json decode error: Syntax error, malformed JSON", and a "Undefined index: can_remove_poll" whenever I view the Poll.. Any fix for it?

(Malformed Bug -- /Sources/Load.php, Line: 1513)
(Undefined index -- /Sources/Display.php, Line: 804)

**Comment by cyraid** [comment] 2016-10-30 21:44
Fixed the malformed JSON (the custom profile fields just had to be recompiled into display user fields), by going to the profile fields area and saving it.  The can_remove_poll is still not working.. Took a quick look at the code, and didn't bother looking deeper because I don't have that much time, but could also be another DB error? I really didn't want to reset it all, and do all the settings and stuff from scratch, I think I would just move onto different Forum Software if that were the case..

**Comment by illori** [comment] 2016-10-31 09:26
https://github.com/SimpleMachines/SMF2.1/issues/3634

**Comment by live627** [comment] 2016-12-10 00:30
@cyraid which database server do you use, MySQL or PostgreSQL?

**Comment by cyraid** [comment] 2016-12-12 00:17
@live627 I use MySQL :)

**Comment by frandominguezl** [comment] 2016-12-30 12:48
What about this? Can be closed or the issue is still happening?

**Comment by frandominguezl** [comment] 2017-01-28 21:32
I haven't been able to reproduce this, and since the OP is not answering, maybe we should close this @Oldiesmann

**Comment by cyraid** [comment] 2017-01-29 00:18
Don't drop the issue. Yes it still happens... And since there's no way to upgrade between betas now that the recommended way to upgrade failed on some JSON parts, I'm screwed and can't use SMF.. so I'm gonna use something else. :P have fun guys!

**Comment by cyraid** [comment] 2017-01-29 00:19
(you can close it if you want, but just saying it was still happening)

**Closed as completed** 2017-03-23 16:00 UTC
