### ISSUE TITLE
Upgrader - Tables remain MyISAM after upgrade

### ISSUE THREAD

**Issue by sbulen** [SimpleMachines/SMF#3867] opened 2017-01-25 04:38 UTC
Just completed a brand new round of tests of the upgrader, & noticed that my 2.0 tables that had a MyISAM engine remained on MyISAM after the upgrade to 2.1.  

I think we want those changed to InnoDB, right?  (Newly installed tables are all properly set to InnoDB.)

**Comment by albertlast** [comment] 2017-01-25 05:03
Please hav a look at the guide from mysql: https://dev.mysql.com/doc/refman/5.7/en/converting-tables-to-innodb.html
and hav in mind that the min version of mysql smf supported 5.0 is.
This mean the alter table command how switch the db engine from myisam to innodb we can not use (it'
s require 5.5+).
Without that the commands,
this topic get very complex and the project trys to get stable enough to leave the beta status.

**Comment by sbulen** [comment] 2017-01-25 17:00
Ouch.  

You are correct, the release notes for 5.4 & prior indicate a more involved process:
http://mysql.localhost.net.ar/doc/refman/5.4/en/converting-tables-to-innodb.html

**Comment by jdarwood007** [comment] 2017-01-25 22:44
I would also leave the changing over to the admin rather than the upgrade script.  Big boards that are still on MyISAM (for some awful reason) could experience outages lasting hours if they try to convert big tables like messages over.

**Comment by sbulen** [comment] 2017-01-26 03:23
That makes sense.  

Should we close this out?   Or should we consider a modest mod to the Upgrader to ALTER the tables to InnoDB when MySQL >= 5.5?

**Comment by Oldiesmann** [comment] 2017-01-26 03:36
The problem is that it takes a really long time to convert larger tables, not that it's harder to do on older versions of MySQL. We can just close this.

**Closed as completed by Oldiesmann** 2017-01-26 03:36 UTC
