### ISSUE TITLE
Characters immediately after a quote tag get stripped

### ISSUE THREAD

**Issue by jmvalente** [SimpleMachines/SMF#4967] opened 2018-08-27 20:17 UTC
Here is how they show up on 2.1 Beta 3
![image](https://user-images.githubusercontent.com/55451/44683383-36c8d780-aa14-11e8-8634-2dada0446b79.png)

Quoting the post does show the full message within the text
![image](https://user-images.githubusercontent.com/55451/44683425-58c25a00-aa14-11e8-8fea-58e207263e92.png)

it also doesn't seem to be entirely consistent as my own post shows up fine here, but I've run into it on other posts.  I also posted my own thread to try quoting myself and it doesn't happen, so I can't be sure _which_ conditions trigger this behavior but it is frequent.

**Comment by frandominguezl** [comment] 2018-08-27 22:34
Don't use Beta 3. Download it from GitHub and try again, there are a lot of commits ahead since Beta 3 was released.

**Comment by wintstar** [comment] 2018-08-27 23:17
> Don't use Beta 3. Download it from GitHub and try again, there are a lot of commits ahead since Beta 3 was released.

Then on the download page of simpelmachines.org a note should be displayed that it is outdated or the download of Beta 3 should be deactivated. Same with the Beta 3 language packs. Who downloads Beta 3 there will be dissatisfied and will not continue testing.

**Comment by frandominguezl** [comment] 2018-08-27 23:41
As its name says, its a Beta. There's no need to include a note or remove the download because its what it is, a Beta release.

**Comment by jmvalente** [comment] 2018-08-28 18:39
>Don't use Beta 3. Download it from GitHub and try again, there are a lot of commits ahead since Beta 3 was released.

I'll have one of the admins grab the code from here and try that.

**Comment by smfbigguy** [comment] 2018-08-28 20:26
Not all files from the zip archive from here get uploaded. There is a nightly build link somewhere that is good to use.

https://www.simplemachines.org/community/index.php?topic=558451.msg3971841;topicseen#top

**Comment by sbulen** [comment] 2018-08-29 03:11
I cannot reproduce in the github version.  Yes, please try the github version.  
I agree, the beta 3 version link should be put to rest...

**Comment by Sesquipedalian** [comment] 2018-09-01 22:58
This was fixed in #4137

**Closed as completed by Sesquipedalian** 2018-09-01 22:58 UTC

**Comment by jmvalente** [comment] 2018-09-04 15:48
>This was fixed in #4137

Oof. Thanks.  Is the beta link on the website really 1+ years out of date?
