### ISSUE TITLE
Database upgrade hanging 2.0.11 - > 2.1b3

### ISSUE THREAD

**Issue by PhuriousGeorge** [SimpleMachines/SMF#3387] opened 2016-04-09 23:18 UTC
After using Firefox and enabling extra debug, I found I'm timing out on database upgrades at:
`Executing: "Messenger fields" (17 of 42)`

According to the extra debug information I was able to get, the following item was the last to be completed:
`Add an order value to each existing cust profile field...done`

**Comment by albertlast** [comment] 2016-04-10 05:33
Did you a rollback to 2.0.11 of you database before you try this version of the upgrade?
Maybe the upgrade of the beta2 change you database in a version between 2.0.11 and 2.1b2.
And the beta3 upgrade can't handle this.

**Comment by PhuriousGeorge** [comment] 2016-04-10 05:47
This was attempted on a fresh 2.0.11 conversion. I restored a backup at each attempt.

**Comment by albertlast** [comment] 2016-06-06 19:49
What is the status of this issue?

**Comment by MissAllSunday** [comment] 2016-07-10 17:43
@PhuriousGeorge Does this issue still happens to you while using the latest build?

**Comment by dodexahedron** [comment] 2016-09-11 15:45
This issue is happening for me, too, on the current build.
Upgrading from 2.0.2 to current build (As of now).
It hangs exactly where @PhuriousGeorge said, and doesn't even output the next line in the upgrade_2-1_mysql.sql file, which is:
---# Converting member values

This is on php-fpm 5.6 and nginx 1.10
PHP error logging is turned on and I get nothing at this step to indicate what's going on.

![image](https://cloud.githubusercontent.com/assets/8242181/18418478/325d753a-7815-11e6-8e78-cde4208844ee.png)

**Comment by dodexahedron** [comment] 2016-10-16 14:05
Still occurring on the most recent beta release.

**Comment by sbulen** [comment] 2017-01-27 19:03
I believe this is a duplicate of:
Upgrade Issue - Can't get past Step 4 #3833

Which was addressed in this PR:
Fix upgrade migration of fields from members to themes #3842

**Comment by sbulen** [comment] 2017-01-31 05:38
This should be closed.

**Comment by XinYenFon** [comment] 2017-03-02 22:53
Can we get feedback from @PhuriousGeorge and/or @dodexahedron while trying with latest build ? Then we can close or move forward with this.

**Comment by PhuriousGeorge** [comment] 2017-03-02 23:14
Sorry, I'll give the latest a go over the weekend and report back

**Comment by colinschoen** [comment] 2017-03-23 16:02
@PhuriousGeorge Bump

**Comment by frandominguezl** [comment] 2017-08-27 19:01
No news from @PhuriousGeorge, maybe we should close this

**Comment by sbulen** [comment] 2017-09-07 10:40
This one should still be closed...

**Comment by frandominguezl** [comment] 2017-09-08 13:53
@Sesquipedalian

**Closed as completed** 2017-09-10 03:12 UTC
