### ISSUE TITLE
Unwatched topics still show in the unread topics pages

### ISSUE THREAD

**Issue by live627** [SimpleMachines/SMF#6907] opened 2021-08-03 16:23 UTC
#### Description
--Description Here--

### Steps to reproduce
1. Have a multi-page tropic
2. Mark only the first page read
3. Set the topic's alert prefs to ignore
4. Observe the topic is still in the unread lists

### Additional information/references
I have a fix coming shortly which  modifies the queries to have the requisite predicate in the `WHERE` clause rather than the `ON` clause of `LEFT JOIN`.

**Comment by Sesquipedalian** [comment] 2021-08-03 22:21
I can't reproduce this.

What I did:

1. Went to a multi-page topic that my user was watching.
2. Clicked the "Mark Unread" button, which of course took me back to the topic index and marked the topic as unread.
3. Verified that the topic appeared in both "Unread Posts" and "Updated Topics" (it did).
4. Viewed the first page of the topic again.
5. Selected "Not Following" in the notification button menu.
6. Checked both the "Unread Posts" and "Updated Topics" lists.

Result: the topic did not display in either list.

**Comment by live627** [comment] 2021-08-04 03:40
That's perplexing. I was able to reproduce on localhost, @smfbigguy's site, and a unit test.

Can you confirm that the topic in log_tropics has a msg id that is between the first and last messages?

**Comment by Sesquipedalian** [comment] 2021-08-06 00:39
I'll try it again soon and let you know.

**Comment by Sesquipedalian** [comment] 2021-08-08 17:35
Confirmed. The topic is unwatched and id_msg is set to the id of one of the replies to the topic.

log_topics table (filtered to hide irrelevant rows):
![Screen Shot 2021-08-08 at 11 27 15 AM](https://user-images.githubusercontent.com/191731/128640379-6494d00b-6d7b-465f-9cc0-387b75845416.png)

messages table (filtered to hide irrelevant rows):
![Screen Shot 2021-08-08 at 11 26 45 AM](https://user-images.githubusercontent.com/191731/128640418-4cbb75f3-f1ae-46d4-aecd-4d0137e94909.png)

Result: topic 135 is marked as new on the message index, but does not show up in `?action=unread` or in `?action=unreadreplies`:
![Screen Shot 2021-08-08 at 11 28 08 AM](https://user-images.githubusercontent.com/191731/128640540-3f818535-2ee2-40ab-ac71-2bafc9ca3853.png)
![Screen Shot 2021-08-08 at 11 34 45 AM](https://user-images.githubusercontent.com/191731/128640555-e95c0a23-c1f6-402e-a0fd-def2e0a224f5.png)
![Screen Shot 2021-08-08 at 11 34 54 AM](https://user-images.githubusercontent.com/191731/128640558-6c27580e-4060-4e95-b6df-825d49b3818e.png)

**Closed as completed** 2021-08-21 07:41 UTC
Labels: Topics
