### ISSUE TITLE
Deleted Member - Database Error

### ISSUE THREAD

**Issue by xrunner** [SimpleMachines/SMF#342] opened 2013-04-25 14:57 UTC
I completely deleted a member yesterday (all posts and topics) and after that I started receiving this error message -

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CASE WHEN mem.id_group = 0 OR mg.icons = '' THEN pg.icons ELSE mg.icons END AS i' at line 10
File: /home/thesite9/public_html/spamhaven/Sources/Load.php
Line: 960

I could not repair the error and it would not go away even after I performed another 2.1 upgrade and an install leaving the database intact. I started over with a new database and of course the error was gone then.

**Comment by Oldiesmann** [comment] 2013-04-25 15:50
After looking at the code, I found out what the problem is. It's actually caused by disabling custom titles - not related to deleting a member.

```
mem.is_activated, mem.warning' . (!empty($modSettings['titlesEnable']) ? ', mem.usertitle, ' : '') . '
CASE WHEN mem.id_group = 0 OR mg.icons = {string:blank_string} THEN pg.icons ELSE mg.icons END AS icons';
```

If custom titles are disabled, there's no comma between "mem.warning" and the "CASE WHEN" statement, so it causes an error. Will commit a fix shortly, but this will fix it:

```
mem.is_activated, mem.warning,' . (!empty($modSettings['titlesEnable']) ? ' mem.usertitle, ' : '') . '
CASE WHEN mem.id_group = 0 OR mg.icons = {string:blank_string} THEN pg.icons ELSE mg.icons END AS icons';
```

**Comment by xrunner** [comment] 2013-04-25 15:51
```
On 4/25/2013 10:41 AM, Oldiesmann
  wrote:

  Do you know what the full query is that it was trying to run?
    That particular line is used whenever we pull member data, so I
    don't see why deleting a member would cause it to fail.
  —
    Reply to this email directly or view
      it on GitHub.

No I don't know what the full query was, and I might be wrong about
the deletion of the member, it may be a coincidence. All I know is
the forum was up for several weeks and yesterday after I deleted a
member's account I got that message and I could not fix it. Kindred
advised that I report the error here.
```

**Comment by xrunner** [comment] 2013-04-25 15:52
Great!

**Comment by illori** [comment] 2013-06-05 19:35
oldies have you had a chance to commit this?

**Comment by Oldiesmann** [comment] 2013-06-06 03:35
No, not yet. Let me make sure nobody else has committed this yet and get my fork up to date, then I'll throw a fix in there for it.

**Comment by Oldiesmann** [comment] 2013-06-06 05:40
Just checked Load.php again and it appears this has already been fixed in another commit, so I'm going to close this for now.

**Closed as completed by Oldiesmann** 2013-06-06 05:40 UTC
Labels: Minor Bug
