### ISSUE TITLE
Newsletters no longer working?

### ISSUE THREAD

**Issue by VBGAMER45** [SimpleMachines/SMF#5503] opened 2019-03-11 21:18 UTC
#### Description
I tried sending newsletters to myself and couple member on my forum.
I have the background fix mod applied to my forum.

When sending email says sent but nothing is received.  Mail queue is empty.
Tried different isp's for the email.
I get other emails such as notifications for the forum but not newsletters.

I also noticed today some one else has the same issue
https://www.simplemachines.org/community/index.php?topic=565850.0

### Steps to reproduce
1.  Try sending a newsletter to yourself or members on the forum.

### Environment (complete as necessary)
- Version/Git revision: SMF 2.1 RC1 Release
- Database Type: MySQL
- Database Version:
- PHP Version: 7.1

### Additional information/references
https://www.simplemachines.org/community/index.php?topic=565850.0

**Comment by smfbigguy** [comment] 2019-03-11 22:02
Would these screenshots be relevant I tried a test mail and got this error. I did not get an email either.

**Comment by Oldiesmann** [comment] 2019-03-12 03:58
It might be an issue with RC1. I just tested it on one test board running a recent git build and it worked fine on that one. Will try on a stock RC1 board in a bit.

@smfbigguy That's just a missing language string I believe. That shouldn't have anything to do with newsletters.

**Comment by MarkRH** [comment] 2019-03-12 05:02
I have the same symptoms as @VBGAMER45 .  I get the green message that it's been added to the queue to send but is never sent and the queue is empty.  No error messages in forum or external PHP error log.  I'll try the latest Git version and do a file comparison to what I downloaded.

**Comment by smfbigguy** [comment] 2019-03-12 11:15
> 
> 
> Would these screenshots be relevant I tried a test mail and got this error. I did not get an email either.
> 
> Posted edited. Missing language string.

**Comment by sremick** [comment] 2019-03-12 13:27
I'm the other person vbgamer45 mentioned. I tried a newsletter to all 12 test users, then just to 1 user (myself). None were received. The "Test Email" function in SMF works fine. I'll provide details about my system:

- Version: 2.1 RC1
- Database type: MySQL 
- Database Version: 10.1.37-MariaDB-cll-lve
- PHP Version: 7.2.15
- Server: LiteSpeed V7.2 

Also: in email settings I'm using SMTP, a server prefixed w/ ssl://, and port 465

**Comment by SychO9** [comment] 2019-04-18 21:32
Do your members have **Receive forum newsletters, announcements and important notifications by email.** in their notification settings ? it is disabled by default.

**Comment by sremick** [comment] 2019-04-19 04:00
> Do your members have **Receive forum newsletters, announcements and important notifications by email.** in their notification settings ? it is disabled by default.

I see no such setting anywhere. In the General settings, I do have "Allow users to disable announcements" unchecked, so if newsletters are now lumped in under "announcements" then that could explain why I don't see the option per user. 

But it's worth noting that when I send a newsletter, even if I check the box for " Override notification settings", it is not received by the user.

**Comment by vort7u** [comment] 2019-04-19 04:30
@sremick
https://github.com/SimpleMachines/SMF2.1/pull/5583

**Comment by SychO9** [comment] 2019-04-19 09:17
> I see no such setting anywhere. In the General settings, I do have "Allow users to disable announcements" unchecked, so if newsletters are now lumped in under "announcements" then that could explain why I don't see the option per user.
> 
> But it's worth noting that when I send a newsletter, even if I check the box for " Override notification settings", it is not received by the user.

And your **Mail Queue** is empty when you "Override notification settings" ?

**Comment by sremick** [comment] 2019-04-19 13:33
>  And your **Mail Queue** is empty when you "Override notification settings" ?
Yes. Not mentioned previously here on github, but it was mentioned in the forum link vbgamer45 provided.

**Comment by sbulen** [comment] 2019-06-10 05:08
Is this still happening?   

I cannot reproduce, on WAMP or Linux, on smtp or on php mail.  I get the newsletters to go out...  

I am using github as of now; it's possible all the recent notifications rework had an impact.

**Comment by SychO9** [comment] 2019-06-10 07:08
I can't reproduce it either

**Comment by nolt** [comment] 2019-08-09 20:50
SMF 2.1 RC2 on LXD with apache+mariadb+php7.2. Newsletter is working.

**Comment by frandominguezl** [comment] 2019-09-05 11:43
@VBGAMER45 @MarkRH @sremick  Is this still an issue?

**Comment by MarkRH** [comment] 2019-09-05 23:14
@frandominguez03 Yeah, still **not** (edit: now it is) working for me.  Running SMF 2.1 RC2, PHP 7.2.22, 10.1.41-MariaDB. Says it's added to the queue but when I check it, it's empty, no mail is sent and no PHP errors logged or errors shown in forum.  If my email settings were wrong would it through up an error?

I made a testmail.php following https://wiki.simplemachines.org/smf/E-Mails_-_Why_are_members_not_getting_emails_sent_from_the_forum and it sent an email fine. 

Okay, I changed the email settings to PHP Default and blanked out the SMTP stuff.  Then, I noticed the checkbox to force send regardless of notification settings. Checking that, it did actually add them to the queue.  Click the send queue now button did send the emails out.  

So could have been the mail settings and/or forcing it out.

**Comment by MissAllSunday** [comment] 2019-09-30 17:39
Will close this for now, @MarkRH if you still have problems with the newsletter then please open a new issue.

**Closed as completed by MissAllSunday** 2019-09-30 17:39 UTC
Labels: Mail

**Comment by Turk1938** [comment] 2019-10-20 17:14
Is the a repair for this problem yet.
I have the same problem, newsletter will not send, says it's sent and in Mail Queue, go there nothing..

But if I use the Advance and add all the email addresses and click send, it says sent and in mail queue, and it is in there and I can then send it out.

Thanks

Ron.

**Comment by sbulen** [comment] 2019-10-21 00:21
@Turk1938 - This item is closed as nobody could reproduce it.  I would suggest asking a question in the 2.1 Support Forum:
https://www.simplemachines.org/community/index.php?board=254.0

**Comment by Turk1938** [comment] 2019-10-21 00:26
I did ask on SMF support, apparently they have no answers either..

Thanks for the reply..

Ron.

________________________________

**Comment by sbulen** [comment] 2019-10-21 00:43
**_If you send a link to the thread, we can resume the discussion there!_**

This case is closed.    

In the cases we've seen, it's been mail settings, or something similar.  Note there were some bugs a while back, but we think they're all fixed.  Also note that, in order to avoid spamming forum users, there are checks to PREVENT mailing folks too often, which REALLY confuses things when testing...

**Comment by Turk1938** [comment] 2019-10-21 11:31
SMF Support link: https://www.simplemachines.org/community/index.php?topic=570138.0

I have tried different mail setups, right now I am using PHP and the domain email account. Funny I can send out a message if I use the Advanced process, works great..

But anyway I thank you for your time and help.

Ron..
________________________________
