### ISSUE TITLE
upgrade.php error 

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#3451] opened 2016-05-18 09:09 UTC
+++  Convert member ipsError: Undefined index: a File: D:\wamp\www\github2.1\upgrade.php Line: 5907 +++  Convert member ips2Error: Undefined index: a File: D:\wamp\www\github2.1\upgrade.php Line: 5907 done. 
+++  Convert ips on messagesError: Undefined index: a File: D:\wamp\www\github2.1\upgrade.php Line: 5907 done.

**Comment by jdarwood007** [comment] 2016-05-18 21:33
Thats a result of improvements to the upgrader to not kill the server during the upgrade to ipv6.  I thought the upgrader set a, but looks like we need to define that ourselves.

**Comment by equinoxmatt** [comment] 2016-08-26 18:37
I think the function might need a bit more TLC.  Line 5932 tries to do:

`nextSubStep($substep)`

$substep isn't declared.  Leading to Warning errors.

**Comment by live627** [comment] 2016-12-30 07:55
this seems to be a duplicate of https://github.com/SimpleMachines/SMF2.1/issues/3645, closing this.

**Closed as completed** 2016-12-30 07:55 UTC
Labels: Upgrader
