### ISSUE TITLE
ssi_recentTopics generated links to new posts does not work correctly

### ISSUE THREAD

**Issue by Bopske** [SimpleMachines/SMF#5548] opened 2019-03-27 21:34 UTC
#### Description
ssi_recentTopics in SSI.php in 2.1 is generating links to new messages that do not link to the correct post. 

Compared to the SSI function in 2.0 the 2.1 SSI function drops you on the first message on the page that holds the new post...

Unread link SMF:
https://myforum.com/index.php?topic=23259.msg327172;topicseen#new

Href link from ssi_recentTopics:
https://myforum.com/index.php?topic=23259.msg327173;topicseen#new

### Environment (complete as necessary)
- Version/Git revision: SMF RC1 last_commit_2802e3a 
- Database Type:
- Database Version:
- PHP Version: 7.1

### Additional information/references
When on the page and hit 'Refresh' the page does position to the correct post. 
Symptom very similar to #5477

**Comment by Bopske** [comment] 2019-03-29 07:36
Just checked and tested the solution provided here... #5478 , unfortunately thas fix does not solve the occurrence from SSI (af far as I can see)...

**Comment by frandominguez03** [comment] 2019-04-01 08:03
@Sesquipedalian Was this properly tested? OP says the proposed fix wasn't solving the problem.

**Comment by SychO9** [comment] 2019-05-05 12:50
@Bopske are you using **Show most recent posts at the top in topic view.** ?

**Comment by Bopske** [comment] 2019-05-06 20:04
Not sure what you are asking. We use the SSI function in TinyPortal recent topics. That;s where the issue occurs...

**Comment by jdarwood007** [comment] 2019-05-06 22:37
Can you verify that the log_topics contains the correct information for the topic you are testing?  It should have the correct message id for the relevant member and topic.

**Comment by Bopske** [comment] 2019-05-24 10:23
> @Bopske are you using **Show most recent posts at the top in topic view.** ?

I must have had a 'blonde' moment: answer is no. Not using that setting...

**Comment by Bopske** [comment] 2019-05-24 10:39
> Can you verify that the log_topics contains the correct information for the topic you are testing? It should have the correct message id for the relevant member and topic.

Actually it does not: I did a few tests and checking the database: when a topic spans multiple pages, visiting the first pages updates the log_topics tabel with the correct topic ID and the last message ID of the page visited. But when visiting the last page of the topic the message ID written to the log_topics is a  message ID that is not even part of the topic in question. It seems to update the log_topic with the message id that is actually the latest message ID in the database (not the latest in the topic!)...

**Comment by shnazzle** [comment] 2019-06-11 11:24
A bit confused about where this defect is but I can verify that there is an issue with posting with the Show most recent posts at the top in topic view. option ticked, and also Return to thread by default.
When you reply, it returns to an arbitrary position in the thread. When you turn Show most recent... off, it no longer does this.

**Comment by sbulen** [comment] 2019-09-21 05:21
I do not see this exact issue, but I see almost the exact opposite - the "Latest Post" link on the board index is wrong...  Using today's git...

"bob" just posted a new message, you'll see that it's message 16:
![image](https://user-images.githubusercontent.com/23568484/65368235-63d5c280-dbf3-11e9-95d9-3b6fa8f0a514.png)

If I go to ssi_examples.php, I see that message as the latest message, and it is properly message 16:
![image](https://user-images.githubusercontent.com/23568484/65368284-dfd00a80-dbf3-11e9-8e7c-60b90979b64e.png)

And if I click on the link, I go to the right place.  
![image](https://user-images.githubusercontent.com/23568484/65368288-f7a78e80-dbf3-11e9-8a85-065c96e0f708.png)

However...  On the board index, the last message link is ***17*** not 16:
![image](https://user-images.githubusercontent.com/23568484/65368316-2de50e00-dbf4-11e9-95c2-8ea2a265a1ae.png)

And in fact, msg 17 doesn't exist...  The link works (I guess close enough counts).  

So...  I'm seeing the exact opposite.  SSI is correct, but the home page "Latest Post" link is incorrect.  

Anybody else seeing this?

**Comment by SychO9** [comment] 2019-09-21 05:45
@sbulen that's exactly what I noticed while trying to reproduce this issue

**Comment by sbulen** [comment] 2019-09-21 06:22
And...  2.0 does the exact same thing, with the 'last post' link off by 1...  

I cannot reproduce this.  I have my forum open in 2.0 & 2.1 side-by-side, and I'm clicking on the links in ssi_examples.php, and I am getting the same pagination behavior in 2.0 & 2.1.  Even on long, multi-page threads.  Even with the 'show most recent posts at the top' option on in both.   Current github.  

Screenshots may help???

**Comment by MissAllSunday** [comment] 2019-09-21 16:47
@Bopske Are you able to reproduce this issue using the latest build?

**Comment by Bopske** [comment] 2019-09-22 08:07
I will check...

**Comment by Bopske** [comment] 2019-09-22 19:52
Tried it again today with github built of a week ago: could no longer reproduce it using ssi_examples... so maybe something got changed since I reported it...

**Comment by SychO9** [comment] 2019-09-22 23:42
It probably got fixed along the way, we can close this then

**Closed as completed** 2019-09-23 16:20 UTC
Labels: Topics
