### ISSUE TITLE
track user in others profile visible

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#1885] opened 2014-06-23 14:04 UTC
i can see the option to track user in the profile menu, then an empty option shows as its sub-menu which goes to github2.1/index.php?action=profile;area=tracking;sa=;u=6 and the user is granted with an error that they can not access that page

**Comment by illori** [comment] 2014-06-23 17:03
this only happens if the user is a group moderator 

```
'groupreq' => array($txt['trackGroupRequests'], 'approve_group_requests', 'enabled' => !empty($modSettings['show_group_membership'])),
```

**Comment by illori** [comment] 2014-06-30 16:09
this is not related to the moderation center, it is an error in the profile.

**Comment by Oldiesmann** [comment] 2014-07-08 17:15
Closing this since everything seems to be working as intended after further investigation.

**Closed as completed by Oldiesmann** 2014-07-08 17:15 UTC
Labels: Minor Bug
