### ISSUE TITLE
Attachments UI popup width hardcoded?

### ISSUE THREAD

**Issue by m4z** [SimpleMachines/SMF#7765] opened 2023-06-11 13:29 UTC
#### Description
When having attached a file to a post preview and clicking the "insert into post" blue upload arrow, the popup seems to be fixed width. This is a problem for translations that use longer strings (`$txt['attached_insert_*']`), because the button is pushed outside of the visible area.

Please see the screenshots here: https://www.simplemachines.org/community/index.php?topic=586100.msg4153790#msg4153790

### Environment (complete as necessary)
- Version/Git revision: 2.1.4 / current SMorg
- Database Type: any?
- Database Version: any?
- PHP Version: any?

### Additional information/references

**Comment by DiegoAndresCortes** [comment] 2023-06-11 20:20
Maybe truncate the text and use a title attribute?

**Comment by DiegoAndresCortes** [comment] 2023-06-11 20:21
Maybe...
1. Truncate the text and use a title attribute?
2. Tweak the behavior of these popups a bit.

**Comment by sbulen** [comment] 2023-06-11 21:50
As discussed in the forum, I think those particular translations are too verbose.

**Comment by Sesquipedalian** [comment] 2023-06-12 04:27
I suspect that reopening and merging #7737 will solve this issue permanently.

**Comment by sbulen** [comment] 2023-06-12 06:19
Did that pr allow the box to expand sideways?  That's what's needed here, if we want to allow the long translations.  

I prefer shortening the translations.

**Comment by Sesquipedalian** [comment] 2023-06-12 08:28
It allows the panel to expand *down* even past the progress bar, which means that the button won't disappear. 

The reason that the button is disappearing is that the current combination of z-index and overflow properties causes the bottom of the panel to (1) disappear behind the progress bar and then (2) be cut off when it reaches the edge of the surrounding .roundframe container div.

A robust solution needs to be able to handle unexpectedly large label text without hiding the button. We can and should shorten the translated text, sure. But the issue could also occur other languages. Moreover, it could occur if the browser simply increases the font size. For such situations, the only good solution is to ensure that the panel can expand outside of its container so that the button is not cut off.

**Comment by TwitchisMental** [comment] 2023-06-12 18:56
I have tested the changes of #7377 and can confirm that it does resolve the issue. No matter how long the text is keeps it contained. This could future proof things. 
![Post-reply(2)](https://github.com/SimpleMachines/SMF/assets/98340766/9c981c50-d79e-4cc5-b6aa-2751f22d8b0c)

**Comment by sbulen** [comment] 2023-06-12 19:48
I've got no problem with making the tweak, but we need to make sure the string is fixed as well.  

99% of the problem is that "Insert width (px)" was interpreted as an imperative verb+noun sentence, which, when making it formal, became something akin to "Please provide the width (px)".   

As noted in the forum, this is just a label, not a sentence.  I'd be happy with "Width"...

**Comment by m4z** [comment] 2023-06-13 19:51
I've shortened the German* strings two days ago, but for some reason they aren't available in the language pack downloads yet. (Reported that internally to see if the problem is on the Crowdin or SMorg side.)

**Comment by m4z** [comment] 2023-06-15 05:12
The shortened German strings have landed in the LPs now. 💐 @jdarwood007

**Comment by sbulen** [comment] 2023-07-07 03:45
@Sesquipedalian - could you resubmit that PR with the z-index solution?

**Comment by Sesquipedalian** [comment] 2023-07-07 17:03
> @Sesquipedalian - could you resubmit that PR with the z-index solution?

I have reopened #7737 so that it can be tested and merged.

**Comment by sbulen** [comment] 2023-08-22 03:57
This was closed out earlier.

**Closed as completed by sbulen** 2023-08-22 03:57 UTC
Labels: Attachments, Theme
