### ISSUE TITLE
duplicate options/smiley and message icons

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#560] opened 2013-08-07 10:21 UTC
when you modify a smiley set you have the option to select the default smiley set

when you go to the settings page you have the option there as well to set the default smiley set

this could confuse users. i think we should remove the drop down from the settings page.

**Comment by Arantor** [comment] 2014-01-18 00:14
I'm not convinced this is a duplicate, nor that it will cause confusion. The one in the modify page won't turn up in search results, and it is not intuitive that you would have to modify something to make it default.

Honestly, of all the mistakes for UI that are on the Smileys & Message Icons page, this is not one of them, IMO. That said, show me some suggestion that users are confused by it and I'll reconsider, but for now, I'm going to have to close this.

**Closed as completed by Arantor** 2014-01-18 00:14 UTC

**Comment by illori** [comment] 2014-01-18 00:21
i have no posts that say users are confused, it just seemed strange to be in 2 places to me.

**Comment by Arantor** [comment] 2014-01-18 00:27
That's one of the problems when assessing duplicate options; does it actually confuse them or not? The way they're presented, they can and will be used in different ways - if you create a new smiley set you may want to make it a default right off the bat, which is why it's offered.

**Comment by Xarcell** [comment] 2014-01-18 15:52
I don't think it should be in two places either. However, I don't see it confusing the admin either. 

IMO, I say leave as is, as there are way more important things to tackle. To me, it seems the bug list is getting over-whelming, and I feel bad for the very few trying to tackle it all. I wish I could help, but I would just get in the way at this point. I have a few UI issues(not bugs) myself, but I'll hold on to them until most of the bugs have squashed.

**Comment by Arantor** [comment] 2014-01-18 15:57
Half the problem is the fact that no-one ever really went properly through the bug reports board on sm.org, sorting out what was done and what wasn't. That's why the influx of issues here - but many less over there.

**Comment by Xarcell** [comment] 2014-01-18 16:01
I figured as much. I just feel bad for all the stuff the 3 of you are having to fix. You especially. 

I guess it was a good thing SMF started using Github?

**Comment by Arantor** [comment] 2014-01-18 16:08
It's brought its fair share of challenges, but it's not like we didn't already have the tools for the job between sm.org and Mantis. The problem here is more about not cleaning house. Though I won't argue GH does make it marginally easier to clean house because we can flag issues as resolved with the code that resolves them. (It would be doable on sm.org+Mantis, just as it was for sd.net+Project Tools, but GH is effectively ready made in that respect)

The other thing is that there are bugs that have never been investigated properly that have been around for years. There is a patch in the works for 2.0 to fix a number of issues, some of which are identically present in 2.1 and were known issues even back in the 2.0 RC days but for whatever reason were never fixed.
