### ISSUE TITLE
Still badly is shown cursor in qucik reply (IE11)

### ISSUE THREAD

**Issue by jsqx** [SimpleMachines/SMF#2466] opened 2014-10-28 12:52 UTC
Yo, I recently reported bug with cursor, which isn't show in write window. Just next to emoticons. Bug still is in quick reply.

![quickreply](https://cloud.githubusercontent.com/assets/8003629/4782540/4b6b6204-5cfa-11e4-8d91-2189633999a9.png)

Are you able to do something with it or not? Don't close issue until it won't be checked.

**Comment by XinYenFon** [comment] 2014-10-28 14:07
I can't reproduce this issue on IE11 (11.0.8) - Win10 TP,

**Comment by Oldiesmann** [comment] 2014-10-28 14:51
It should be fixed now with #2463.

**Comment by jsqx** [comment] 2014-10-28 15:11
My version: 11.0.9600.17280

**Comment by MissAllSunday** [comment] 2014-10-28 15:17
@jsgrom  can you please fetch the main repo and test it again?

Every time there is a change on the main repo you need to fetch those changes or if you're not using git, download the files again and make sure your install gets all its files overwritten by the new ones.

**Comment by jsqx** [comment] 2014-10-28 15:41
@MissAllSunday 

For every time I remove old SMF 2.1 along with the database and I'm download new package and installing the clean forum. Believe I have a notion about it.

Cursor is badly shown in quick reply, because in main window of writing post shown is already good.

**Comment by jsqx** [comment] 2014-10-31 12:40
Cursor start flashing in bad place in quick reply when click button to refresh browser, do you understand? Then flashing in this place:

![cursor](https://cloud.githubusercontent.com/assets/8003629/4860700/1a06d1da-60fb-11e4-874b-dc854a3c3e36.png)

**Comment by colinschoen** [comment] 2014-10-31 20:52
What browser is this in @jsgrom ?

**Comment by Oldiesmann** [comment] 2014-11-01 06:14
@colinschoen IE11, as it says in the issue title

**Comment by jsqx** [comment] 2014-11-02 15:46
Previously:

![cursor](https://cloud.githubusercontent.com/assets/8003629/4860700/1a06d1da-60fb-11e4-874b-dc854a3c3e36.png)

Currently:

![smf21cursor](https://cloud.githubusercontent.com/assets/8003629/4875762/8460f036-62a6-11e4-830f-14005afcf05d.png)

Look, I don't know but someone did something with it because see that the position of the cursor was changed, is more next to emoticon. But still shouldn't flashing in this place.

**Comment by Oldiesmann** [comment] 2014-11-03 17:52
The way we fixed this before was to enable auto-focus for the editor. This caused problems because browsers were jumping to the quick reply box instead of whatever content we wanted them to, so we disabled that option for the quick reply box. I'm honestly not sure if we can fix this.

**Comment by jsqx** [comment] 2014-11-05 18:23
A few months ago this problem with cursor in IE11 wasn't, so why now is bad shown in quick reply?

**Comment by Oldiesmann** [comment] 2014-11-07 17:46
We did upgrade the editor to version 1.4.5 a while back, so it's possibly related to that. We'll look into this and see if there's a fix, but it's not really a huge issue.

**Comment by jsqx** [comment] 2014-11-08 09:04
I understand, I don't say that is a huge issue, but cursor in IE11 shouldn't be in this place, just should be in position in editor.

**Closed as completed** 2015-04-02 00:10 UTC
Labels: Editor
