### ISSUE TITLE
RTL Language

### ISSUE THREAD

**Issue by islam2hamy** [SimpleMachines/SMF#1923] opened 2014-06-25 19:20 UTC
The defult Theme Doesn't work good with RTL Language (example: arabic)

examples :

![bug1](https://cloud.githubusercontent.com/assets/7989030/3390141/c9b8ba22-fc9b-11e3-9cff-7b84203c4b12.png)

![bug2](https://cloud.githubusercontent.com/assets/7989030/3390179/43834e12-fc9c-11e3-9658-fc30ab3e3a4d.png)

![bug3](https://cloud.githubusercontent.com/assets/7989030/3390313/ae357d42-fc9d-11e3-80bd-2676bce7cff3.png)

and more bugs about the RTL Language

**Comment by live627** [comment] 2014-06-25 22:22
Do a hard refresh.

**Comment by XinYenFon** [comment] 2014-06-26 08:54
can't reproduce it either.

**Comment by Dragooon** [comment] 2014-06-26 10:30
Closing

**Closed as completed by Dragooon** 2014-06-26 10:30 UTC
Labels: Theme
