### ISSUE TITLE
more errors...

### ISSUE THREAD

**Issue by illori** [SimpleMachines/SMF#2143] opened 2014-07-31 14:11 UTC
Type of error: Critical
The database value you're trying to insert does not exist: topic
Function: execute
github2.1/cron.php
File: F:/wamp/www/github2.1/Sources/tasks/CreatePost-Notify.php
Line: 62

Type of error: Cron
8: unserialize(): Error at offset 81 of 85 bytes
github2.1/cron.php
File: F:/wamp/www/github2.1/cron.php
Line: 199

i think this is related to having a thread waiting approval and the task related to sending out a message that the thread is waiting approval.

**Comment by Oldiesmann** [comment] 2014-07-31 15:36
I have no idea what the issue is here as I'm unable to reproduce any of these. The database error would indicate that there's no "id" in the topicOptions array passed to that function, but that should never happen, and if it did, you should be getting further undefined index errors related to where it's set.

**Comment by illori** [comment] 2014-08-05 11:00
anyone have any other ideas on this? i am still getting these every time the cron.php file is run.

sometimes the unserialized error changes which offset it occurs at. 85 of 102, 81 of 85

**Comment by Oldiesmann** [comment] 2014-08-07 17:31
Something is screwing up the serialized string, but I have no idea what.

**Comment by Arantor** [comment] 2014-08-11 17:15
How about providing the serialised string that's damaged?

**Comment by illori** [comment] 2014-08-11 21:23
```
a:4:{s:10:"msgOptions";a:9:{s:2:"id";i:123;s:7:"subject";s:8:"Re: test";s:4:"body";s:111:"Test<br><br>
```

```
a:4:{s:10:"msgOptions";a:9:{s:2:"id";i:122;s:7:"subject";s:4:"test";s:4:"body";s:72:"
```

**Comment by Arantor** [comment] 2014-08-12 15:31
So what's the content of message 122? Or message 123? Special characters perhaps?

**Comment by Arantor** [comment] 2014-08-12 15:32
Technically, text fields are totally the wrong place for some of this stuff but you can't change to the proper solution reliably until you go UTF-8 only.

**Comment by illori** [comment] 2014-08-12 16:34
It should be only utf-8 it was a 2.1 install from the start.

**Comment by illori** [comment] 2014-08-12 20:59
message 122 was the test of the emoji that does not show up in the message body. i am guessing that 123 had an emoji in it as well along with the word Test.

**Comment by live627** [comment] 2014-08-12 22:49
ah so fixing #2162 will fix this then.

**Comment by illori** [comment] 2014-08-12 23:23
there should be someway to clear the the background tasks so this does not keep filling up the error log? or to remove specific entries in the background tasks.

**Comment by Arantor** [comment] 2014-08-13 12:15
"it should be only utf-8", if only that were what I was getting it, which it wasn't. In the real world where CompSci people are actually allowed to do their job properly, they wouldn't be using bloody text fields for serialised data, but the correct data type: blobs. Unfortunately all the time we're stuck with this evil that is dual encoding we can't use blobs because we can't safely handle the transcoding properly to fix them without rewriting routines that haven't been touched in years (that specifically fix serialised columns)

Once you go UTF-8 only, you can safely convert half the crappy things into blobs as they should be, which has an additional bonus of _never_ mangling any binary data pushed into them. EVER. But all the time we're stuck with this mess of dual encoding, we've got to take the extra hit of using the wrong containers for data.

As for the background tasks, that's easy: just remove the row from the table.

**Comment by Oldiesmann** [comment] 2014-08-13 14:28
Would it be safe to use blob for those on install, since new installs should be UTF-8 only, or do we still need to worry about people using dual encoding even then?

**Comment by illori** [comment] 2014-08-13 21:32
yes it is easy to remove the rows for those that know how, what about those that dont know how? it might be easier to have a UI like we have for the mail queue.

**Comment by Oldiesmann** [comment] 2014-08-14 05:04
Because in most cases you would have no reason to need to remove rows.

**Comment by illori** [comment] 2014-08-14 09:33
then why do we need to remove rows from the mail queue? this is similar to that and we can see what is waiting in the queue. for this we can not from within in the forum.

**Comment by Oldiesmann** [comment] 2014-08-14 19:03
The mail queue is quite a bit different than background tasks. At this point I think it's best that we concentrate on testing and fixing 2.1 instead of building new sections of the admin center.

**Comment by Arantor** [comment] 2014-08-15 20:22
Here's the reason: some things in the email queue may legitimately need to be removed, e.g. defunct emails that are bouncing, or issues with the mail outbounding. But in general that shouldn't be a case with background tasks - the only case I can imagine with that would be is like with the emoji issue and the problem there is not with the background tasks anyway.

**Comment by illori** [comment] 2014-09-18 12:43
i replied to a report on a member and these errors started to return to the log.

the task data is

```
a:7:{s:9:"report_id";N;s:7:"user_id";N;s:9:"user_name";N;s:9:"sender_id";i:1;s:11:"sender_name";s:5:"icari";s:7:"comment";N;s:4:"time";i:1411039125;}
```

**Comment by illori** [comment] 2014-09-18 12:44
Type of error: Cron
8: Undefined index: comment_id
github2.1/cron.php
File: F:/wamp/www/github2.1/Sources/tasks/MemberReportReply-Notify.php
Line: 33

**Comment by Oldiesmann** [comment] 2014-09-20 15:42
That error was fixed with #2345.

**Comment by XinYenFon** [comment] 2015-08-12 15:04
I can't reproduce this with latest build.

**Comment by illori** [comment] 2015-08-15 10:38
Antes did you test with the proper type of character? i dont see that #2162 has been fixed to fix this.

**Closed as completed** 2015-08-18 04:40 UTC
Labels: Notifications
