### ISSUE TITLE
Theme Error: Database error, given array of string values is empty. (query_where)

### ISSUE THREAD

**Issue by Bopske** [SimpleMachines/SMF#3982] opened 2017-03-22 13:42 UTC
After a clean upgrade to version 2.1 I want to create a new theme. When going into admin section Configuration > Theme settings an error message is shown when no themes other than default are available:
Database error, given array of string values is empty. (query_where)

After creating a copy from the default theme this error is no longer shown. Cause is clear: system is trying to fetch a list of themes from the database when nothing is there (yet). The error is not so nice: should simply state that no themes are found en and not write this error to log...

![image](https://cloud.githubusercontent.com/assets/24902644/24200556/bef2aa9e-0f0d-11e7-8a1f-8c19fc144d63.png)

**Comment by albertlast** [comment] 2017-03-22 15:57
Please go to your error liog in admin area and post the complet error information.

**Comment by Bopske** [comment] 2017-03-22 17:59
Database error, given array of string values is empty. (query_where)
Function: get_all_themes

http://test2.fjr-club.nl/index.php?action=admin;area=theme;sa=list;f4bbcf9=f3b5041fef5ee32a4faa06c684478193

http://test2.fjr-club.nl/index.php?action=admin;area=logs;sa=errorlog;file=L2hvbWUvZGViNzc0NTMvZG9tYWlucy9manItY2x1Yi5ubC9wdWJsaWNfaHRtbC90ZXN0Mi9Tb3VyY2VzL1N1YnMtVGhlbWVzLnBocA==;line=139

**Comment by Bopske** [comment] 2017-03-22 18:00
That looks funny 

File: /home/deb77453/domains/fjr-club.nl/public_html/test2/Sources/Subs-Themes.php
Line: 139

**Comment by sbulen** [comment] 2017-03-23 02:36
I cannot reproduce in any of my 2.1 environments at this time.  

Must be some combination of settings...   Will read further...

**Comment by sbulen** [comment] 2017-03-23 06:28
It looks like, upon your fresh install, you were missing either the enableThemes or the knownThemes setting from your settings table...

knownThemes was used throughout 2.0.   enableThemes is created by the upgrader.  

I can't think of a scenario where you would be missing one or the other.    And I cannot reproduce this.

**Comment by Bopske** [comment] 2017-03-23 07:48
It is not a big problem: once I create a new theme the error goes away...

BTW it was clean _upgrade_

What did I do:
Starting point was a 2.0 install with 2 extra themes

- copied and restored a backup database of production forum to test domain
- removed the themes and sources folder before the upgrade
- copied the 2.1 files to the server
- ran the upgrade
- executed repair_settings (the production dbase runs in SSL so all paths to be updated)

Now the forum is up and running

- Added Dutch text files
- Installed two mods that I need:
- Tinyportal and Downloads system

All working perfectly

Then I went into the themes admin area and found that _one_ of the two themes still showing (even though theme folder was removed before upgrade)
I then choose to DELETE the theme there, and the above error is showing. 

important note: the test forum is on a sub-domain of my productive forum. Some time later I noticed that the delete action in the sub-domain actually had deleted the theme folder on the main site!
It seems that somehow a pointer to the main theme location has been kept after updating the test forum...

After creating a new theme and deleting that again the errors do not re-appear...

**Comment by sbulen** [comment] 2017-03-23 15:23
Thanks for the info.  I will try again to reproduce.

**Comment by sbulen** [comment] 2017-03-24 17:14
I cannot reproduce, despite the helpful & detailed steps.  (Though I did not install the mods...)  

Like Arjen, I do have the spurious themes that need to be deleted (in my case, both showed up), but I do not get the error message above after deleting them.   

The theme info for the old themes is displayed in repair_settings.php.   I believe Arjen would have seen the old paths in there.  

Note that I am working on improving the cleanup of stray theme data in the upgrader in this PR, but we are still working thru the best way to approach this:
Clean up old theme data #3964

Since the error here occurred after deleting a non-existent theme, I believe this PR will ultimately address this.

**Comment by Bopske** [comment] 2017-03-24 17:57
As I already stated iT is not a big issue. Thanks for the effort but better focus on important stuff. As far as I am concerned this can be closed

**Comment by colinschoen** [comment] 2017-03-27 07:05
Fixed with #3964

**Closed as completed by colinschoen** 2017-03-27 07:05 UTC
